### ISSUE TITLE
Change 'Parameters' to 'Args' in docstrings

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#101]
We recently decided to adopt 'Args' instead of 'Parameters' in keeping with Google-style docstrings.

**Comment by phargogh** [comment]
This might already be done ... double check and then close?

**Comment by davemfish** [comment]
`$ grep -r -l "Parameters:" src/natcap/invest/ | uniq`
- [ ] src/natcap/invest/sdr/sdr_core.cpp
- [ ] src/natcap/invest/sdr/sdr.py
- [ ] src/natcap/invest/sdr/sdr_core.pyx
- [ ] src/natcap/invest/habitat_quality.py
- [ ] src/natcap/invest/crop_production_regression.py
- [ ] src/natcap/invest/crop_production_percentile.py
- [ ] src/natcap/invest/scenario_gen_proximity.py
- [ ] src/natcap/invest/hydropower/hydropower_water_yield.py
- [ ] src/natcap/invest/finfish_aquaculture/finfish_aquaculture.py
- [ ] src/natcap/invest/utils.py
- [ ] src/natcap/invest/wind_energy.py
- [ ] src/natcap/invest/coastal_blue_carbon/preprocessor.py
- [ ] src/natcap/invest/coastal_blue_carbon/coastal_blue_carbon.py
- [ ] src/natcap/invest/routedem.py
- [ ] src/natcap/invest/globio.py
- [ ] src/natcap/invest/ndr/ndr.py
- [ ] src/natcap/invest/ndr/ndr_core.cpp
- [ ] src/natcap/invest/ndr/ndr_core.pyx
- [ ] src/natcap/invest/hra.py
- [ ] src/natcap/invest/carbon.py
- [ ] src/natcap/invest/datastack.py
- [ ] src/natcap/invest/wave_energy.py
- [ ] src/natcap/invest/recreation/recmodel_client.py
- [ ] src/natcap/invest/recreation/buffered_numpy_disk_map.py
- [ ] src/natcap/invest/recreation/recmodel_workspace_fetcher.py
- [ ] src/natcap/invest/recreation/out_of_core_quadtree.pyx
- [ ] src/natcap/invest/recreation/out_of_core_quadtree.cpp
- [ ] src/natcap/invest/recreation/recmodel_server.py
- [ ] src/natcap/invest/ui/inputs.py
- [ ] src/natcap/invest/ui/usage.py
- [ ] src/natcap/invest/ui/model.py
- [ ] src/natcap/invest/forest_carbon_edge_effect.py
- [ ] src/natcap/invest/seasonal_water_yield/seasonal_water_yield_core.cpp
- [ ] src/natcap/invest/seasonal_water_yield/seasonal_water_yield.py
- [ ] src/natcap/invest/seasonal_water_yield/seasonal_water_yield_core.pyx
- [ ] src/natcap/invest/scenic_quality/viewshed.cpp
- [ ] src/natcap/invest/scenic_quality/viewshed.pyx
- [ ] src/natcap/invest/pollination.py
- [ ] src/natcap/invest/delineateit.py
- [ ] src/natcap/invest/fisheries/fisheries.py
- [ ] src/natcap/invest/fisheries/fisheries_io.py
- [ ] src/natcap/invest/fisheries/fisheries_hst.py

**Comment by emlys** [comment]
This was fixed in #394.
