### ISSUE TITLE
Workbench not responding after logging 10000s gdal warnings

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1023]
Jade reported this and I reproduced it. We ran the rec model with some data that generated many warnings like this:

```
2022-07-01 14:18:15,992 (osgeo) utils._log_gdal_errors(98) WARNING [errno 1] Value 21650600 of field area_m2 of feature 1267 not successfully written. Possibly due to too larger number with respect to field width
```

There are almost 40000 of these in the invest log. I'm not sure how many got logged to the Workbench UI before it stopped responding. I re-ran the same data with logging level set to `ERROR` and avoided the problem. That's the main reason I think the UI logging is the problem.

Even when the workbench stopped responding, invest continues running in the background so the model completed successfully.

[InVEST-natcap.invest.recreation.recmodel_client-log-2022-07-05--17_24_30.txt](https://github.com/natcap/invest/files/9049905/InVEST-natcap.invest.recreation.recmodel_client-log-2022-07-05--17_24_30.txt)

**Comment by davemfish** [comment]
Here's data to reproduce https://drive.google.com/file/d/1k1GURCHM5aWZEAqn_pY8UX8ciFXZWNlj/view?usp=sharing

**Comment by davemfish** [comment]
I also noticed that many log messages are missing from the UI pane. When data comes through stdout so rapidly like this, it seems the workbench can't keep up.

**Comment by davemfish** [comment]
Examining this a bit closer, I think the bottleneck is something called "reflow", when the browser is forced to re-calculate layout, style etc. That can get expensive and we're doing it _a lot_ with our naive approach of updating a `div` `innerText` with each message.

The invest run described above causes 1000s of these warnings in the browser:
```[Violation] Forced reflow while executing JavaScript took <N>ms```

Here's a reference of things that can trigger reflow:
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

Probably we need to optimize how we render the log. Our handling of the stdout stream and even the IPC calls sending the data to the renderer are fine, I think. It's just the way we update the DOM on each new message that is likely the problem.

**Comment by davemfish** [comment]
Okay, even further examination...The forced reflow/layout is a problem, but it's not the only problem. The forced layout is triggered by our method for keeping the scroll at the bottom as the log display updates dynamically:

```
  componentDidUpdate() {
    this.content.current.scrollTop = this.content.current.scrollHeight;
  }
```
If we can accomplish this using CSS, that should solve the forced layout problem.

But, even if I remove this `componentDidUpdate` altogether and forgo any scrolling, the browser still struggles to keep up with the high frequency of logger messages and IPC calls. Some messages are missed, and the browser still hasn't finished updating minutes after the invest model has completed.

**Comment by davemfish** [comment]
Here's our case in pseudocode:

```javascript
// electron main process
pythonProc = spawn('invest run carbon');

pythonProc.stdout.on('data', (data) => {
  ipcMain.send('stdout', data)
})

// electron renderer process
ipcRenderer.on('stdout', (data) => {
  console.log(data)
})
```

I simplified this even further, removing the python subprocess and just looping over 100,000 iterations of `ipcMain.send`. I timestamped the sent message and always found that the last message was received by the renderer within 2ms of it being sent.

_In another test I replaced the IPC communication with websocket communication and found much worse performance. The last message was received 2300 ms after it was sent._

With IPC, if the number (or presumably size) of the messages grows (I tried 1 million iterations), the renderer becomes temporarily unresponsive (as it does with the real invest logging example). But there is still no lag between the message being sent & received. This makes sense because [electron IPC is using "named pipes"](https://www.chromium.org/developers/design-documents/inter-process-communication/) and apparently a pipe's producer will stop sending if the pipe's buffer is full (due to the consumer not keeping up with the producer). https://unix.stackexchange.com/a/339932

So there's no lag between the producer and consumer, but the flow of data does slow down considerably if the buffer fills up. That is consistent with the original observed behavior, where the invest stdout data did not finish sending to the renderer until minutes after the python process completed. (worth noting there was no similar bottleneck writing invest's stdout to file or to Qt with python `logging`)

In theory a larger buffer for the IPC pipe might help, but this is not configurable with node `spawn`. Also it might not help enough. https://github.com/nodejs/node/issues/41611

Can anyone think of anything else to try?

**Comment by phargogh** [comment]
This is such a cool problem, Dave!  And thanks for digging into this so thoroughly.

So it sounds like we have a couple of bottlenecks:

1. We want to avoid events that force the browser to re-render
2. The IPC queue will eventually fill up, and things slow down considerably when the queue is full

So, it seems like maybe a solution would:

1. Consume everything that comes through the IPC buffer as quickly as it is produced
2. Only present the relevant or necessary information to the browser when necessary

If I were on linux in a bash shell, this sounds a lot like 

```
python run sdr &
watch -n 0.1 tail <logfile>
wait
```

(if we assume that the python model is already writing to a logfile)

A similar sort of model might work for us as well, maybe using some internal buffer to consume the logging coming through IPC and then only displaying the last n lines of the logging in the browser at a set interval.  I bet the workbench could do this directly in javascript, but we could also probably configure python's logging to only emit the last n lines so the workbench doesn't need to think about it.  Standard cmdline utilities (watch, tail, etc.) might be an option as well if we feel like distributing them and their source code ... but writing our own in python/cython also would not be that hard.

**Comment by phargogh** [comment]
Oh!  And the errors mentioned in the original post, 

```
2022-07-01 14:18:15,992 (osgeo) utils._log_gdal_errors(98) WARNING [errno 1] Value 21650600 of field area_m2 of feature 1267 not successfully written. Possibly due to too larger number with respect to field width
```

I think these might be improved once we address https://github.com/natcap/pygeoprocessing/issues/273

**Comment by phargogh** [comment]
OK I _finally_ understand why we're getting this warning in the first place: `aoi.shp` has a field of type `ogr.OFTReal`, `area_m2` with a width of 13 and a precision of 11.  That's a problem because:

* ESRI Shapefile measures both width and precision as numbers of ASCII digits - no binary representation of data here.
* The full value of the `area_m2` field is `21650600.00000000000`.
* Because the field has a width of 13, those 11 digits of precision leave only enough room for 2 digits left of the decimal to be stored in the field so a warning is thrown.  Therefore, only `00.00000000000` of the above value can be stored with a width of 13 and a precision of 11.

## Solution 1: resize the field

`ogr.Layer` has a method `AlterFieldDefn` that can be used to resize the field to a known width.  So if it's convenient for us to calculate the width and precision of a field before we create the field, this could work well:

```python
    response_vector = gdal.OpenEx(
        response_vector_path, gdal.OF_VECTOR | gdal.GA_Update)
    response_layer = response_vector.GetLayer()
    response_layer.StartTransaction()
    new_field_defn = ogr.FieldDefn('area_m2', ogr.OFTReal)
    new_field_defn.SetWidth(24)
    new_field_defn.SetPrecision(11)
    response_layer.AlterFieldDefn(
        response_layer.FindFieldIndex('area_m2', 1),
        new_field_defn,
        ogr.ALTER_WIDTH_PRECISION_FLAG)
    response_layer.CommitTransaction()
```

## Solution 2: Let GDAL do it for us

We can also just ask GDAL to resize all the fields for us to the correct width:

```python
    response_vector = gdal.OpenEx(
        response_vector_path, gdal.OF_VECTOR | gdal.GA_Update)
    response_vector.ExecuteSQL('RESIZE aoi')  # where aoi is the layer name
```

PR incoming implementing solution 2 for Recreation.

**Comment by davemfish** [comment]
I have a solution for the Workbench performance issues as well. It really did turn out to be a bottleneck on the browser side -- not consuming the data fast enough. 

1. We were rendering the text data with a very naïve approach that didn't make good use of react's builtin optimizations for rendering. In fact, we were side-stepping react altogether by using `setInnerHTML('big long text string')` on a DOM node, instead of using `jsx`.
2. We were updating react state/props on every stdout update, which ended up being much more frequent than a person would be able to notice anyway.
3. We were resetting scroll position on each of those updates to follow the tail end of the log. And that was triggering the "Forced Layout/Reflow" slowdowns.
4. We keep the entire logfile's text rendered to the DOM even though a very small portion of it is visible to the user at any one time.

There's a number of things we can do to improve things:
1. Store log data in an array instead of one big string, that way react can create a DOM node for each text chunk, and not have to re-render all the text on every update.
2. Create a cache on the react side to ingest the stdout data and only update the component that renders that data every 10ms or so. This reduces the overall number of renders by about 10x for cases like the flood of gdal warnings.
3 & 4. Use a virtualized list component to render the array of log data. This can render only a window of the array, based on whatever portion is currently in view. Basically, it keeps a mapping between the viewport size & scroll position and the indices of the array. And it does other fancy things to estimate the height of a rendered element of the array. For example `react-virtuoso`. This library can also manage the scroll behavior.

I implemented all these things and it seems to work great, except it is a big pain to get `react-virtuoso` to render anything in a `jsdom` environment, where there is no real viewport with real dimensions. That's where I'm stuck now, and I might even consider abandoning the virtualized list altogether if the other optimizations are good enough.

**Comment by davemfish** [comment]
> That's where I'm stuck now, and I might even consider abandoning the virtualized list altogether if the other optimizations are good enough.

They are indeed good enough. In particular these two fixes solve the problem without needing a virtualized list.

>1. Store log data in an array instead of one big string, that way react can create a DOM node for each text chunk, and not have to re-render all the text on every update.
>2. Create a cache on the react side to ingest the stdout data and only update the component that renders that data every 10ms or so. This reduces the overall number of renders by about 10x for cases like the flood of gdal warnings.
