### ISSUE TITLE
Mac cannot read ANSI encoded CSV

### ISSUE THREAD

**Issue by mlacayoemery** [natcap/invest#103]
It seems that on a Mac the attached CSV that is ANSI encoded will not work with InVEST 3.8, but CSV that is encoded in UTF will work. Incidentally both files work on Windows.

[biophysical_ansi.txt](https://github.com/natcap/invest/files/4591706/biophysical_ansi.txt)
[biophysical_utf.txt](https://github.com/natcap/invest/files/4591707/biophysical_utf.txt)

**Comment by phargogh** [comment]
Hey @mlacayoemery , thanks for letting us know about this!  When you say that it won't work on mac, how are you using the tables? Is is that validation doesn't properly recognize it in the UI, or that a model is crashing with an exception?

And which version of InVEST are you running it with?

**Comment by mlacayoemery** [comment]
Hi @phargogh,

Yes, it is the UI validation that is at least initially blocking things for the Annual Water Yield model in InVEST 3.8.

**Comment by mlacayoemery** [comment]
I think that it might have something to do with quoted field strings or accent marks. Perhaps it is not a bug that needs to be fixed and just something users need to be aware of, but I'm not exactly sure that the origin of the issue is.

**Comment by phargogh** [comment]
OK, thanks for the info!  I'll take a look at it and get back to you.

**Comment by phargogh** [comment]
@mlacayoemery the core issue here is that `pandas` assumes that CSVs have a UTF-8 encoding unless we specify otherwise, and there currently isn't a way to specify this in InVEST.

As far as the error message itself is concerned, I'm working on a bugfix for InVEST that will describe the encoding requirement within the validation error message. I hope that'll be clearer than hiding the encoding requirement in the documentation somewhere :)

**Comment by mlacayoemery** [comment]
> @mlacayoemery the core issue here is that `pandas` assumes that CSVs have a UTF-8 encoding unless we specify otherwise, and there currently isn't a way to specify this in InVEST.
> 
> As far as the error message itself is concerned, I'm working on a bugfix for InVEST that will describe the encoding requirement within the validation error message. I hope that'll be clearer than hiding the encoding requirement in the documentation somewhere :)

Great, thanks for the quick work @phargogh

**Comment by phargogh** [comment]
FYI @mlacayoemery this ended up being an issue with how validation was opening up the table to test for the existence of a UTF-8 byte order marker, which has been fixed.

Pandas still uses UTF-8 as the default encoding, though, and so for best (most predictable) results, encoding tables as UTF-8 is recommended.
