### ISSUE TITLE
Show the end of input file path in UI

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1050]
In InVEST versions pre-Workbench, if we add a file path to a UI field whose text string is longer than the visible space, it defaults to showing the end of the file path, which contains the actual file name, and the beginning of the file path will be hidden off to the left. But in Workbench, it defaults to showing the beginning of the file path string, with the file name end hidden to the right.

The first (pre-Workbench) way is much more useful, otherwise you need to arrow-scroll down each entry to verify that you got the right file etc. It's also crucial during trainings, when students are looking at your screen to make sure they got the entries correct, and the part that's important is the ending file name. And now that I can increase the font size in Workbench (yay!), that makes it even more likely that the entire file path won't be shown during trainings (and as my eyes age...)

So here's a request to change back to showing the end of the file path in this case, not the beginning.

**Comment by davemfish** [comment]
Thanks @newtpatrol , totally agree with you. I tried to accomplish this a while back and found it stupidly hard for some reason and put it aside. Surely it can be done though. I'll give it another try.

I'll close this as a duplicate because we're also tracking this in #855
