### ISSUE TITLE
Gura Sample Data produces unnatural banding in slope output

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1067]
The Gura sample DEM used for SDR and NDR both produce slope outputs that have unnatural vertical and horizontal banding.  No errors or warnings are emitted by our slope function (`pygeoprocessing.calculate_slope`), so it'd be useful to look into why this might be.

<img width="671" alt="Screen Shot 2022-08-29 at 3 20 24 PM" src="https://user-images.githubusercontent.com/4583897/187310398-d90f1de0-16d6-4d5e-8206-e0594e1c9adf.png">

One thing that I notice about the Gura DEM is that it's an integer raster.  Perhaps smoothing it out a bit might improve the banding?

**Comment by phargogh** [comment]
We should also verify that the compiled slope function in pygeoprocessing can handle integer pixel values correctly, promoting them to floats.

**Comment by emlys** [comment]
I confirmed that `pygeoprocessing.calculate_slope` reads in integer DEM values as floats. Also, in SDR, a pit-filled DEM is used, which has already been converted to float. 

I suspect the original data might be the cause. A similar banded/squared-off pattern is harder to discern visually in the DEM, but does appear to be there:
<img width="400" alt="Screenshot 2024-03-27 at 10 36 04" src="https://github.com/natcap/invest/assets/43770515/9b3531c7-3cb9-47dc-bdeb-9d16bb36893d"> <img width="400" alt="Screenshot 2024-03-27 at 10 36 18" src="https://github.com/natcap/invest/assets/43770515/20ff45c0-1d69-4b0e-80ad-ca68fb3fdcbe">
