### ISSUE TITLE
Workbench sample data download issues

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1070]
When testing InVEST 3.12 I experienced some bugs when trying to download sample data. I think there are two issues I'm experiencing:

1) Cannot download data into `C:\Program Files`. I was trying to download the sample data into the InVEST install directory.
a) There was no error message or response indicating something had failed
2) In the same session, downloading the sample data again causes the download bar to increment. So If I download all sample data again the bar now reads: 1 of 48

Reproducible steps:
1) Download ALL sample data into `C:\Program Files\InVEST-[version]\`
2) Notice Download bar hangs at 1 of 24
3) In same session download sample data into `C:\Users\[user]\[folder]`
4) Notice that Download bar reads 1 of 48, but does download the data

**Comment by davemfish** [comment]
Cool, sounds like maybe a permissions issue and lack of proper error-handling.
