### ISSUE TITLE
Allow the user to select the workbench's install location

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1078]
@newtpatrol  mentioned this recently since it's convenient to sometimes have all  your InVEST installs in a single place that isn't `C:\Program Files`.  The current Workbench installed (tested on InVEST 3.12.0) does not allow the user to configure the install location.  I've confirmed that this is the case for both "all users" and "only this user".

**Comment by davemfish** [comment]
Seems easy enough

>allowToChangeInstallationDirectory = false Boolean - assisted installer only. Whether to allow user to change installation directory.

https://www.electron.build/configuration/nsis.html
