### ISSUE TITLE
Update build dependency to python-build

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1091]
Over on [conda-forge](https://github.com/conda-forge/natcap.invest-feedstock/pull/13) there was the following recommendation from the bot:

>I noticed that this recipe depends on `build` instead of `python-build`. The conda package name 'build' is deprecated and too generic. Use 'python-build instead.'

Something to look into.

**Comment by phargogh** [comment]
I think this is only an issue in the conda environment, since `build` is still the correct python package.

And as a side note, of course someone has a `python-build` PyPI package that does something related but different!  https://pypi.org/project/python-build/
