### ISSUE TITLE
Habitat Quality: validate or handle inputs in different projections

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1093]
Habitat Quality is one of several models that require all spatial data to use the same SRS. #445 .

But the model does not validate this is true for the inputs. `align_and_resize` is called without doing any reprojection, but with a target bounding box from the LULC input. So rasters with a different SRS will appear to not intersect the target bounding box, even if they do.

Here's an example: https://community.naturalcapitalproject.org/t/habitat-quality-alignment-error/3081/9

HQ could either reproject it's inputs, or validate that all SRS are the same. But this validation is not easy (https://github.com/natcap/invest/issues/558), so maybe easier to reproject everything?

**Comment by dcdenu4** [comment]
>so maybe easier to reproject everything?

I think you're right and this would fall in line with how most other InVEST models operate. I can't remember why I wouldn't have done this unless it was just a large oversight. Maybe something will become clear when I look to do this.
