### ISSUE TITLE
Fix logic in `make deploy` so it works in Windows and Mac build pipelines

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#11]
Right now the build pipelines share the `make deploy` target, which is good. But since we don't build the sample data in the Mac pipeline, `make deploy` crashes on the Mac when it tries to rsync the sampledata to our releases bucket. 

We can either modify `make deploy` or the `ci/mac_mini_build_process.sh` script to better handle this.

**Comment by phargogh** [comment]
This is super relevant to #26 (in progress).  I'll take this on as a part of the binary build task.

**Comment by phargogh** [comment]
This was resolved while taking care of #40
