### ISSUE TITLE
Translation: Workbench should link to the UG in the selected language

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1102]
Once we have translated UG & invest builds, the links to the UG from each invest model tab should link to the language selected by the user in the Workbench settings.

**Comment by davemfish** [comment]
I think we could implement this now in `release/3.13.0` if we want to. It's kind of related to #851 , but could be implemented regardless of that decision. Though if we end up linking to a local UG, we would need to package all language versions of the UG. Maybe that's a reason to keep linking to the remote latest version?

**Comment by phargogh** [comment]
Closed in #1244
