### ISSUE TITLE
Explicitly support python 3.11

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1103]
Python's on it annual release schedule now, so that means that python 3.11 was recently released!  So that also means that it's time to take a look at supporting python 3.11 and whether all of InVEST's dependencies can support it yet.

**Comment by emlys** [comment]
python 3.11 is incompatible with gdal<3.6, and our test suite is failing with a cryptic error with gdal>=3.6. https://github.com/OSGeo/gdal/issues/8497
