### ISSUE TITLE
Allow users to specify the encoding of CSV files

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#111]
InVEST implicitly expects that all incoming CSV files are encoded as `UTF-8`, `UTF-8-SIG` or `ASCII` (UTF-8 is, by design, a superset of ASCII).  It would be nice if we had a way to allow users to specify how the table should be interpreted.

Because `UTF-8` can represent all forms of human writing that have ever been invented, this is a low low priority thing to think about, and feels like a lot of complexity to develop in lieu of establishing a (very reasonable) contract.

**Comment by dcdenu4** [comment]
Does this issue still make sense after our recent CSV endeavors @emlys or @phargogh ?

**Comment by phargogh** [comment]
A part of me will always want to allow the user to define their encoding, but the likelihood that this is actually needed is low.  If we can parse the CSV, that's probably good enough!  I'd advocate for closing.  Any objections @emlys ?

**Comment by dcdenu4** [comment]
Could `icebox` it too I guess. I don't think it'd be too hard an implementation if someone got keen.

**Comment by emlys** [comment]
@phargogh no objections! I agree it seems reasonable to expect people to use UTF8.

**Comment by phargogh** [comment]
Then let's `wontfix` this and revisit it if ever this becomes a problem.
