### ISSUE TITLE
Validation discrepancy between AWY and SDR for watersheds 'ws_id' column

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1116]
A user on the [forum](https://community.naturalcapitalproject.org/t/identificador-de-la-cuenca-hidrografica/3204) was using the same watershed vector for AWY and SDR but noticed in SDR that validation was raising an error in the UI that the `ws_id` was not of type `integer`. They found this confusing since it worked just fine in AWY.

It looks like SDR does some internal validation for that vector and field, but both SPECS indicate that field should be `integer`. Could we better use model SPECS to do validation consistently?

**Comment by davemfish** [comment]
> Could we better use model SPECS to do validation consistently?

I think `validate` does use the `type` property of the spec, but in this case the `ws_id` isn't a top-level arg in the spec. It's nested within `columns` of `watersheds_path`, and I think at one point we decided that `natcap.invest.validate` would only validate the top-level args, and the model's own `validate` should be responsible for nested stuff like this, if the developer thinks it makes sense.

**Comment by dcdenu4** [comment]
>we decided that natcap.invest.validate would only validate the top-level args, and the model's own validate should be responsible for nested stuff like this, if the developer thinks it makes sense.

That's right, thanks the context reminder!

**Comment by phargogh** [comment]
I believe this has been resolved inadvertently in #1204 (as described in #1201) because the `ws_id` field is not actually used, but still validated.
