### ISSUE TITLE
3.12.1 release notes contain 2.6.0 release notes?

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1142]
Something funky happening with the [GH 3.12.1](https://github.com/natcap/invest/releases/tag/3.12.1) release notes. At the bottom there's a `2.6.0` section. Not quite sure what's going on there, `History.txt` looks fine.

**Comment by emlys** [comment]
Very strange! I edited the release notes to remove that section. I did all the steps including generating the github release using the commands in the release scripts, so not sure how that happened.
