### ISSUE TITLE
HQ railroad raster sample data doesn't represent railroads

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1146]
In working on a threat decay issue with HQ I noticed that the _railroad_ threat raster didn't match the railroad class in the LULC raster. It instead looks like the _railroad_ threat raster is mimicking the residential LULC class.

The HQ sample data should be updated to fix this discrepancy which could influence the HQ tests.

**Comment by emilyanndavis** [comment]
@dcdenu4, I've updated the railroad threat rasters in the sample data repo.

I also ran `invest-autotest` and `invest-autovalidate` while pointing to the updated data locally and verified those tests passed.

I couldn't find any references to the sample data in the HQ model test suite (it seems to generating a lot—if not all—of its test data on the fly). Before I update the revision hash, could you double-check `test_habitat_quality.py` and make sure I'm not missing something obvious?

**Comment by emilyanndavis** [comment]
> Before I update the revision hash, could you double-check `test_habitat_quality.py` and make sure I'm not missing something obvious?

Actually, no need! I was able to pull the updated sample data and run all the model tests, and everything passed.
