### ISSUE TITLE
Windows build-binaries failure on GHA

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1151]
This GHA failure is pretty common lately. For example: https://github.com/natcap/invest/actions/runs/3914510430/jobs/6691661359

In the Setup Conda Env step:
```
Pip subprocess error:
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-pyjvumdg\\sphinx-apidoc.exe'
```

**Comment by phargogh** [comment]
I think at one point these packages were not on conda-forge, but both clearly are now.  Let's see if that does the trick!
