### ISSUE TITLE
Proposal: Automate the bugfix release process on Github

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1160]
## Further automate the bugfix release workflow
Our bugfix release workflow consists of a checklist and 3 scripts to be run manually. The scripts have some known issues and so we often end up doing the steps manually anyway. Recent improvements to github command line tools and the github actions interface should make it possible to combine these scripts into one - less room for error.

## Create a mirror repo for release testing
Similar to testpypi, a mirrored copy of the invest repo would let us try out the workflows without polluting the real, user-facing releases. A test repo will be necessary while developing the proposed workflow changes, and also helpful when we want to do a "dry run" of future releases.

## Run the release workflows on Github Actions
Challenges with running the release workflow locally include:
- We have different versions of common command line utilities that may require different syntax 
- Have to install and authenticate CLI tools for github and google cloud
- Have to have certain environment variables set
- Handling the case where there are local changes in the repo
- Validating inputs that are entered manually

Running workflows in the shared, controlled environment of Github Actions simplifies these tasks.

### Current process (abridged from the wiki)
- Run autotest script
- Check out the main branch
- Run the 1st autorelease script, which does the following:
    -  Edit HISTORY.rst for release
    - Update Makefile so that the UG rev matches the latest on UG main
- Run the 2nd autorelease script, which does the following:
     - Create and check out a new branch `autorelease/<version>`
     - Commit the edited files
     - Tag the commit with the release version
     - Push the new branch and tag to the target repository
- Wait for Github Actions builds on `autorelease/<version>` to succeed
- Run the 3rd autorelease script, which does the following:
     - Download release artifacts
     - Create a release on Github with the release artifacts and release notes
     - Create a release on PyPI with the wheels and sdist
     - Create a pull request from `autorelease/<version>` into `main`
- Merge the pull request

### Proposed process (run locally)
- Check out the main branch
- Run the autorelease script, which does the following:
    - Create and check out a new branch `autorelease/<version>`
    - Edit HISTORY.rst for release
    - ~~Update Makefile so that the UG rev matches the latest on UG main~~ **the UG rev should already be correct**
    - Commit the edited files
    - Tag the commit with the release version
    - Push the new branch and tag to the target repository
    - Wait for Github Actions builds on `autorelease/<version>` to succeed **(can automate this with `gh run watch`)**
    - Download release artifacts
    - Create a release on Github with the release artifacts and release notes
    - Create a release on PyPI with the python artifacts
    - Create a pull request from `autorelease/<version>` into `main`
    - Merge the pull request **(can automate this with `gh` - I don't think there's any need to review the PR)**

### Proposed process (run on Github Actions)
- Manually start the autorelease workflow by [clicking a button on Github](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow). The workflow will do the following:
    - Create and check out a new branch `autorelease/<version>`
    - Edit HISTORY.rst for release
    - Commit the edited files
    - Tag the commit with the release version
    - Push the new branch and tag to the target repository
    
    Pushing the tag will trigger the usual build workflow. [If that workflow succeeds, it will trigger another workflow](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow), which will do the following:
    - Download release artifacts
    - Create a release on Github with the release artifacts and release notes
    - Create a release on PyPI with the python artifacts
    - Create a pull request from `autorelease/<version>` into `main`
    - Merge the pull request

**Comment by emlys** [comment]
To handle the situation where builds are failing due to an unrelated issue and we want to go ahead with the release anyway, we could add an option to trigger the second workflow manually. That way we could run it even if the build workflow fails.

**Comment by davemfish** [comment]
From the meeting today, 

It sounds like we think it's still important to have a person download and install the desktop InVEST before publishing a release. So maybe there's an automated workflow for all the steps that lead up to that, and then all the steps that would follow it.

**Comment by emlys** [comment]
Another benefit of hosting the release process on Github Actions would be that it's easier to implement rollback steps vs. in a simple bash script. Actions can conditionally run steps depending on the outcome of previous steps, so we could for instance automatically roll back the pull request if there's a problem with the github release.
