### ISSUE TITLE
A few workbench strings are not translating

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1161]
I noticed a few Workbench strings that are not translating to either chinese or spanish. One on the `Home` tab that's only visible when there are no recent runs to display:
>Set up a model from a sample datastack file (.json) or from an InVEST model's logfile (.txt): 

And a few in the `Settings` modal under the `more info` toggle. 

The "more info" string itself is just missing the `_()` wrapper. But for the others, I think what they have in common is that the strings are quoted with backticks _( \`some text\` ) instead of regular quotes. Could that be screwing up the gettext parsing? If so maybe we also don't have the translations for these strings.

I think the backticks were only used to appease the linter because the strings are long I didn't want to exceed the 80 char line width. There are other ways to deal with that though.

**Comment by emlys** [comment]
Some of the input type labels aren't getting translated either

**Comment by davemfish** [comment]
done in #1162
