### ISSUE TITLE
Option strings not rendering in RST

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1163]
This turned up when working on the Urban Nature Access model, but I see that it's an issue with other models as well.

Anywhere we have an ARGS_SPEC dict with an "option_string", the user's guide rendering of that option string is unformatted:

Here's an example from Scenic Quality:
<img width="681" alt="Screen Shot 2023-01-30 at 2 57 13 PM" src="https://user-images.githubusercontent.com/4583897/215615422-c436479b-0a22-482e-9c32-6526860dfabd.png">

And another from Coastal Vulnerability:
<img width="684" alt="Screen Shot 2023-01-30 at 2 58 32 PM" src="https://user-images.githubusercontent.com/4583897/215615675-c6b7cd8f-90f5-4f6a-bc38-2801948a6951.png">

**Comment by emlys** [comment]
Fixed in #1235
