### ISSUE TITLE
Restart the app when language changed

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1168]
Tell users they must restart the app (or automate restarting it) when the language setting is changed.

- This would eliminate some complexity where the renderer process has to tell the main process to change its language. Instead, the language setting would be constant throughout the life of each process.
- It would fix an (unimportant) loophole where changing the language setting does not affect the "About"/"Report a problem" windows if they are already open. Because they are parallel renderer processes, it would be complicated to communicate the change of language and reload those windows.

The downside is that changing the language setting is a larger interruption to using the app, but 
- we already reload the renderer process, which closes all your tabs
- requiring restart for settings to take effect is a common pattern
- we don't expect users to change this setting very often

### current process
(on startup)
1. main process starts
2. renderer process starts
3. renderer process reads language setting from storage
4. renderer sets its i18n instance to that language
5. via IPC, renderer tells main to change its language
6. main sets its i18n instance to that language
 
(on change of the language setting)
1. renderer process updates the language setting in storage
2. renderer process restarts (`window.reload`)
3. repeat steps 3 - 6 above

## alternative
(on startup)
1. main process starts
2. main process reads language setting from storage
3. main process sets its i18n instance to that language
4. renderer process starts
5. renderer process sets its i18n instance to that language (could be read from a variable exposed in preload)

(on change of the language setting)
1. renderer process (tells main process to) updates the language setting in storage
2. user quits and restarts the app
3. repeat steps 1 - 5 above

**Comment by davemfish** [comment]
I think this alternative plan is a really good one. It requires figuring out a good way to manage persistent data available to the `main` process. Right now we have that sort of data (i.e. "invest settings") stored in the browser using `localForage`. But for this language setting, and probably others too, it might make a lot more sense to manage them all via `main` and just make `ipc` calls from the renderer when the user changes them.

This looks like a simple solution: https://github.com/sindresorhus/electron-store

**Comment by emlys** [comment]
As part of this work, also should revisit the mysterious warning that appears in the renderer tests (but not when running the app for real):
`react-i18next:: You will need to pass in an i18next instance by using initReactI18next
`

**Comment by davemfish** [comment]
It looks like this is a common pattern and we can use `app.relaunch` ourselves to take the burden off the user. https://www.electronjs.org/docs/latest/api/app#apprelaunchoptions

With some extra consideration we can probably also allow the `python` process to persist, saving the bulk of the shutdown & startup time costs.
