### ISSUE TITLE
Urban Nature Access: support a proportion of urban nature instead of binary 1/0

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1180]
@lmandle suggested that we modify the Urban Nature Access to support a proportion of urban nature in a pixel rather than a strict binary 1/0 classification.

It would be helpful to spec this out a bit more and be sure that we update all the needed places:
- [ ] model source
- [ ] MODEL_SPEC
- [ ] sample data
- [ ] user's guide

**Comment by lmandle** [comment]
It looks like Andreas tried to do this in his forked version of the UNA model (see slack thread here: https://stanford-natcap.slack.com/archives/C02FLK8C0A2/p1659740498859329) Do you have access to that, @phargogh ?

**Comment by phargogh** [comment]
Yep!  Andreas implemented the change in https://github.com/natcap/invest-mental-health, which is based off an older version of the Urban Nature Access model.

To make this ready for release, we would also need to implement tests, update the input descriptions, add sample data, and make sure the user's guide reflects the change.  And with the meetings next week, I just don't think I'll have time to make it happen.

**Comment by lmandle** [comment]
Oh, sorry I wasn't clear - I fully support waiting to add this feature! I just didn't want to lose track of where it had been tried out before.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by phargogh** [comment]
@lmandle oh, for sure!  I was mostly stating my rationale for my own memory on this ... I did remember that we had talked about this feature at some point and agreed that it would make sense to push off to a future release, and I forgot to include that important information in my post (and I'm sorry about that!)

**Comment by phargogh** [comment]
Because of https://github.com/natcap/invest/issues/1354 proportions might not be represented in the sample data.
