### ISSUE TITLE
Why does SDR still require the ws_id field in the watershed input?

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1201]
A user brought this up on the forum today, noting that SWY does not require that the watershed input have a _ws_id_ field, but SDR does. I'm pretty sure that the only reason that SDR does is legacy from the days when we provided a valuation step, such that different watersheds had different valuation parameters assigned. But we don't do that any more, so is there any reason to require the _ws_id_ field in SDR? Can we remove that requirement?

**Comment by phargogh** [comment]
Looking at the SDR source code, I can confirm that the `ws_id` field is no longer required and is not used _except_ to validate that the field exists.  So no need to have it there!  I'll pull it.
