### ISSUE TITLE
Duplicate array_equals_nodata functions

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1213]
I noticed that both `natcap.invest.utils` and `pygeoprocessing.geoprocessing` have an identical `array_equals_nodata` function.

https://github.com/natcap/invest/blob/dd23b43b01fbc47d2fcfd55349a81d42e130b7ae/src/natcap/invest/utils.py#L968

https://github.com/natcap/pygeoprocessing/blob/e1437c4494e1298b66b0655f7c2d378d3f49b8ae/src/pygeoprocessing/geoprocessing.py#L610

I think this function makes sense in pygeoprocessing since it is useful outside of the invest use case. I'm wanting to use it in other scripts but don't want to have to `natcap.invest` be a dependency.

**Comment by phargogh** [comment]
@dcdenu4 I think this might have been a recent addition!  Once we do the pygeoprocessing release we can decide how we want to handle the duplication.

**Comment by dcdenu4** [comment]
Ah, I see that now as it's used in the new `raster_reduce` function. Sounds good.

**Comment by emlys** [comment]
Yeah, I needed this in `raster_reduce` so I just copied it over. I agree it belongs in pygeoprocessing rather than invest utils, but I didn't want to have to update that everywhere in invest as part of implementing `raster_reduce`

**Comment by emlys** [comment]
On hold awaiting the next pygeoprocessing release.

**Comment by emlys** [comment]
Fixed in #1437
