### ISSUE TITLE
Dropdown menus display their values, not the `display_name` from MODEL_SPEC

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1217]
When I load up a model that has a dropdown menu in the workbench, the menu shows the option's key (which is the string that the model expects) rather than the `display_name`.  Here's an example from scenic quality, compared with what's in the MODEL_SPEC:

<img width="869" alt="Screen Shot 2023-03-01 at 10 37 41 AM" src="https://user-images.githubusercontent.com/4583897/222234231-26ddcf3c-0cda-4322-a3b2-2428c90915b3.png">
<img width="596" alt="Screen Shot 2023-03-01 at 10 37 54 AM" src="https://user-images.githubusercontent.com/4583897/222234240-3b0382d4-641e-4e58-bbfd-7a2f0e178e9a.png">

For us English speakers this isn't an issue because we can just make the keys (what the model expects) more human-readable.  But that also means that the dropdown menu options won't be translated.

**Comment by emlys** [comment]
Fixed in #1235
