### ISSUE TITLE
Workbench images in About and Report menus are missing

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1220]
I think this was an overlooked bug we created recently, in the `release/3.13.0` branch.

When moving the content of `about.html` and `report.html` to `.jsx` we broke a reference to a few image sources:

`<img src="/src/renderer/static/invest-logo.png">`

Previously, `vite` did its magic by finding & replacing this path for us during the build process, to point to the comparable location in `build/`. But I'm guessing that only works for html documents, not `.jsx`. So now the production javascript still points to a `src/` folder which doesn't exist.

**Comment by emlys** [comment]
Whoops, I didn't realize those pages were supposed to have images!

**Comment by emlys** [comment]
Fixed by #1233.
