### ISSUE TITLE
Update website download links

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1224]
Since we're deprecating the classic version of the UI, need to remove that from the download links on the website.

https://github.com/natcap/invest-download-links

**Comment by davemfish** [comment]
At the same time we should also slightly adjust some text on the website. In the "What's the new Workbench" section, I think it's okay to leave that section in place for a while, but just remove the last sentence:

>For now the classic application is also available, but the Workbench is the future of InVEST.

I can do this when the time comes. Help me remember, Doug!
