### ISSUE TITLE
Should we make our `taskgraph` cache directory structure and location consistent across models?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1230]
This has become a little more clear due to the `MODEL_SPEC['output']` work just how many different names and directory hierarchies we have for the taskgraph cache directory.  There are varying names and locations across many of the models, and some even write files to the same directory as the cache database.

Now that we're maintaining some additional information in the MODEL_SPEC about the taskgraph cache (and other files, of course), it might be worthwhile to standardize this across all model runs.

**Comment by dcdenu4** [comment]
Yep, I agree.

**Comment by emlys** [comment]
This would be great!

**Comment by dcdenu4** [comment]
We decided that this would be nice to do, but should note in History that this will cause previous runs to re-run jobs.

**Comment by davemfish** [comment]
Let's note the directory name & location in our invest dev wiki https://github.com/natcap/invest/wiki/spec_invest#taskgraph
