### ISSUE TITLE
Workbench desktop icon is cropped/squashed

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1236]
After replacing the interim icon with our standard `InVEST.ico` icon, the icon - as it appears in the Windows tray, or in the upper-left corner of the Workbench window - is not even close to square.

**Comment by emlys** [comment]
@davemfish I'm not sure if I'm seeing the same thing on mac - here's what it looks like for me. 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/43770515/223569646-23aeb062-6812-45ee-9507-f949fb77e2e9.png">
It's not square, but it's proportional to the original image - it just seems to be ignoring the blank space that pads the top and bottom of the image to make it square. Is this what you're seeing, or is it more distorted?

**Comment by phargogh** [comment]
Here's what I'm seeing on Windows 11 Pro 22H2:

In the Windows tray things look pretty normal:
![Screenshot 2023-03-07 145457](https://user-images.githubusercontent.com/4583897/223572917-a64c4939-cfcf-40a5-a85c-b4d3e523d1b0.jpg)

And in the window corner, the image definitely does not: 
![Screenshot 2023-03-07 145521](https://user-images.githubusercontent.com/4583897/223572947-505e817c-626d-45a1-bd5d-cfb1242dfadd.jpg)

**Comment by emlys** [comment]
Possibly related: https://github.com/electron-userland/electron-builder/issues/2128

**Comment by emlys** [comment]
Fixed in #1240
