### ISSUE TITLE
Workbench Windows test failure

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1239]
There's a new failure that popped up for just the Windows Workbench tests. I'm not sure if it's related to PR #1222 or a new separate issue.

https://github.com/natcap/invest/actions/runs/4327838148/jobs/7608191125#step:8:19

**Comment by davemfish** [comment]
I tried to resolve this race condition in #1222 but apparently failed.

**Comment by dcdenu4** [comment]
Currently skipping effected test on Windows and I think we're okay living with that for now. Closing.
