### ISSUE TITLE
Figure out fonts for Chinese

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1254]
The workbench logs are full of this message:
```
Electron Helper (Renderer)[59185:2237923] CoreText note: Client requested name ".PingFangSC-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```
We're not intentionally requesting a different font for Chinese, and the default seems to display just fine. But we should figure out how to prevent this message from showing up, and confirm whether a different font would be better.

**Comment by emlys** [comment]
This seems to be an underlying issue in chromium. It's reproducible by rendering a Chinese character in a basic electron app. 
https://github.com/electron/electron/issues/33317
https://bugs.chromium.org/p/chromium/issues/detail?id=1131559&q=NewYork-Regular&can=2

**Comment by zzswang** [comment]
Is there a workaround now?

**Comment by zzswang** [comment]
Actually, I run into this issue in a project with electron.
And find this issue from electron repo.

There are full of annoying warnings.

<img width="1082" alt="image" src="https://github.com/natcap/invest/assets/1524745/0e7b680c-c794-477e-826f-71e158d740e1">

Finally, I found a workaround, not perfect, but it worked for me:

- remove the font `BlinkMacSystemFont` in css
