### ISSUE TITLE
Cannot re-open Workbench after closing the main window, if a UG window is still open

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1258]
User Guide windows are independent of the main electron window. That means it's possible to close the main window and leave the UG window open. That seems okay, except it prevents the user from re-opening the main window unless they first close the UG window. Because of our `requestSingleInstanceLock()` logic. All the electron & python processes remain open until all windows are closed, as we currently have it configured.

We could close all the windows when the main window closes - as we do for the `About` and `Report` child windows. There was a reason I didn't assign the main window as the `parentWindow` for the UG, but I can't remember why.

**Comment by emlys** [comment]
On mac, I can't reopen the workbench after closing the window, regardless of other windows. Clicking the X should be equivalent to minimizing the window. It appears to do so, but clicking on the invest icon in the dock causes it to crash, rather than reopen.
