### ISSUE TITLE
Middle-clicking a workbench tab opens a new blank window

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1261]
When I ran an InVEST model in the workbench 3.13.0 release candidate, I went to close a model tab like I do in my web browser: by middle-clicking the tab.  Doing so brought up a window:

<img width="853" alt="Screenshot 2023-03-17 at 3 11 38 PM" src="https://user-images.githubusercontent.com/4583897/226062092-d05e8bbf-d4bd-4e65-8424-5d6699e41a57.png">

I think I would expect it to close the tab, but maybe middle-click is supposed to indicate some other type of action?

To reproduce (at least on my mac):
1. run a model in the workbench on the sample data
2. When the model finishes executing, middle-click the model tab
3. Observe new window opening.

**Comment by davemfish** [comment]
Interesting, I'm not a middle-clicker, but this must be the default middle-click handler for links that is opening the new window. Despite the model tabs looking like tabs, they are in fact links:

```
<a href="#" role="tab" data-rb-event-key="2119562675" aria-selected="true" class="nav-link active"> Nutrient Delivery Ratio</a>
```

I think we could add a custom handler to support the middle-click-close-tab feature for these `.nav-link`. Should we leave the behavior for other links as-is? Such as the UG & Form links.

**Comment by dcdenu4** [comment]
>this must be the default middle-click handler for links that is opening the new window. Despite the model tabs looking like tabs, they are in fact links

Yes, I'm always middle clicking links to open them in a new window, so this makes sense. But since they do look like tabs and act like tabs, I can see middle click closing them. But I would want to leave other links defaulted I think.
