### ISSUE TITLE
Workbench sample data download links to 3.10.2 in dev mode

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1267]
I was seeing how the Workbench handled downloading sample data and noticed the `BASE_URL` was manually set to 
` const BASE_URL = 'https://storage.googleapis.com/releases.naturalcapitalproject.org/invest/3.10.2/data';`
on the latest `main` branch.

We're currently on release 3.13.0. I'm wondering if there is another way to keep this synced up via config file or otherwise.

**Comment by davemfish** [comment]
You had me panicking for a minute @dcdenu4 ! But I think we have this covered. That url, which I I think you found in `renderer/DataDownloadModal/index.jsx`, is the fallback. The production URL should be found in a token created during the build process. 

see `package.json` scripts
```
"token": "cd .. && make jprint-DATA_BASE_URL > workbench/resources/storage_token.txt",
```

**Comment by davemfish** [comment]
Nevertheless, that fallback URL could certainly be updated to the latest release. Probably it is there to make the component functional in dev mode. And that probably deserves a code comment.

**Comment by dcdenu4** [comment]
I knew something was up and I was missing something after posting this issue because obviously everything works fine and Urban Nature Access sample data downloads. Thanks for the rundown and sorry for the scary post!
