### ISSUE TITLE
macos binary build failure: `ImportError: cannot import name 'FailedProcessError'`

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1273]
mac binary builds are failing with this new error:
```
python3 -m build --wheel
Traceback (most recent call last):
  File "/Users/runner/micromamba-root/envs/env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/runner/micromamba-root/envs/env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/runner/micromamba-root/envs/env/lib/python3.10/site-packages/build/__main__.py", line 21, in <module>
    from build.env import IsolatedEnvBuilder
ImportError: cannot import name 'FailedProcessError' from 'build' (/Users/runner/micromamba-root/envs/env/lib/python3.10/site-packages/build/__init__.py)
```
We're installing the same old version of `build` (0.7.0) so that hasn't changed. But it seems like it's getting mixed with a newer version somehow - `FailedProcessError` doesn't exist in the 0.7.0 source code. 

The conda-forge `build` channel is still on version 0.7.0, but the latest available from PyPI is 0.10.0. Installing from PyPI instead might fix the problem.

**Comment by phargogh** [comment]
@emlys interestingly, the corresponding `conda-forge` package changed from `build` to `python-build`.  I bet updating that package name will address the issue.

**Comment by emlys** [comment]
Oh interesting. It looks like we're specifying `python-build`, but the environment contains both `python-build` 0.9.0 and `build` 0.7.0. https://github.com/natcap/invest/actions/runs/4612373494/jobs/8153210333?pr=1272

**Comment by emlys** [comment]
We have `build` in `requirements-dev.txt`, which is correct because that's what it's called on pypi. The problem seems to be that we're assuming the package names in `requirements-dev.txt` and `requirements.txt` are interoperable with conda, which is not the case here.
