### ISSUE TITLE
Inconsistency in ARGS_SPEC argument `name` values

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#128]
The `name` property of an argument's spec is used by the electron UI as the display name next to the input field. It's useful to display the type of input required (vector, raster, csv, number, etc) along with name because not all names are self-explanatory. Some models include this type info in the `name` property itself (e.g. "Watersheds Vector"), while others do not. 

Since the `type` property of an argument's spec always includes this type info, I propose we consistently strip it from the `name` property and display it in the UI by reading the `type` property.

**Comment by davemfish** [comment]
Emily also pointed out there are inconsistencies in the case of names (title case, sentence case etc). So we can standardize on that as well.

**Comment by emlys** [comment]
Closed in #486.
