### ISSUE TITLE
Does InVEST support non comma separated table inputs?

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1296]
There have been many forum posts where a user will have semicolon separated table inputs for their CSV. The Users Guide usually says that comma separated is required. However, I _think_ InVEST doesn't hold a tight contract on this and will let Pandas mostly handle this...

When errors come up on the forum from users with semicolon tables, Stacie and others will often suggest using commas instead as that is what the User Guide recommends. Even if this is not the cause for the error.

I think we should have more clear and tight contracts around this. If we do support semicolon and other separators we should say as much in the Users Guide. Likewise, if we don't want to fully support that we should validate tables upfront or early in model runs to provide useful feedback and not "casually try" to make it work.

**Comment by davemfish** [comment]
I don't think there are any cases where we require a comma. At least whenever we're using the `utils` functions we have for reading CSVs, we're letting pandas determine the separator.

**Comment by phargogh** [comment]
We decided that we're letting pandas decide what the separator should be, so the UG should reflect this.

In the user's guide's `getting_started` page, there is also a mention that separators must be commas.

**Comment by emlys** [comment]
Done! https://github.com/natcap/invest.users-guide/issues/130
