### ISSUE TITLE
 Wind Energy fails when no grid points provided intersect the AOI 

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#13]
Mentioned on the forums: https://community.naturalcapitalproject.org/t/error-running-offshore-wind-energy-with-custom-aoi-and-custom-grid-land-points/513

Original issue: https://bitbucket.org/natcap/invest/issues/3922/wind-energy-fails-when-no-grid-points

Apparently I was already working on this in my fork on the `bugfix/WINDENERGY-3922-error-when-no-grid-pts-intersect-aoi` branch.  Might want to dig that out.

**Comment by emlys** [comment]
Hey @phargogh, is this still a work in progress?

**Comment by phargogh** [comment]
I had started to look into this, but it's so long ago and what I had done was so trivial that I can't actually say that it's in progress. I've removed the label.
