### ISSUE TITLE
Does SWY work as expected with negative DEM values?

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1315]
Confirm whether SWY works with negative DEM values.

**Comment by dcdenu4** [comment]
For SWY I think the DEM is mostly used in pit filling -> flow direction -> flow accumulation -> streams. This is the same for SDR and NDR, so if there is an issue it'd be an issue there as well.

**Comment by emlys** [comment]
I looked over the pit filling and flow direction functions and I see no reason why they shouldn't work with negative DEM values. So to answer this question from the science team, yes, SWY and the other models should work with negative DEM values. Since no issue with this behavior was reported, I don't think we need to do anything further.
