### ISSUE TITLE
Expose the `dtype` parameter of `pandas.read_csv` in `utils.build_lookup_from_csv`

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1319]
Underlying `utils.build_lookup_from_csv`, we use `pandas.read_csv` to read in the file. [`read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html?highlight=read_csv) has many options, including `dtype`, which lets you set a data type for each column. `pandas` will interpret each value in the column as an object of that type, or raise an error if it can't do so.

Exposing this option would be useful to address #1278 and prevent similar bugs in other models. Because we're not specifying the dtype, pandas infers it. The resulting dtype can change depending on the user data. In #1278, the user had all integer values in the ID column, so `pandas` set the dtype to `int`. If there were any non-numeric values, `pandas` would set the dtype to `str`. We should enforce a `str` type, an `build_lookup_from_csv` is an easy place to do that.

**Comment by phargogh** [comment]
I agree, I think it'd be helpful to expose `**kwargs` in the `build_lookup_from_csv` function.  This was probably an oversight on our part!
