### ISSUE TITLE
SWY's limits on the GDAL Cache Max is limiting

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1320]
SWY is unique among the InVEST models in that it makes a call to `gdal.SetCacheMax`.  We had a [support case over slack](https://stanford-natcap.slack.com/archives/CECFUU1DW/p1685049456935449) where, given a Float32 DEM of the entire country of Pakistan, the model was just outrageously slow.  When given an Int16 version of the same raster, the model was quite performant.  Removing the one line that set the cache limit, the model completed in a very reasonable amount of time, several orders of magnitude faster than with the cache limit in place.

By default, [GDAL uses 5% of the system's installed memory](https://gdal.org/user/configoptions.html#performance-and-caching) for caching, which is significantly more than what SWY was restricting it to.  In this case, we were likely invoking a pile of extra disk reads because of cache misses during pitfilling that were avoided when we set the cache limit.

**Comment by phargogh** [comment]
Well, I don't remember specifically.  Looking at [this GDAL RFC](https://gdal.org/development/rfc/rfc26_blockcache.html), maybe the default block cache was only 40MB?  If this is true, then the SWY cache limit would double the size of the GDAL block cache and would have made the model more performant as a result.

Now that the GDAL default cache size is set to 5% of the installed memory, I think that's an extremely reasonable default that should be fine for the majority of use cases.  Only when we have an unusual system (like a high-memory node on an HPC cluster) should it be necessary to fine-tune the cache maximum.

**Comment by emlys** [comment]
Would it be useful to expose that parameter and optionally allow GDAL to use even more memory?

**Comment by dcdenu4** [comment]
>Would it be useful to expose that parameter and optionally allow GDAL to use even more memory?

I don't think it'd be necessary for general use of InVEST. As noted in this case, just letting it sit at the default 5% provides reasonable performance. But, I could see exposing it or thinking more about performance if we take on infrastructure to support global runs or like James mentioned start running jobs on HPCs or something. Just my quick thoughts!

**Comment by phargogh** [comment]
> Would it be useful to expose that parameter and optionally allow GDAL to use even more memory?

I agree with Doug that the 5% default is probably good enough for most uses of InVEST, and if we have a use case (like HPC scripts) where we need to tweak the cache, we can.

On the other hand, this could be a good preemptive thing for us to expose for cases where a user of the workbench has suuuuuuper long flow paths that stretch across many pixels and blocks.  If there are cases like that, a user might benefit from a setting for this.
