### ISSUE TITLE
Urban Nature Access: some outputs should reflect nodata pixels in population raster

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1326]
@Yingjie4Science mentioned in a [slack message](https://stanford-natcap.slack.com/archives/CECFUU1DW/p1686504301627049) that while some raster outputs of the Urban Nature Access model have nodata holes where the population raster is nodata, there are other rasters (`urban_nature_supply.tif` and `urban_nature_balance_totalpop.tif` were specifically called out) that seem like they should also have nodata where the population raster is nodata.

This is specifically using the `greenspace` execution mode with `dichotomy` kernel.

I think this is a bug in the model, but I'm looking into it a bit more to figure out why.

**Comment by phargogh** [comment]
Here's a summary of what I've found so far, summarized as 4 representative files:

<img width="1043" alt="Screenshot 2023-06-14 at 10 14 50 AM" src="https://github.com/natcap/invest/assets/4583897/d3bc8a80-d12b-40d9-9799-514bf6eae8df">

1. The LULC has no nodata holes.
2. The population raster has some nodata holes in places where there are no residents, like in Golden Gate Park.
3. The output file `output/urban_nature_balance_percapita_demand100.tif` ("demand per capita") has valid pixel values for the entire raster.
4. The output file `output/urban_nature_balance_totalpop.tif` ("balance") has valid pixel values only where both the LULC and the population rasters have valid pixel values.

The question here is: should the _demand per capita_ raster have valid pixel values where the LULC or population rasters do not?

Functionally, the model isn't doing anything wrong here.  The way that we are using a non-normalized convolution is to add up (and potentially weight) all of the people within a certain radius of some urban nature.  Thus, a pixel that is nodata in the LULC could, in fact, have nonzero people within the search radius and therefore have a computed value, as we see in the _demand per capita_ raster.  The _balance_ raster, on the other hand, is directly computed as the product of another output with the population raster, so if the population raster is nodata, _balance_ cannot be calculated.

But, I agree with the notion that we might want to be more consistent with which pixels we _want_ to have as outputs and mask accordingly.

**Comment by Yingjie4Science** [comment]
After filling the NA in Pop ![image](https://github.com/natcap/invest/assets/40079217/dbb5981f-1ab5-4740-9989-323811652a46)

**Comment by phargogh** [comment]
I think we resolved this by deciding that the population raster really needed to have its nodata values filled.  Closing this issue, but feel free to reopen if needed!
