### ISSUE TITLE
Document changes under model banner in HISTORY

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#133]
Looking over the design document (Design Doc: InVEST Launcher (and download manager?) ) I thought a simple but effective solution to knowing whether a model has been updated in any given release would be to document model changes under the models name from args_spec.

For instance, a sample of the InVEST 3.8.0 HISTORY of changes  might read as:

InVEST 3.8.0
--------------
- General:
    - Created a sub-directory for the sample data in the installation directory.
    - Updating the psutil requirement to avoid a possible import issue when building binaries under WINE. Any version of psutil should work except for 5.6.0.
    - Fixed a file cache flushing issue observed on Debian in utils.exponential_decay_kernel_raster that would cause an exponential kernel raster to contain random values rather than expected value.
- Recreation:
    - Fixed a bug in Recreation Model that was causing server-side code to execute twice for every client-side call.
    - Fixed a bug in Recreation model that did not apply results_suffix to the monthly_table.csv output.
    - Speed and memory optimization of raster processing in the Recreation model.
- NDR:
    - Fixed an issue with NDR where the model was not properly checking for the bounds of the raster, which could in some cases lead to exceptions being printed to the command-line. The model now correctly checks for these raster boundaries.
    - Fixed an issue in the NDR model that would cause an exception if the critical length of a landcover field was set to 0.

Using the args_spec model name could also allow hooks for future UI features such that the HISTORY file could be parsed via versions and then via models to display something helpful to the user. 

GDAL does something similar in breaking down changes: https://github.com/OSGeo/gdal/blob/v3.1.0/gdal/NEWS

**Comment by phargogh** [comment]
Interesting!  I'm OK with grouping changes like this, and I agree that it would make it easier to discern whether something has changed for a particular model that one cares about.

**Comment by davemfish** [comment]
I'm in favor of doing this. There are definitely times when I go back to HISTORY to see if there have been changes to a specific model. And I agree that we should use consistent names as you suggest.

**Comment by phargogh** [comment]
For the sake of keeping track of the conversation, we've also started discussing this over in PR #150 (https://github.com/natcap/invest/pull/150#discussion_r434667292)

**Comment by dcdenu4** [comment]
I think this has been formally introduced now and can be closed. At the top of HISTORY is a commented section of model names for bundling bug fix updates.
