### ISSUE TITLE
InVEST models don't validate input vector geometry

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1374]
There was a user who was getting odd results on the [forums](https://community.naturalcapitalproject.org/t/why-does-the-sdr-model-complete-and-produce-a-tif-file-but-fails-to-show-the-content-in-qgis/3993/7) and it turns out they were passing in a watershed vector with a line geometry instead of a polygon.

Can we validate vector geometry type through the MODEL_SPEC?

**Comment by davemfish** [comment]
Offhand I know that CV does this validation for a few inputs, and it's somewhat verbose, so standardizing the approach sounds nice.

```python
        vector = gdal.OpenEx(args['slr_vector_path'], gdal.OF_VECTOR)
        layer = vector.GetLayer()
        # all OGR point/multipoint codes
        if layer.GetGeomType() not in [
                ogr.wkbPoint, ogr.wkbMultiPoint,
                ogr.wkbPointM, ogr.wkbMultiPointM,
                ogr.wkbPointZM, ogr.wkbMultiPointZM,
                ogr.wkbPoint25D, ogr.wkbMultiPoint25D]:
            validation_warnings.append(
                (['slr_vector_path'], POINT_GEOMETRY_MSG))
```
