### ISSUE TITLE
Add support for python 3.12

### ISSUE THREAD

**Issue by emlys** [natcap/invest#1425]
python 3.12 was released 10/2/2023.

**Comment by emlys** [comment]
On hold until there is a GDAL and pygeoprocessing release compatible with python 3.12.

**Comment by phargogh** [comment]
Pygeoprocessing now supports python 3.12, we should do this.

Also, when this is done and released, we should be sure to re-add python 3.12 support (which will probably involved a `conda smithy rerender -c auto`)
