### ISSUE TITLE
NDR working group follow up

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1438]
Related to #1044

Placeholder issue reminder

**Comment by phargogh** [comment]
@dcdenu4 the main docs I can find related to the deep dive are (stanford auth required):

* https://docs.google.com/document/d/1zmjysV88hGwgLBCR-2ZTeCQHc5_RRuHKjW5sm6PYrbg/edit
* https://docs.google.com/document/d/1CuCQaB-yZcrxAzfuBdXecAOP3rPevXNXheTgBRkAeps/edit

**Comment by dcdenu4** [comment]
Let's use #1044 for this work.
