### ISSUE TITLE
PyInstaller conflicts with custom hooks

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#145]
I haven't seen this anywhere yet besides my local dev environment, but doesn't hurt to document it. 

```
> python -m PyInstaller exe/invest.spec
...
File "/home/dmf/projects/invest/env/lib/python3.7/site-packages/PyInstaller/depend/imphook.py", line 289, in __init__
    assert self.hook_module_name not in HOOKS_MODULE_NAMES
AssertionError
```
It seems we have some custom hooks for modules that already have built-in hooks with PyInstaller. More is explained in https://github.com/pyinstaller/pyinstaller/issues/4626. A patch to report which hooks are in conflict is already in PyInstaller develop.

But the fix for packaging invest, for me, was to remove the conflicting hooks from our project. I won't suggeset we actually do that until this issue comes up somewhere else...but when it does we'll know what to do!

Conflicting hooks: `numpy scipy pandas shapely osgeo`

My env:
ubuntu
python 3.7
PyInstaller 3.6

**Comment by phargogh** [comment]
- [ ] We're currently building against 3.5, so can we upgrade to 3.6 and take care of this issue?

**Comment by dcdenu4** [comment]
Pyinstaller 4.1 is release with Python 3.8, 3.9 support. But, when working on the release I did notice duplicate hooks that we included that are now default included with Pyinstaller. Worthwhile to drop our maintained hooks where allowed when testing out the 4.1 version of Pyinstaller.
