### ISSUE TITLE
module 'natcap.invest' has no attribute 'sdr'

### ISSUE THREAD

**Issue by mengmonkia** [natcap/invest#1462]
Hello, I have successfully installed the natcap.invest module in my 3.7.9 environment and I can import the module via import, but I get an error when outputting the results, natcap.invest.sdr.sdr.execute(args), ------------------------- --------------------------------------------------
AttributeError Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_114984\2210574907.py in <module
----> 1 natcap.invest.sdr.sdr.execute(args)

AttributeError: module 'natcap.invest.sdr' has no attribute 'sdr'
I'd like to ask for help with this question, I'm using version 3.10.2 for my invest

**Comment by davemfish** [comment]
@mengmonkia I'm not sure how you did the import; you might want to share the rest of your code. 

This should work though:
```python
import natcap.invest.sdr.sdr

natcap.invest.sdr.sdr.execute(args)
```

**Comment by dcdenu4** [comment]
@mengmonkia thanks for creating this issue and using our python libraries. Just in case you weren't aware, we also have a community forum: https://community.naturalcapitalproject.org/, where you can ask questions and learn from what others are up to. We monitor that daily.

**Comment by mengmonkia** [comment]
thank you!,Sorry, I didn't look closely at the code on the ndr instance and saw the carbon module code for the change.
