### ISSUE TITLE
HRA stressor comparison bug on sample data

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1467]
A user on the forum noted they were getting an error when running HRA with sample data in 3.14.0.

https://community.naturalcapitalproject.org/t/error-in-hra-with-dawnloaded-sample-data/4339

It looks like when comparing stressors one table is lowercasing while the other is not. For the habitat_stressor_info table `validation.get_validated_dataframe` is being used which does return a table with lowercased values. For the criteria table, `utils.read_csv_to_dataframe` is returning a table where values are NOT lowercased.

Note: `validation.get_validated_dataframe` calls `utils.read_csv_to_dataframe`, so this is likely an unique case handling the HRA criteria table.

I can reproduce the issue with the latest `invest:main`

**Comment by dcdenu4** [comment]
Interestingly, all tests pass so we must not be running a regression test on sample data. And looking at the HRA tests, all the unit tests use lowercase values for table creations.

**Comment by davemfish** [comment]
> Interestingly, all tests pass so we must not be running a regression test on sample data. And looking at the HRA tests, all the unit tests use lowercase values for table creations.

see also #1468

**Comment by dcdenu4** [comment]
So, I think that reading the table with `validation.get_validated_dataframe` is the issue here. That function does some additional mutation to the dataframe that helps when validating. But it causes consequences when using in the model directly. In this case, the function lowercases the values of columns which `utils.read_csv_to_dataframe` does not. So let's use the same `utils` function for reading when we're comparing.
