### ISSUE TITLE
RTD builds failing, trying to pip install gdal

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1575]
https://readthedocs.org/projects/invest/builds/24343844/

I don't quite understand what is triggering pip to install gdal 3.9.0 (just released), we should already have gdal installed from conda-forge based on `.readthedocs_environment.yml`. I tried restricting gdal to <3.8.5 in that yml, but pip still wanted to install 3.9.0.

**Comment by phargogh** [comment]
Yeah, any time there is a newer version of a package available on PyPI, pip will (by default anyways) try to install the newer package, even if the already-installed version is satisfactory.

I just checked the `pip install` help, and it looks like if we have control over the `pip install` command, we might be able to use `pip install --upgrade-strategy=only-if-needed` (the default is `--upgrade-strategy=eager`).  Maybe that would help?

**Comment by davemfish** [comment]
Thanks @phargogh , good lead! It looks like we've run into this:
https://github.com/readthedocs/readthedocs.org/issues/9727
