### ISSUE TITLE
"Windows protected your PC" after code signing

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#1591]
We've confirmed from a few folks that downloading the InVEST 3.14.2 workbench have been seeing a smartscreen alert (see image below) despite the binary having been signed, as demonstrated on the popup.  This wasn't always the case - is it possible to avoid this popup the first time the application starts?

![invest-3-14-2-windows-protected-2](https://github.com/natcap/invest/assets/4583897/e197a387-1dd3-4e9a-9db4-7ffc8577fa39)

**Comment by phargogh** [comment]
[This SO answer](https://stackoverflow.com/a/51113854/299084) suggests that because we are using a new certificate, it will take a little time (a few days maybe?) for SmartScreen to trust it.  So we can/should expect this issue to recur whenever we get a new certificate.  The way around this is some kind of special certificate called an “Extended Validation” code signing certificate, which does not have this trust period.

**Comment by dcdenu4** [comment]
Hey @phargogh from our convo earlier this week it sounds like this issue is really dependent on other validators recognizing and trusting our cert and not something we can take action on. Okay to close and / or remove the bug label?

**Comment by phargogh** [comment]
I think we should close this issue, as there's likely nothing to do.

Our options here are either:
1. Wait until our certificate becomes trusted (which is really just a matter of time), or
2. Pay for an Extended Validation certificate, which would be at NatCap's cost.

I'm assuming that we should just go with number 1 since it's at no cost to us as Stanford folks, so then there's nothing to do and this certificate is working as expected.
