### ISSUE TITLE
Open Workspace button is enabled even when there is no workspace

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1598]
If the invest run crashes before creating the workspace, then clicking the "Open Workspace" button will crash the Workbench.

This is a rare edge case, but can be reproduced by an error during python imports, for example a `ModuleNotFoundError` . Or by the case described in #1599

**Comment by abhijeetsri13** [comment]
#include <iostream>
#include <climits>
using namespace std;

int main() {
    

    cout << "==============================================" << endl;
    cout << "\t      Ranges of Character" << endl;
    cout << "==============================================" << endl;
    cout << "signed char    : " << CHAR_MIN << " to " << CHAR_MAX << endl;
    cout << "unsigned char  : 0 to " << UCHAR_MAX << endl;

    for (int i = 0; i <= UCHAR_MAX; i++) {
        cout << "==============================================" << endl;
        char c = 'A';
        cout << "Character : " << c << " ( " << int(c) << " ) " << endl;
        c = char(int(c + 1));
        cout << "Next Character : " << c << " ( " << int(c) << " ) " << endl;
        cout << "==============================================" << endl;
    }
    
    return 0;
}
