### ISSUE TITLE
Urban Flood Risk drops AOI attribute table fields

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1600]
I'm running Urban Flood Risk, SDR and NDR in the same place, providing the same watershed shapefile as the area of interest for all models. The watershed shapefile contains an important field that I want to retain in the model output, but UFR does not retain them, while SDR and NDR do. In particular, I have a unique ws_id assigned to each watershed that gets dropped, and that's very inconvenient for later needing to join up the results with other data, because what's left is the FID field, which GIS software can independently change if a feature is added or deleted. 

So the request is for UFR to keep all of the fields contained in the input AOI vector when creating the aggregated vector result. Thanks!

**Comment by emlys** [comment]
Thanks @newtpatrol - marking it as a bug because we do intend to preserve input fields in the output.

**Comment by emilyanndavis** [comment]
Please ignore the "mention" notification above! That PR is unrelated to this issue; I simply pasted in the wrong URL by mistake. 🤦🏻‍♀️
