### ISSUE TITLE
Habitat Quality does not guard against `MAX_DIST` = 0

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#165]
It's possible for users to set `MAX_DIST` for a threat to `0.0` in the input CSV, but this raises numpy runtime warnings later on, and produces strange values in the final rasters. See example here:
https://community.naturalcapitalproject.org/t/hq-raster-1-ind/1038

It's very possible this is already fixed in the refactor for 3.9, but worth checking.

**Comment by dcdenu4** [comment]
Thanks Dave! That is an interesting use case. I wonder if we should interpret 0 as meaning ignore this threat for calculations... or if we should restrict values to greater than 0.

**Comment by davemfish** [comment]
Interesting indeed! I've never used this model so I don't really know how a user might be thinking about that. It would be interesting to hear back from the user about how the 0 got into their table (intentional or erroneous?). 

But, if the conventional way to ignore a threat would be to remove it's row from the table entirely, then I think it's reasonable to throw an error or validation warning for the 0s. Rather than giving 0 some special meaning.

**Comment by dcdenu4** [comment]
I agree with Dave, giving 0 a special meaning is confusing. So, let's put a range check on `Max Dist` values to be `max_dist > 0`.

**Comment by dcdenu4** [comment]
A fix for this was included in PR #75 ( The refactor of HQ )
