### ISSUE TITLE
UFRM doesn't write its summary vector unless the built_infrastructure vector is provided

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#168]
When running UFRM without the built infrastructure inputs, the output vector (`flood_risk_services.shp`) is not included in the output directory, despite the stats that are summarized in this vector not being a part of the built infrastructure calculations.

> There should be a shapefile output with the two fields that are related to the supply: the retention index and retention vol (m3).

Send Perrine a development build when this is patched.

**Comment by davemfish** [comment]
Nothing new here, but basically a +1 for this issue: https://community.naturalcapitalproject.org/t/urban-flood-mitigation-model-output-shapefile-missing/991
