### ISSUE TITLE
investspec "evapotranspiration" wording needs to be changed

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1693]
The Data Needs section of the User Guide for Urban Cooling and Annual Water Yield currently says this:

> Evapotranspiration ([raster](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/en/input_types.html#raster), units: mm, required): Map of evapotranspiration values.

Just calling it "evapotranspiration" is not precise enough, because there is a difference between _potential_ ET and _reference_ ET and _actual_ ET (all of which users might encounter in an ET data search), and both of these models' equations specify _reference_ ET (then they calculate potential and/or actual ET using Kc provided in the biophysical table). So the Data Needs section should specify "reference evapotranspiration", like it does for Seasonal Water Yield. 

So please update this in investspec - thanks!

**Comment by newtpatrol** [comment]
@davemfish if it's ok for the software team, I will take you up on learning how to edit investspec directly. It's also fine for me to (try to) remember to assign it to "invest" and "bug" if that's preferred, and helps bump it up on the priority queue. Thanks for addressing this so thoroughly.

**Comment by jagoldstein** [comment]
I'm also willing to try to learn about how to edit `investspec`s directly!
