### ISSUE TITLE
Add "integer" to LULC description for UNA

### ISSUE THREAD

**Issue by newtpatrol** [natcap/invest#1695]
Currently, :investspec:`urban_nature_access lulc_raster_path` does not specify that the raster values must be integer, which match the "lucode" field in the attribute table. Please add this information. Thanks!

In general, while I'm sure there's a lot of utility to putting these definitions in :investspec:, it really does make it inconvenient for crowdsourcing UG edits.

**Comment by davemfish** [comment]
I think this is made clear in the description of the LULC Attribute Table, but not in the description of the LULC raster. The UG:

>Land Use/Land Cover ([raster](http://releases.naturalcapitalproject.org/invest-userguide/latest/en/input_types.html#raster), required): A map of LULC codes. All values in this raster must have corresponding entries in the LULC attribute table. For this model in particular, the urban nature types are of importance. Non-nature types are not required to be uniquely identified. All outputs will be produced at the resolution of this raster.

>LULC Attribute Table ([CSV](http://releases.naturalcapitalproject.org/invest-userguide/latest/en/input_types.html#csv), required): A table identifying which LULC codes represent urban nature. All LULC classes in the Land Use Land Cover raster MUST have corresponding values in this table. Each row is a land use land cover class.

>Columns:

>lucode ([integer](http://releases.naturalcapitalproject.org/invest-userguide/latest/en/input_types.html#integer), required): LULC codes from the LULC raster. Each code must be a unique integer.

We could either add to the "about" text in the model spec here:

```python
        'lulc_raster_path': {
            **spec_utils.LULC,
            'projected': True,
            'projection_units': u.meter,
            'about': (
                "A map of LULC codes. "
                "All values in this raster must have corresponding entries "
                "in the LULC attribute table. For this model in particular, "
                "the urban nature types are of importance.  Non-nature types "
                "are not required to be uniquely identified. All outputs "
                "will be produced at the resolution of this raster."
            ),
        },
```

And/or we could publish the `bands` information from `spec_utils.LULC`:
```python
LULC = {
    "type": "raster",
    "bands": {1: {"type": "integer"}},
    "about": gettext(
        "Map of land use/land cover codes. Each land use/land cover type "
        "must be assigned a unique integer code."),
    "name": gettext("land use/land cover")
}
````
