### ISSUE TITLE
MacOS Binary Build failure - gsutil

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#1704]
Seen in GHA: https://github.com/natcap/invest/actions/runs/12257234368/job/34194266735

```
Error: gsutil requires Python version 2.7 or 3.5-3.11, but a different version is installed.
You are currently running Python 3.12
Follow the steps below to resolve this issue:
	1. Switch to Python 3.5-3.11 using your Python version manager or install an appropriate version.
	2. If you are unsure how to manage Python versions, visit 
```

**Comment by emilyanndavis** [comment]
According to the [`gsutil` changelog](https://github.com/GoogleCloudPlatform/gsutil/commit/209426930211e762ed27ba333bad21f03fea6e7a), it looks like this should be resolved in `gsutil 5.32`, which was released a few days ago.

Will our build process automatically pull the latest version of `gsutil`, or do we need to explicitly update the version number somewhere?

**Comment by emilyanndavis** [comment]
Correction: this is resolved in `gsutil 5.33`, which was released just yesterday. (The update in 5.32 added support for Python <= 3.12; 5.33 also supports any 3.12.x versions.)

**Comment by davemfish** [comment]
Great, thanks @emilyanndavis ! I think we should expect to get the latest `gsutil` without making any changes on our end. I'll check back on the latest Actions running on `main` to see what happens.

**Comment by davemfish** [comment]
Looks like this resolved itself
