### ISSUE TITLE
UFRM: output file names don't match users guide

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#173]
A user on the forums pointed out that the output names don't reflect those in the users guide.

community.naturalcapitalproject.org/t/urban-flood-risk-mitigation-output/1070

InVEST outputs: `Runoff_retention`, `Runoff_retention_m3`
Users Guide: `R.tif`, `R_m3.tif`

It also seems like `Interpreting Results` is misleading, as I'm sure it is in most model sections, in that it doesn't provide any useful context for the outputs besides a dry factual description. Not much in the way of "interpretation". Perhaps that should be an issue on the users guide repo, work to update those across models where we have capacity ("we" meaning science model maintainers)

**Comment by phargogh** [comment]
FYI I've addressed the filename inconsistencies in #219

**Comment by phargogh** [comment]
Now that natcap/invest.users-guide#7 has the 'interpreting results' part of the above issue and the filename inconsistencies were addressed in #219, I'll close this issue.  But @dcdenu4 please feel free to reopen if there's something here that hasn't yet been addressed!
