### ISSUE TITLE
AUTO Merge instructions misleading

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#179]
When recently fixing a conflict in a Master -> Release auto PR I was following the instructions:

```
$ git checkout master
$ git pull upstream master  # Include the latest changes on the upstream master
$ git checkout -b pr-resolution
$ git merge release/3.9
```
On doing this I ended up in my `pr-resolution` branch with no merge conflicts. I then looked back at these instructions awaking from autopilot and thought, is that really what I want to do? 

Should it not be:
```
$ git checkout master
$ git pull upstream master      # Include the latest changes on the upstream master
$ git checkout release/X.Y
$ git pull upstream release/X.Y   # Include the latest changes on the upstream release
$ git checkout -b pr-resolution   # Create resolution branch from the release
$ git merge master                  # Merge in master to recreate the conflicts for fixing
```

Thoughts? Am I just confusing myself?

**Comment by phargogh** [comment]
Yep, your suggestions make a ton of sense @dcdenu4 !  We should definitely update the PR body text to include these.
