### ISSUE TITLE
Refactor tests to use consistent numpy testing

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#188]
Numpy recommends that `assert_array_almost_equal` and `assert_almost_equal` be replaced with `assert_allclose`. The former two testing assertions are used throughout InVEST testing modules and they have a different default `decimal` comparison metric. `assert_allclose` uses a `rtol` and `atol` metric instead. 

Current tests that would need updating:
- [x] `test_carbon`
- [x] `test_coastal_blue_carbon`
- [x] `test_coastal_vulnerability`
- [x] `test_globio`
- [x] `test_habitat_quality`
- [x] `test_ndr`
- [x] `test_recreation`
- [x] `test_routedem`
- [x] `test_scenic_quality`
- [x] `test_sdr`
- [x] `test_seasonal_water_yield`
- [x] `test_wave_energy`
- [x] `test_wind_energy`

**Comment by dcdenu4** [comment]
For a few tests I've been using `rtol=0` and `atol=1e-06` for `assert_allclose`.

**Comment by emlys** [comment]
It looks like the `decimal` value is set to 6 in some places and 2 in others. From the numpy docs, `assert_array_almost_equal` and `assert_almost_equal` use a tolerance value of `1.5 * 10**(-decimal)` while `assert_allclose` uses `atol + rtol * abs(desired)`. 

So setting `rtol=0` and `atol=1.5e-2` would be equivalent to `decimal=2`.

Trying it first with @dcdenu4 's values for places where `decimal=6` and `atol=1.5e-2` where `decimal=2`.
