### ISSUE TITLE
InVEST Pest Control Model 

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#19]
Implement InVEST Pest control model.

Design doc: https://docs.google.com/document/d/1iQagCqzdaMOO8whCL9-VbZFYlrq5ky1qf1xJRrSXeks/edit?usp=sharing

My algorithms are not reproducing the same data as the original model. On hold until we can figure out what the issue might be.

Originally reported by @richpsharp at https://bitbucket.org/natcap/invest/issues/3630/invest-pest-control-model

**Comment by phargogh** [comment]
@richpsharp I think you were working on this at some point.  Do you remember what the status was?

**Comment by richpsharp** [comment]
Let me take care of it right now.

**Comment by phargogh** [comment]
@richpsharp , I see that you just added the `wontfix` label, but it looks like the issue was reopened.  I'll mark the issue as closed, since I think that's what you meant to have happen!  Feel free to reopen if I'm wrong.
