### ISSUE TITLE
InVEST Requires Windows Admin Privileges 

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#21]
See if there is a way to get around having to be an admin to install InVEST

not sure I'll get to this. I did do some research and it seems possible windows bumps admin privileges when finding words "setup", "install", etc..

Originally reported by @dcdenu4 at https://bitbucket.org/natcap/invest/issues/3498/invest-requires-windows-admin-privileges

**Comment by dcdenu4** [comment]
It looks like in `invest_installer.nsi` we have `RequestExecutionLevel admin`. What happens if we set that to `user`?
