### ISSUE TITLE
Proposal: Move "Save as Python" from UI to datastack or CLI modules

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#237]
There's a method `save_to_python` on `natcap.invest.ui.model.InVESTModel`. That method is useful, almost as-is, in the `invest-workbench`, except that the workbench avoids depending on anything from `natcap.invest.ui` because it's likely we'll eventually be able to deprecate the whole `ui` module. 

So here's a proposal to move the core functionality of `save_to_python` -- all the string formatting -- into `natcap.invest.datastack` or `natcap.invest.cli`. Then the current UI and the new workbench can both call on the same code for this feature.

An alternative proposal is to refactor this function and it's tests into javascript and include it directly in the workbench.

**Comment by phargogh** [comment]
We talked about this a bit this morning and agreed that this should be moved away from the GUI and also adapted a little:

- [ ] The `logging` boilerplate should be added (#71 )
- [ ] It would also be helpful to optionally provide the `args` dict boilerplate without populated args dict values.
- [ ] Have this script available on the CLI
