### ISSUE TITLE
Mac OS interprets IMG files as disc images

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#265]
A user reported on the forums that `.img` raster input files might not be recognized as such. This might be worth testing on someones Mac.

>The main issue seemed to be that I use a Mac iOS and the .img files are recognized within the system as a disk image file, which I think may have been altering formatting

https://community.naturalcapitalproject.org/t/urban-flood-risk-mitigation-model-errors-1-and-4/1206/9

- [ ] Can we reproduce the above issue?

**Comment by phargogh** [comment]
Hey @dcdenu4 do we happen to have the user's `.img` files that couldn't be used?

**Comment by dcdenu4** [comment]
@davemfish might, but I do not. Yep, GDAL shouldn't mind reading `.img` files. I'm honestly not sure what the user was getting at, but I wanted to log it here in case it turned into something.

**Comment by davemfish** [comment]
@dcdenu4 @phargogh I don't have the data either, and I'm also skeptical that this is a real problem as there were other variables at play also. Earlier in the user's posts they mention converting to tif and getting the same results.

**Comment by dcdenu4** [comment]
Sounds good Dave. I don't think it's worth the time to look into then.

**Comment by phargogh** [comment]
Yep, I agree.  And as a side note, it turns out that Apple isn't wrong about interpreting files with the `.img` extension as disk images since it turns out that [Apple's own disk image format sometimes has the same extension](https://en.wikipedia.org/wiki/Apple_Disk_Image).
