### ISSUE TITLE
Add default reset to UI settings menu

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#266]
This might ultimately better fall under the workbench at this point, but when looking at the InVEST UIs `Settings` menu, I noticed that the tool-tip mentions default values. However, there is no way to reset settings to default and the values that are selected for me on a new install of InVEST are not the defaults.

I'd propose adding a `reset defaults` option in that menu.

**Comment by phargogh** [comment]
For the Qt UI (if we implement this in the Qt UI), we should be able to use the refresh context menu option on InVEST text inputs as a starting place for this.
