### ISSUE TITLE
InVEST UI settings differ from tool-tip text

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#267]
When looking into a user's post I noticed that the InVEST UI's settings menu had different default values then what is mentioned in the tool-tip text. For instance the cache directory for me on a fresh install of InVEST 3.8.7 is: `AppData/Local/python/cache` where as the default says `AppData/Local/invest/cache`. I do not think I have ever changed this setting.

**Comment by phargogh** [comment]
This sounds unexpected!  I'm not experiencing this on my windows laptop myself, but I am curious.  So the value that is being used for your cache directory is `AppData/Local/python/cache`?

**Comment by dcdenu4** [comment]
@phargogh indeed it is. Even on a fresh install. Here's a shot of the Scenario Generator, a model I don't think I've opened before.


![image](https://user-images.githubusercontent.com/2659980/90436657-167e0180-e09f-11ea-88eb-e362aefd7891.png)

**Comment by phargogh** [comment]
Well that does sound strange.  Out of curiosity, what happens when you delete that folder, `AppData/Local/python/cache`?  I'm wondering if it will default back to what it's supposed to default to.

**Comment by dcdenu4** [comment]
Interestingly, `AppData/Local/python` doesn't exist on my system! Neither does `AppData/Local/invest`

**Comment by phargogh** [comment]
Well _that_ is interesting!  The application is supposed to create those directories at application startup (or maybe when the settings are saved).  What happens when you change one of the settings and click `save`?

**Comment by dcdenu4** [comment]
Great question. I did just that and I can't tell where files are being saved. Do you know what any of the saved files to `cache_dir` should be named? I can try doing a search on my drive.

**Comment by phargogh** [comment]
Looks like thse files are _actually_ being stored in `AppData\Roaming\Natural Capital Project`, so maybe the path there is wrong somehow??

**Comment by emlys** [comment]
Giving this the icebox label because it'll likely become irrelevant with the workbench UI. Unless this causes problems for someone, it's pretty low priority.
