### ISSUE TITLE
Support GDAL 3+

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#27]
InVEST tests currently fail when using GDAL 3+. This is mostly related to how GDAL 3 has changed how it handles spatial references, and particularly coordinate transformations. This issue should be blocked on the Pygeoprocessing version of this issue. The main consideration is whether we should support both GDAL 2 and GDAL 3 or move on to GDAL 3 and drop support for GDAL 2. The main thing here is that there are slight variations in spatial coordinates pertaining to bounding boxes and extents. This would mean that in certain cases we would have to carry around expected test data for both GDAL 2 runs and GDAL 3 runs. That is doable, but perhaps not ideal?

- [x] Pygeoprocessing supports GDAL 3+
- [x] Update history with changes

**Comment by phargogh** [comment]
Also, when we have a functioning binary build based on GDAL3, let's be sure to have Jade and/or Stacie test the new build on the MAR datasets that were having LZW errors! (related to #29 )

**Comment by phargogh** [comment]
Just heard from Jade that the latest release (InVEST 3.8.1, which uses GDAL 2.4.4), resolves the LZW issue which confirms our hypothesis about the compression issue being related to OSGeo/gdal#1439.  The upgrade to GDAL 3 should also contain this fix.

**Comment by dcdenu4** [comment]
This is dependent on Pygeoprocessing milestone 2.0

**Comment by dcdenu4** [comment]
closed from #150
