### ISSUE TITLE
Installation failing because requirements-all.yml doesn't list conda-forge

### ISSUE THREAD

**Issue by jsta** [natcap/invest#278]
I'm attempting installation and running the following command:

`make ENV=invest env`

but I'm getting the following error:

```
conda env update -p invest --file requirements-all.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - taskgraph[version='>=0.9.1']
```

I solved the error by manually adding conda-forge as a channel to the `yml` file and re-running:

`conda env update -p invest --file requirements-all.yml`

**Comment by phargogh** [comment]
Thanks for letting us know about this!  The script does indeed check conda-forge for the presence of packages, so it would follow that the environment file it produces should include the conda-forge channel.  I'll get a patch in for this.

**Comment by dcdenu4** [comment]
Hey @phargogh , just confirming that this is good to go now.

**Comment by jsta** [comment]
Works for me.

**Comment by phargogh** [comment]
Thanks for letting us know, @jsta !
