### ISSUE TITLE
UCM: some optional parameters are not handled well by validation / UI

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#28]
Here's an error report: https://community.naturalcapitalproject.org/t/urban-cooling-model-error/824/2

The model expects the args in question to either have values that cast to float, or for the key to be missing from the args dict altogether. Not handled is the case where `args['cc_weight_shade'] = ''`. Ditto for the other two `cc_weight` args.

**Comment by phargogh** [comment]
Well that is surprising!

**Comment by phargogh** [comment]
Still need to test out a windows build of this once the actions run (https://github.com/phargogh/invest/actions/runs/177739135) has finished.
