### ISSUE TITLE
Expose raster/driver creation options in InVEST Settings

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#29]
Occasionally (this has come up twice now to my knowledge), successive reads/writes to an LZW-compressed GeoTiff, such as within a batch script, will result in errors like the one below being produced.

```python
ERROR 1: LZWDecode:Corrupted LZW table at scanline 1280
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: C:\Temp\SWY_sensitivity_test2\L_sum_avail_CMCC_TFA_500.tif, band 1: IReadBlock failed at X offset 5, Y offset 5: TIFFReadEncodedTile() failed.
Traceback (most recent call last):
  File "src\natcap\invest\seasonal_water_yield\seasonal_water_yield_core.pyx", line 309, in natcap.invest.seasonal_water_yield.seasonal_water_yield_core._ManagedRaster._load_block
AttributeError: 'NoneType' object has no attribute 'astype'
```

The only known workaround for this at the moment is to write uncompressed GeoTiffs, a change that requires passing the appropriate parameter to each pygeoprocessing function call.

A solution for this might involve touching many components of InVEST and so should probably be designed.

**Comment by phargogh** [comment]
This issue might be related to https://github.com/OSGeo/gdal/issues/1439, which appears to have been fixed in GDAL 2.4.2.  InVEST 3.8.0 ships with GDAL 2.4.1, which is the latest version of GDAL 2.x that Gohlke offers.

So we may need to wait to test this again once we've migrated InVEST and pygeoprocessing to GDAL3.

**Comment by richpsharp** [comment]
Seeing as how this is probably a GDAL bug, I'd tend to lean toward a `wontfix` on this, or a more useful issue of "expose `raster_driver_creation_tuple` in InVEST settings" - something like that. That'd fix every future issue fudging around with whatever we were trying to patch here.

**Comment by phargogh** [comment]
@richpsharp This issue was really intended to reflect the latter -- that we should expose GDAL creation options in the InVEST User Interface and then use them throughout InVEST -- so I've updated the issue title to reflect this.

**Comment by phargogh** [comment]
I'm going to wontfix this, as the value that it would provide would not outweigh the cost of implementation and the cost of maintenance.

In practice, so many of our internal functions _depend_ on tiled geotiffs, that we'd only be able to practically permit file formats that provided the same sort of functionality.  Far better to ship an updated version of GDAL than to open ourselves up to additional maintenance in the future and a complex refactor to accommodate multiple output filetypes and creation options.
