### ISSUE TITLE
Urban InVEST recreation prototype model

### ISSUE THREAD

**Issue by richpsharp** [natcap/invest#290]
This issue is a catch-all for the urban recreation model Attached is the design document.
[rec design doc20190328.docx](https://github.com/natcap/invest/files/5154185/rec.design.doc20190328.docx)

**Comment by dcdenu4** [comment]
@richpsharp , is this still in progress or active development?

**Comment by richpsharp** [comment]
Yes and yes @dcdenu4. But now we have to wait  for the PSC to tell us it's okay to continue to work on.

**Comment by richpsharp** [comment]
I think the PSC still hasn't decided on this, plus I'll never implement it so I'm removing myself as the assignee.

**Comment by phargogh** [comment]
Yep, the PEP for this hasn't gone through the PSC yet, so it's on hold (and I tagged it as such).  Looks like the work-so-far on this is in `https://github.com/richpsharp/invest/tree/feature/urban-rec-290`.

**Comment by emlys** [comment]
This is the Urban Nature Access model (#722)
