### ISSUE TITLE
Cython ModuleNotFoundError on 3.8.8 release UI test

### ISSUE THREAD

**Issue by emlys** [natcap/invest#299]
https://github.com/natcap/invest/runs/1073578973?check_suite_focus=true

This error happened in 4 consecutive runs of the UI tests. It's only happening on the 3.7, x64 version. 
We are going ahead with the release but should look into this at some point.

**Comment by phargogh** [comment]
I was looking into the release logs a little (just to check that the UI test failures were for a known reason), and I noticed another error that looks like this might have been something unrelated to Cython in the same logs:

```text
 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pywin32>=223 from https://files.pythonhosted.org/packages/96/51/d46eb277182e0989a81cdc0933e97924b68b12519dfe62ae0ea5dec198dd/pywin32-228-cp37-cp37m-win_amd64.whl#sha256=00eaf43dbd05ba6a9b0080c77e161e0b7a601f9a3f660727a952e40140537de7 (from pypiwin32->-r requirements-dev.txt (line 17)):
        Expected sha256 00eaf43dbd05ba6a9b0080c77e161e0b7a601f9a3f660727a952e40140537de7
             Got        3712daaadf5b4b2b1c6787430b17181c141dc5ce5aa35bbe5e1641d6a7d3c9be
```

Which, if true, would be _super_ interesting.

**Comment by emlys** [comment]
Super weird! It looks like there's currently no way to clear the cache and make it re-download the packages: https://github.com/actions/cache/issues/2 aside from not running the tests for 7 days, or editing the YML to use different keys for the cache :(

**Comment by dcdenu4** [comment]
I don't think we're still seeing this issue correct? This feels like it'd be important for the 3.9 release, so wanted to check in on it.

**Comment by phargogh** [comment]
Yep, I think this issue ended up resolving itself.  I personally haven't seen this issue since early Sept.  Have you seen this recently @emlys ?

**Comment by emlys** [comment]
I have not seen it recently! Not sure what was up with that. Maybe some weird thing with github actions that we have no control over anyway. I agree it's probably fine to close the issue

**Comment by dcdenu4** [comment]
Cool, closing for now.
