### ISSUE TITLE
Using makensis github action instead of script

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#303]
When working on the build process for InVEST recently I was diving into all the pieces we have set up to automate builds and installers. I noticed the `ci/windows-ci-binary-install.ps1` script we maintain and wondered if it could be replaced with a GitHub actions routine:

https://github.com/marketplace/actions/makensis

The script is downloading some other tools as well, but perhaps a GitHub Actions hosted Windows environment already handles some of these? 

Moving in this direction would obviously make us extremely dependent on GitHub Actions.

**Comment by phargogh** [comment]
Interesting!  That would make a couple things a little simpler (like downloading and installing the `makensis` binaries), and it _does_ look like it supports having us define a directory of plugins, which we would need to use.

You're very right to note the implicit commitment to the platform that we would be taking on if we were to use this action.  Do you see a compelling benefit to adopting this action that would outweigh the time required to refactor?  Is there something that this action would do for us that our existing setup doesn't?  And also, are there things that our current setup supports that this actions workflow does not?

**Comment by davemfish** [comment]
I'm not sure which I like least, debugging Actions yml or powershell scripts :joy: 

I'd vote for devoting the efforts to building out the workbench installation process (sample data distribution, software updates, etc) and leaving this as-is.

**Comment by phargogh** [comment]
Let's wontfix this.

Several things have changed recently about this:

* We'll be moving large parts of our build process soon to the workbench (pending repo organization questions), probably including the NSIS stuff
* GitHub Actions Runners now ship the latest NSIS version and we no longer do our own setup for it
