### ISSUE TITLE
SDR UI documentation link broken

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#319]
Stacie reports: 
> ... if I launch SDR and click on the Documentation link, I get the message "Local documentation link could not be found: sdr.html" ... The local doc link works properly for other models I've tried (CV, Urban Cooling, Carbon). sdr.html is in the documentation installation folder, so it's something about its reference that isn't working. Just FYI. InVEST 3.8.8.

**Comment by emlys** [comment]
Just tried this and the same problem is happening for me with all the models, even the ones that are working for Stacie.

**Comment by phargogh** [comment]
Sounds like a fairly quick fix, and important to finish for the 3.9 release.

**Comment by phargogh** [comment]
This issue has also come up a couple times, and it would be great if we had a way to test this as part of our regular automated tests.

**Comment by phargogh** [comment]
Also, can we confirm the state of this on both mac and windows?

**Comment by dcdenu4** [comment]
Confirmed on windows for SDR:
![image](https://user-images.githubusercontent.com/2659980/94054853-28dc1100-fdaa-11ea-9cf1-512d0ec77083.png)

**Comment by dcdenu4** [comment]
For `invest/ui/sdr.py` the `localdoc` path is set to `../documentation/sdr.html`. In my downloaded invest directory I have `documentation/userguide/sdr.html`

**Comment by dcdenu4** [comment]
It looks like `_check_local_docs` in `ui/model.py` is handling the setting of the docs path. It seems to expect `self.localdoc` to be `mymodel.html`. I can confirm that on Windows UCM model local doc link works as expected.

**Comment by emlys** [comment]
On mac, in my downloaded invest directory I have `documentation/sdr.html`, no `userguide` directory

**Comment by phargogh** [comment]
The mac binaries will probably need a different solution than windows binaries. Mac's [app sandboxing feature](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html) (which is, in general, a very good idea) in recent OS versions means that all `.app` applications will be executed within some temporary folder on the filesystem and have limited, if any, access to system resources. This means that if `InVEST.app` and `documentation/` are in the same directory, `InVEST.app` won't know where it originally lived and we won't be able to use a relative path to access the documentation.

**Comment by dcdenu4** [comment]
@emlys , @phargogh I was thinking about taking this on but I don't have a way to work with MacOS builds... Would one of you like to work on this for the 3.9 release? I'm a little naïve when it comes to MacOS, is it easy to set up a MacOS VM that I could test / develop with?

**Comment by phargogh** [comment]
Sure, I'd be happy to work through this on the mac side, once I've worked through these latest CBC revisions!

I'm also waiting to hear back from a mac VM cloud provider to allow us to fire up a mac VM when needed.  We've had plenty of cases where access to disposable mac VMs would have been extremely useful (more useful than a stateful machine sitting in the office, I think), so I'll get back to you on that when I hear back.

**Comment by dcdenu4** [comment]
This from Apple about sandboxing and paths:
>For example, if your app depends on hard-coded paths to locations in the user’s home directory, consider the advantages of using Cocoa and Core Foundation path-finding APIs, which use the sandbox container instead.

https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/DesigningYourSandbox/DesigningYourSandbox.html#//apple_ref/doc/uid/TP40011183-CH4-SW1

**Comment by dcdenu4** [comment]
I have a branch going here for Windows fixes: https://github.com/dcdenu4/invest/tree/bugfix/userguide-documentation-link

Much easier than the MacOS side of this issue ;) . Though I am brushing up on mac apps!

**Comment by emlys** [comment]
> This from Apple about sandboxing and paths:

This might tie in to sandboxing issues related to #322

**Comment by phargogh** [comment]
Following back up on my comment above:

> I'm also waiting to hear back from a mac VM cloud provider to allow us to fire up a mac VM when needed. We've had plenty of cases where access to disposable mac VMs would have been extremely useful (more useful than a stateful machine sitting in the office, I think), so I'll get back to you on that when I hear back.

I haven't done an exhaustive search, but the two mac cloud providers that I've tried have workable, if somewhat pricey, options for us.  The most common arrangement for cloud-based mac hosting is to rent a dedicated machine that lives in a datacenter somewhere for a monthly rate.  One provider did offer by-the-hour billing, and I haven't found anyone that offers the sort of granularity in billing that we might get from GCP on a linux VM.  In any case, if we need to rent a mac in the cloud, we have options!  None of them are the disposable-VM sort of arrangement I was hoping for, but these might still be helpful for testing built applications.

**Comment by dcdenu4** [comment]
Local docs seem good on Windows now. Stacie did have an issue where she said SDR local docs failed for her, but Dave and I could not reproduce this. Going to bump this and we can open a new issue if we're still seeing it after the release.

**Comment by dcdenu4** [comment]
I haven't heard anything more about the SDR doc link from Stacie or the forums. Since it works for us, I'll close this.
