### ISSUE TITLE
Hydropower rsuppy not calculated if demand is 0

### ISSUE THREAD

**Issue by emlys** [natcap/invest#332]
In `hydropower_water_yield.compute_rsupply_volume`, the `rsupply` field is only set `if wyield_mn and consump_mn`. If either of these are 0, the condition doesn't pass. Seems like 0 should be a valid value, though. This should probably be 
`if wyield_mn is not None and consump_mn is not None`.

Came up in this issue: https://community.naturalcapitalproject.org/t/error-hydropower-evaluation-annual-water-yield/1385/8

**Comment by dcdenu4** [comment]
Fixed in PR #340
