### ISSUE TITLE
Proposal: Allow warnings in InVEST, but elevate warnings to errors in tests

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#334]
In a [recent forums thread](https://community.naturalcapitalproject.org/t/seasonal-water-yield-error-warn-method/1405) a user reported an issue with the model where the model is elevating all `warnings` to Exceptions, and a `DeprecationWarning` related to a `LOGGER.warn` call is causing the model to crash.

Historically, we've used [warnings such as through `numpy.seterr`](https://github.com/natcap/invest/wiki/spec_invest#handling-warnings-in-numpy-operations) as a way to find numerical errors and other errors during model development, and, admittedly, raising `warnings` as Exceptions can be helpful in that context.

But it's now also leading to a case where a user is being prevented from running the model.  Obviously we should fix this deprecation issue, but we shouldn't be preventing the user from running the model in a reasonable way.  Also, explicitly raising warnings to Exceptions in a binary distribution also opens us up to issues where warnings that are completely outside of our control prevent the model from executing.

# Use Cases

## End-user of our binaries

When running InVEST through our binaries, it is reasonable to expected to be able to run the model without crashing if their inputs are correct.  A `DeprecationWarning` being treated as an Exception (despite the method still working fine) may result in extra work for us on the forums that could have been avoided.

## Developing InVEST

When we're developing InVEST, any warnings raised during the execution of our models (such as `DeprecationWarnings` from calls we make to deprecated python functions, or `numpy` numerical warnings) should be raised to Exceptions and dealt with through our normal development processes.

# Proposal

I propose that we change our development workflow and standard way of handling warnings to make it easier for us to find and fix them when in development, and make `warnings` less fatal for users of our binaries by making the following changes:

1. We remove all instances of `warnings` elevation across InVEST
2. We agree that we won't generally include `warnings` elevation in future model development that makes it out to the user (except where it makes sense to do so)
3. We add a warnings filter to our testing suite so that warnings emitted by InVEST within our tests _are_ elevated to Exceptions, which allows us a chance to fix them proactively. (See `pytest.ini` example below for a possible approach)

<details>
<summary>Example pytest.ini configuration</summary>

This text, contained within `pytest.ini` in the InVEST project root, would allow any warnings raised throughout InVEST to be reported as Exceptions:

```python
[pytest]

# Convert warnings emitted anywhere in InVEST to exceptions.
filterwarnings =
        error:::natcap.invest[.*]
```

Example output from pytest:

```shell
$ python -m pytest tests\test_utils.py
========================================================================================= test session starts ========================================================================================== platform win32 -- Python 3.7.8, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\james\workspace\phargogh\invest, configfile: pytest.ini
plugins: cov-2.10.1
collected 60 items

tests\test_utils.py ................F...........................................                                                                                                                  [100%]

=============================================================================================== FAILURES =============================================================================================== _____________________________________________________________________________ LogToFileTests.test_log_to_file_all_threads ______________________________________________________________________________

self = <test_utils.LogToFileTests testMethod=test_log_to_file_all_threads>

    def test_log_to_file_all_threads(self):
        """Utils: Verify that we can capture messages from all threads."""
        from natcap.invest.utils import log_to_file

        logfile = os.path.join(self.workspace, 'logfile.txt')

        def _log_from_other_thread():
            """Log from other thead."""
            thread_logger = logging.getLogger()
            thread_logger.info('this is from a thread')

        local_logger = logging.getLogger()

        # create the file before we log to it, so we know a warning should
        # be logged.
        with open(logfile, 'w') as new_file:
            new_file.write(' ')

>       with log_to_file(logfile) as handler:

tests\test_utils.py:290:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env37-conda-x64\lib\contextlib.py:112: in __enter__
    return next(self.gen)
env37-conda-x64\lib\site-packages\natcap.invest-3.8.7.post807+gf118a2b2.d20201009-py3.7-win-amd64.egg\natcap\invest\utils.py:194: in log_to_file
    LOGGER.warn('Logfile %s exists and will be overwritten', logfile)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Logger natcap.invest.utils (WARNING)>, msg = 'Logfile %s exists and will be overwritten', args = ('C:\\Users\\james\\AppData\\Local\\Temp\\tmpm0j539dk\\logfile.txt',), kwargs = {}

    def warn(self, msg, *args, **kwargs):
        warnings.warn("The 'warn' method is deprecated, "
>           "use 'warning' instead", DeprecationWarning, 2)
E       DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

env37-conda-x64\lib\logging\__init__.py:1394: DeprecationWarning
=========================================================================================== warnings summary =========================================================================================== env37-conda-x64\lib\site-packages\osgeo\gdal.py:22
  C:\Users\james\workspace\phargogh\invest\env37-conda-x64\lib\site-packages\osgeo\gdal.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

tests/test_utils.py::SuffixUtilsTests::test_suffix_string
  C:\Users\james\workspace\phargogh\invest\env37-conda-x64\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================= short test summary info ======================================================================================== FAILED tests/test_utils.py::LogToFileTests::test_log_to_file_all_threads - DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
=============================================================================== 1 failed, 59 passed, 2 warnings in 5.38s ===============================================================================

```

Notice how the `warning` raised by a deprecated usage of `LOGGER.warn` in `natcap.invest.utils` is causing an exception to be raised, but two other warnings that are either outside of our control (GDAL's deprecated usage of `importlib`) or having to do with my development environment (the numpy ufunc size change) are still raised as warnings.

The above configuration also captures `numpy` warnings (such as divide-by-zero), by the by.

</details>

Because this is a change in how we approach warnings and errors, I'd like to check in with everyone about this to see if there are any questions, comments or objections.  @richpsharp @dcdenu4 @davemfish @emlys ?

**Comment by davemfish** [comment]
This proposal makes a lot of sense to me. I didn't realize there were places where we elevated warnings to exceptions. It definitely makes sense to sometimes/always do that in tests, but not in releases. 

There's a few cases that come to mind that we'll need to deal with:
* gdal/geos warnings about bad geometries - there are some tests (coastal vulnerability) that deliberately run tests on these geometries
* Also in CV - some `LOGGER.warning` messages that summarize questionable results for users (e.g. "9 points will have missing values..."). I'm not sure if these messages come up in tests - arguably they should be under test. There's also a good case to be made for moving them off the `WARNING` level. The idea was to make them more visible in a sea of `INFO` messages.

**Comment by phargogh** [comment]
Thanks for your feedback, @davemfish !  The intent with `warnings` elevation has to do with warnings emitted from the `warnings` module.  So examples of that would include numerical warnings from numpy (as in division by zero or numerical overflow), deprecation warnings (like what was [reported recently on the forums](https://community.naturalcapitalproject.org/t/seasonal-water-yield-error-warn-method/1405/4) where `LOGGER.warn` was raising `DeprecationWarning`, fixed across InVEST in #336 ).  Warnings written to logging would be unaffected.

> * gdal/geos warnings about bad geometries - there are some tests (coastal vulnerability) that deliberately run tests on these geometries
> * Also in CV - some LOGGER.warning messages that summarize questionable results for users (e.g. "9 points will have missing values..."). I'm not sure if these messages come up in tests - arguably they should be under test. There's also a good case to be made for moving them off the WARNING level. The idea was to make them more visible in a sea of INFO messages.

These are both really interesting use cases, and it makes me wonder if we should be handling these differently.  InVEST currently installs an error handler to ensure that GDAL warnings and errors are written to logging, but perhaps those should be emitted as `warnings` as well?  Do you think that these should be elevated to exceptions under test?

**Comment by davemfish** [comment]
Ohhh I see. I was completely ignorant of the `warnings` module. I thought this was all about using the `WARNING` level of logging.

>but perhaps those should be emitted as warnings as well?

as in, from a `LOGGER.warning` call? I think they already are. As in from the `warnings` module? No I don't think so, see below (but I'm still 98% ignorant about this module)

>Do you think that these should be elevated to exceptions under test? 

No, I was trying to say it would be problematic if they were elevated because they are expected outcomes of passing tests.

**Comment by phargogh** [comment]
Ah, gotcha.  Yes, the two modules are handled in python very differently!  Although there are some areas of overlap between the two, there seems to be more consistent use of `warnings` for reporting of low-level issues to the user than logging, and I suspect this is because we can depend on a `warnings`-based warning being reported to the user via stderr.  `logging` will be sent wherever the application decides, and might not be presented to the user at all.

I agree that because of the expected outcomes of tests, it would be problematic to convert GDAL errors/warnings to exceptions as part of our tests.  I suppose it could be possible to silence those warnings for the tests that need them, but that also sounds like a nicely-contained enhancement to our test suite if it does become necessary.

**Comment by phargogh** [comment]
We discussed this in the bug scrub 2023-04-07:

* Try to see if we can exclude `DeprecationWarnings` from the set of warnings raised to exceptions during GHA runs
* Continue the discussion in a PR

**Comment by emlys** [comment]
A few notes so far -
- It seems that SWY is the only place where we're elevating warnings to errors in production code
- Elevating warnings to errors in tests is simple, but interacts weirdly with other warning handling
- We also redirect warnings to logging, which further complicates things (`utils.prepare_workspace`, `logging.captureWarnings(True)`)
