### ISSUE TITLE
Github actions warnings about add-path

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#346]
In looking through a few recent GH actions runs associated with a PR ([example actions run](https://github.com/natcap/invest/actions/runs/298225931)), there are a pile of annotations/warnings about `add-path` being deprecated and replaced by environment files.  We should look into this and update accordingly.

<img width="1219" alt="Screenshot 2020-10-16 114952" src="https://user-images.githubusercontent.com/4583897/96297492-c68bc000-0fa5-11eb-92b6-39a67cfd1f9c.png">

**Comment by dcdenu4** [comment]
`setup-miniconda` is (has) addressed this in their action. Should be coming in a future release. https://github.com/conda-incubator/setup-miniconda/issues/84.

**Comment by dcdenu4** [comment]
It looks like `setup-miniconda` has released a `v2` release that addresses this issue.

**Comment by emlys** [comment]
Closed in #382.
