### ISSUE TITLE
Global polygon layer has two invalid geometries

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#351]
When looking into an [issue on the forums](https://community.naturalcapitalproject.org/t/no-shapely-geometry-can-be-created-from-null-value-invest-cv/1421/4), it became clear that we have a couple of invalid geometries in our global landmass vector that we should correct.  See the testing script below and the stdout.

```python
import shapely.wkb
from osgeo import gdal

LANDMASS = r'C:/InVEST_3.8.9_x86/sample_data/Base_Data/global_polygon.shp'

if __name__ == '__main__':
    vector = gdal.OpenEx(LANDMASS, gdal.OF_VECTOR)
    layer = vector.GetLayer()
    for feature in layer:
        geom = feature.GetGeometryRef()
        if geom.IsEmpty():
            print(f'Feature {feature.GetFID()} is OGR empty')

        try:
            shapely_geom = shapely.wkb.loads(geom.ExportToWkb())
        except:
            print(f'Could not load feature {feature.GetFID()}')

        if shapely_geom.is_empty:
            print(f'Feature {feature.GetFID()} is shapely empty')
```

Stdout:

```
IllegalArgumentException: Points of LinearRing do not form a closed linestring
Could not load feature 95
IllegalArgumentException: Points of LinearRing do not form a closed linestring
Could not load feature 491
```

**Comment by dcdenu4** [comment]
Pushing a fix for the global poly shapefile now to invest-sample-data repo.

**Comment by dcdenu4** [comment]
The fixed global poly layer was successfully uploaded into the `master` branch of `invest-sample-data`. It had quiet stdout when run against James script above. 

https://bitbucket.org/natcap/invest-sample-data/commits/0859cc23e8c1caef0aff85fb03d8c6e24d73e8a3
