### ISSUE TITLE
Coastal Blue Carbon Price Table Language

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#361]
Rob replied to a user here: https://community.naturalcapitalproject.org/t/coastal-blue-carbon-price-table/1448 and indicates that perhaps the User's Guide doesn't properly indicate some price table information. Might be helpful to update this language.

**Comment by phargogh** [comment]
I can take this as part of the CBC updates.

**Comment by phargogh** [comment]
I went ahead and added a note (the same note) to both `main` (since users might need this sooner than the 3.9 release) and `release/3.9` in the user's guide repository, so I'll mark this as resolved.  Feel free to reopen as needed!
