### ISSUE TITLE
Update the setup-miniconda action version

### ISSUE THREAD

**Issue by emlys** [natcap/invest#380]
I noticed this message today in the github actions build binaries step: https://github.com/emlys/invest/runs/1382670814#step:6:1

>Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Hopefully updating to the latest version of conda-incubator/setup-miniconda will fix this!

**Comment by dcdenu4** [comment]
Hey @emlys this might be a duplicate of #346 !

**Comment by emlys** [comment]
Oops, so it is!
