### ISSUE TITLE
InVEST 3.9.0 development build hangs on Mac OS X Big Sur

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#384]
I'm using a recent development build of InVEST 3.9.0 (revision 7bbbec2dc120f8662361a34efb7ea58942ecf94d, on the mac codesigning branch), and launching InVEST through the mac binaries causes the application to freeze and use up a ton of CPU power while doing so.  The application hangs before any window is presented or any logging is created.sy

So far, I've tried running these binaries in these ways with the same results:

1. By double-clicking on the application (and bypassing the 'unregognized developer' warnings)
2. By running the application from a terminal:
    a. `./InVEST.app/Contents/MacOS/InVEST`
    b. `./InVEST.app/Contents/MacOS/invest_dist/invest --debug launch`

I took a sample of the process through activity monitor and attached it here.  Best guess at the moment is that it's stuck in a PyQt event loop.  [Sample of invest.txt](https://github.com/natcap/invest/files/5538932/Sample.of.invest.txt)

**Comment by phargogh** [comment]
I'll add this to the 3.9 release milestone for the moment, we can bump it to the next bugfix release if needed.

**Comment by phargogh** [comment]
After resolving and merging #383  in to `release/3.9`, this is still an issue: the mac build is still hanging, recognized by the OS as 'not responsive'.

**Comment by phargogh** [comment]
The latest commit on this branch is actually a merge: https://github.com/natcap/invest/pull/392/commits/89c9c569956cab2db52224717af2e9b7bedf8561 , and the builds appear to be working there.

**Comment by dcdenu4** [comment]
I'm not sure where this issue stands at the moment. Will leave as 3.9 milestone until conferring with James during the morning call. We have confirmed it works on Big Sur though I think, so maybe this is fixed?
