### ISSUE TITLE
pytest output has strange XPath lines

### ISSUE THREAD

**Issue by emlys** [natcap/invest#390]
Observed on macOS, pytest version 6.1.2 (latest), python 3.7.9.
Pytest output includes a bunch of repetitive lines:
```
tests/test_hra.py::HraUnitTests::test_missing_index_from_criteria_csv PASSED
tests/test_hra.py::HraUnitTests::test_simplify_geometry 	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
PASSED
tests/test_hra.py::HraUnitTests::test_simplify_geometry_lines 	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
PASSED
```
I'm pretty sure these tests used to print out more useful information. This could be a pytest issue, though I don't see it mentioned on their repo.

**Comment by phargogh** [comment]
I've been seeing this in the latest mac binaries as well when running `invest` from the CLI, so definitely not just an issue with pytest.

Come to think of it, this came up recently on the QGIS email lists as well, and that this was probably coming from `libspatialite`.  No resolution mentioned so far.

**Comment by dcdenu4** [comment]
I am also seeing it via Windows when calling `invest run model`. It is super annoying.

**Comment by emlys** [comment]
This looks to be an issue with gdal>=3.1.3 that involves [libspatialite](https://github.com/Dushistov/libspatialite/blob/master/src/spatialite/virtualxpath.c). Since invest only needs gdal>=3.1.2, we can use 3.1.2 to avoid the annoying messages.

**Comment by emlys** [comment]
For a long-term fix, I have opened an issue on OSGeo/gdal: https://github.com/OSGeo/gdal/issues/3269

**Comment by dcdenu4** [comment]
Update: Looks like a release candidate for `libspatialite 5.0.1` is out: https://www.gaia-gis.it/fossil/libspatialite/index

**Comment by dcdenu4** [comment]
5.0.1 (released on 2021-02-07)

**Comment by emlys** [comment]
Looks like this has been resolved.
