### ISSUE TITLE
Release InVEST as a 64-bit binary

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#4]
When we started developing and shipping binaries for InVEST, 32-bit binaries was an obvious choice as so many computers were still running Windows XP or were running on very old hardware.  In this modern age, I can't remember the last time I saw someone working with a 32-bit windows computers, and macs are all 64-bit anyways.  The only computer system I can think of that runs a 32-bit OS is the Raspberry Pi, but that'll be on linux and would therefore not be using our prebuilt binaries.

- [x] Check the InVEST usage stats ... do we have any records of people running InvEST on a 32-bit system in recent history?
- [x] If it's reasonable to only ship 64-bit, we should still run our tests against 32-bit and 64-bit builds of python on Windows if possible.

**Comment by phargogh** [comment]
Just found out that [Microsoft will be dropping support for 32-bit versions of Windows 10](https://www.bleepingcomputer.com/news/microsoft/rip-microsoft-to-drop-support-for-windows-10-on-32-bit-systems/) very soon (early summer, 2020).  QGIS as a project is doing the same in their next release.

**Comment by phargogh** [comment]
I checked over the model run logs, and I was wrong about tracking this ... we haven't been.  I had assumed that the linux platform strings (e.g. `Linux-4.15.0-47-generic-x86_64-with-debian-buster-sid`) would be reflected in the Windows information.  It isn't.  Example: `Windows-8-6.2.9200`.  Architecture is not implied by build number, it turns out.

All that being said, it also turns out that two things have happened recently that support the argument that we should phase out our 32-bit binaries:

* **It'll be harder for us to develop with 32-bit libraries**  Conda-forge announced a year or two ago that they would be [dropping support for 32-bit windows builds](https://github.com/conda-forge/staged-recipes/issues/5640).  For us, this is most noticeable with GDAL, as nothing above GDAL 2.4.4 is available in a 32-bit build.
* **Microsoft is no longer distributing 32-bit Windows to OEMs** Although this will not affect existing 32-bit installations of Windows (for now), this is likely the beginning of the end for 32-bit Windows builds. [Article on engadget](https://www.engadget.com/windows-10-32-bit-oem-173055990.html).

Therefore, it would be in our best interest to release Windows binaries for InVEST 3.9 and later as 64-bit only.

- [ ] We should also see about including a check in NSIS for whether their computer is 64-bit and show some helpful user feedback if so.

**Comment by dcdenu4** [comment]
PR #314 moves to 64-bit builds and testing only as it relies solely on conda for package dependency management. If this PR goes through it would mean that we would not be testing 32-bit versions. 

PR #314 does not tackled a check in NSIS for whether a users computer is 64-bit.

**Comment by dcdenu4** [comment]
@phargogh what do we think about the NSIS check for architecture? Should we bring up a warning page if they happen to be on a 32-bit machine?

**Comment by phargogh** [comment]
An architecture check sounds nice, especially since we'll only be offering 64-bit binaries starting with this release. Still, I think it would be nice for this to be a warning only ... a user could still conceivably install InVEST onto some other media to be used on a different OS.  What do you think?

**Comment by dcdenu4** [comment]
Working on this in a branch I've created on my fork call: `installer-architecture-warning`

**Comment by dcdenu4** [comment]
This is done!
