### ISSUE TITLE
Water Yield naming inconsistency

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#401]
I think this has always been a weird issue, but I've seen
- Water Yield (model name in startup)
- Hydropower Water Yield (name in model UI and default workspace name)
- Annual Water Yield (UG Name and sample data name)
- hydropower_water_yeild (CLI name)

I think that we've tried to get away from the Hydropower naming convention and adopt the Annual Water Yield one.

**Comment by emlys** [comment]
I've seen this with a lot of the models too and I think it's becoming more of a problem now that we have the workbench. It's been confusing figuring out how to refer to a model. The args spec has `model_name` e.g. 'Wind Energy' and `module` e.g. `natcap.invest.wind_energy`, while `invest list` has two different names: `wind_energy` and `Offshore Wind Energy Production`. It would be great to standardize these.

**Comment by dcdenu4** [comment]
Yep, and for the Wind Energy model, I reckon it should be `offshore_wind_energy`, because that's what the model and data are designed for. But, if we decide to mix some of these up that change the UG or user facing UI, we should try and get confirmation with the science leads.

**Comment by emlys** [comment]
This was fixed in #677.
