### ISSUE TITLE
Beef up tests for GLOBIO

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#409]
I made some not insignificant changes in GLOBIO and the tests all passed. I believe this is a product of the tests being so simple. I'd suggest:

- A test with infrastructure rasters having nodata and 1 for where infrastructure is
- A test with LULC having a nodata border
- A test with rasters larger than 256 x 256, so multiple raster_calculator calls get run.

**Comment by davemfish** [comment]
🐮
