### ISSUE TITLE
Remove python2 stuff from throughout natcap.invest

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#41]
When `natcap.invest` supported both python2 and python3, we used the `future` package and a few other things (like conditionally importing `Queue` vs `queue`) for compatibility.  It would be great to trim this to whatever degree is reasonable.

Known parts to this:

- [x] mock --> unittest.mock
- [x] Remove `future` from `requirements.txt`
- [x] Remove `future` and future-defined imports (builtins, others?) throughout the package
- [x] Replace instances of `basestring` with `str` (hra.py, ... )

**Comment by dcdenu4** [comment]
Under invest/ui/model.py there's the following code:
```
try:
    import PyQt4
except ImportError:
    # PySide2 seems to be the only package that works with qtpy under python3.
    import PySide2
```
Is this related to Python 2 vs 3? PyQt4 says it supports both Python v2 and v3.?

**Comment by dcdenu4** [comment]
Might have answered my own question in invest/ui/launcher.py
```
try:
    import PyQt4
except ImportError:
    # Need to explicitly import PySide2 when on python3.  It's the only Qt
    # binding I can seem to get to work under python3.
    import PySide2
```

**Comment by phargogh** [comment]
Yeah, I think the issue here was that I couldn't get pyqt4 to work under python3.  I don't remember the details for sure, but I wouldn't be surprised if it had to do with distributing the library with pyinstaller!  Either way, I really do think that pyqt5 is preferable over pyqt4, since pyqt4 development has stopped (I think) or at least is no longer being actively developed, and the API better aligned with native python types where possible.

**Comment by dcdenu4** [comment]
@phargogh Ok, so it's a little confusing the development of `PySide2` vs `PyQt5`, but we want to stick with `PySide2`?

**Comment by phargogh** [comment]
Oh gosh, yes, I'm sorry about the confusion!  `PySide2` is the correct library to use.

As an aside about the libraries, both libraries are bindings to `Qt5`, they're just released under slightly different licensing terms, are maintained by different groups and have *slightly* different APIs in a few places.  In theory, all of `pyqt4`, `pyqt5`, `pyside` and `pyside2` should be supported by most of the `natcap.invest.ui` package through the `qtpy` interface layer ... and in practice, `PySide2` was the only one that I could actually get to work for our binary build targets.
