### ISSUE TITLE
DelineateIt - output stream network when snap=False?

### ISSUE THREAD

**Issue by emlys** [natcap/invest#412]
In pre-release testing for 3.9, Stacie brought up the following:
>  Interesting that snapping to the nearest stream is separated now, along with defining the TFA, which is surprising. I see that when I don't snap, I get a tiny watershed, which would be expected if the outlet doesn't lie on the stream, but it does (at least with a TFA of 1000). And if snapping is not selected, no stream layer is output, making it hard to understand why the tiny watershed was created, and then makes me wonder how the model is defining streams when the TFA isn't set.

> I'm wondering if a stream network can be output for the case where people don't choose to snap, so they can see why the generated watershed turned out the way it did. 

After the release, we should discuss further what this means. Since this isn't directly related to 3.9 changes I'm making an issue now so we don't forget.

**Comment by davemfish** [comment]
This issue has some minor overlap with #479 . They're distinct issues, but someone might wish to think about them together.

**Comment by emlys** [comment]
(tagging @newtpatrol so she sees this)
Coming back to this, I realized that there is no stream network to show when snapping is off.

Watersheds are delineated from the flow direction raster (using `pygeoprocessing.routing.delineate_watersheds_d8`), not from flow accumulation or streams. The flow accumulation and stream rasters aren't even produced when snapping is off. Unfortunately, the flow direction input is not very helpful for understanding the watershed output. But I don't think we can do anything about that given the current routing implementation.

I have thought for a while it would be nice to have a script for visualizing flow direction rasters, though...
