### ISSUE TITLE
Forest Carbon output in nodata areas

### ISSUE THREAD

**Issue by emlys** [natcap/invest#414]
Running Forest Carbon with the sample data, there are some weird shapes showing up in the output carbon map raster. The glowing dots in the bottom left and light colored shapes in the bottom right are outside of the input data areas.
<img width="611" alt="Screen Shot 2020-12-09 at 11 50 25 AM" src="https://user-images.githubusercontent.com/43770515/101673737-cabbe300-3a14-11eb-9910-73586388ecab.png">

**Comment by dcdenu4** [comment]
Merged and fixed!
