### ISSUE TITLE
Forest Carbon features unable to be transformed

### ISSUE THREAD

**Issue by emlys** [natcap/invest#418]
Running Forest Carbon with the sample data I get this warning: `geoprocessing.reproject_vector(1688) WARNING 96 features out of 2313 were unable to be transformed and are not in the output vector at /Users/emily/Documents/forest_carbon_edge_effect_workspace/intermediate_outputs/local_carbon_shape.shp`
This might be normal because the global dataset is being transformed to a local projection, maybe some are too far away from the projection area. We should make sure that's why, and filter out those too-far-away points of the global dataset before they are transformed.

**Comment by emlys** [comment]
I gave this some thought and it's a little trickier than I expected.

It's not as simple as cropping the global dataset, because we don't know how much to crop it. For each pixel, the model uses the _n_ nearest polygons from the global dataset. Those polygons don't have to be within the AOI, or within any particular distance of the AOI. So we can't crop it to a certain size around the model inputs.

I haven't found any way to tell if a polygon can be reprojected to the target projection without just trying to reproject it. So we can't crop the global dataset to the "known reproject-able" area either.

It's probably most efficient and pythonic to try/fail on every polygon as we currently do. `pygeoprocessing.reproject_vector` could verify that failures are due to the polygon being too far away. And could report it in a better way than logging a warning.

**Comment by davemfish** [comment]
I believe this was addressed recently in https://github.com/natcap/invest/pull/1646

The solution there is to do partial reprojection, which skips over geometries that cannot be transformed

```python
    with utils._set_gdal_configuration('OGR_ENABLE_PARTIAL_REPROJECTION', 'TRUE'):
        pygeoprocessing.reproject_vector(
            tropical_forest_edge_carbon_model_vector_path, lulc_projection_wkt,
            carbon_model_reproject_path)
```
