### ISSUE TITLE
Models hang on macOS with n_workers>0

### ISSUE THREAD

**Issue by emlys** [natcap/invest#420]
Seen on a few models but likely not a model-specific issue. May be related to the update to taskgraph 0.10
```
2020-12-11 13:39:47,889 Task.__del__(418) ERROR Expected an empty logging queue, but if the TaskGraph were being terminated it's possible this object is corrupt and we'd get a different kind of exception like EOF. In any case we should always stop trying to drain the queue in the case of an Exception.
Traceback (most recent call last):
  File "site-packages\taskgraph\Task.py", line 413, in __del__
  File "multiprocessing\queues.py", line 126, in get_nowait
  File "multiprocessing\queues.py", line 107, in get
_queue.Empty
2020-12-11 13:39:47,890 Task.__del__(440) DEBUG joining _monitor_thread.
2020-12-11 13:39:47,890 Task.__del__(464) ERROR exception occurred during __del__
Traceback (most recent call last):
  File "site-packages\taskgraph\Task.py", line 444, in __del__
  File "threading.py", line 1041, in join
RuntimeError: cannot join current thread
```

**Comment by emlys** [comment]
Confirmed that DelineateIt and Forest Carbon are hanging and that this is a new issue in 3.9.0.

**Comment by emlys** [comment]
Forest Carbon gets stuck after the `calculate_forest_edge_carbon_map` task completes, maybe something's going wrong with the `join` or new task instantiation [here](https://github.com/natcap/invest/blob/e2a02a02ed33bfd2c5cf0cd708e5935fd5645930/src/natcap/invest/forest_carbon_edge_effect.py#L375-L377).

DelineateIt gets stuck in the `fill_pits` task. See attached log files. I'm not really sure how to effectively debug this issue, since it only happens with the app, and likely is related to taskgraph. Any ideas welcome!

**Comment by dcdenu4** [comment]
@emlys did you confirm this is an issue regardless of TG version?

**Comment by emlys** [comment]
@dcdenu4 it's definitely still happening with the latest 0.10.2. I'm no longer getting the error that I pasted originally, I think that got fixed in the 0.10.2 release

**Comment by phargogh** [comment]
I've been able to reproduce this on Big Sur using the 3.9.0 binaries on the 3.9.0 sample data, working with delineateit.  Using an `n_workers` of 4, the model was _not_ leading to a hang when the taskgraph logging level is set to `INFO`.  @emlys are you also observing this behavior?

I'm having some difficulties with the Qt event loop in my development environment, but one other thing that I'm hoping to try is to see if running the InVEST binaries from the launcher (`$ invest launch`) will allow us to reproduce the hanging issue without having to go through the trouble of doing a binary build.

**Comment by emlys** [comment]
Interesting, I am also seeing it with delineateit, but it still hangs for me regardless of the logging level.

**Comment by emlys** [comment]
I wasn't able to replicate it using `invest launch`. Hoping to try it on the workbench, but the mac binaries aren't working (https://github.com/natcap/invest-workbench/issues/94)

**Comment by emlys** [comment]
I couldn't reproduce the issue in the workbench. Because of that and that you can get around it by running invest from the command line, I don't think this is critical for 3.9.1.
