### ISSUE TITLE
pandas 1.2.0 compatibility

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#428]
It looks there are some breaking changes in this pandas release with test failures/errors observed in `utils`, `validation` and `wind_energy`.

https://pandas.pydata.org/docs/whatsnew/v1.2.0.html

Here's an example failing test suite:
https://github.com/natcap/invest/pull/399/checks?check_run_id=1645871551

**Comment by dcdenu4** [comment]
Thank goodness they waited until after 3.9 to release this!

**Comment by davemfish** [comment]
Yeah, maybe not a coincidence they scheduled the release for Dec 26th?

Related to this issue, but not necessarily causing our test failures, pandas demands use of `openpyxl` instead of `xlrd`

**Comment by davemfish** [comment]
One of the failing tests here is in `test_utils.py` : `test_non_utf8_encoding` where we expect non utf8-encoded characters to _not_ raise an error when read by `pandas.read_csv` _without_ specifying an encoding. Apparently the "python" engine of `pandas.read_csv` would silently replace unknown characters with some default characters when this happens (if I'm reading our test correctly).

But now in pandas 1.2.0, a `UnicodeDecodeError` is raised (or rather, uncaught) instead. I've had a hard time finding exactly which changes created this new behavior, but I think they ought to be in this diff (https://github.com/pandas-dev/pandas/compare/v1.1.5...pandas-dev:v1.2.0) in `io/parsers.py`

Anyway, I'm not certain of the history of this test, so I'm interested to discuss if we really do want pandas to silently replace the unparseable characters. Especially if it means we have to manage that ourselves instead of letting pandas do it. @phargogh @emlys @dcdenu4 


```
tests\test_utils.py:890:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
env\lib\site-packages\natcap.invest-3.8.9.post1103+ge2a02a02.d20210106-py3.7-win-amd64.egg\natcap\invest\utils.py:587: in read_csv_to_dataframe
    sep=sep, **kwargs)
env\lib\site-packages\pandas\io\parsers.py:605: in read_csv
    return _read(filepath_or_buffer, kwds)
env\lib\site-packages\pandas\io\parsers.py:457: in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
env\lib\site-packages\pandas\io\parsers.py:814: in __init__
    self._engine = self._make_engine(self.engine)
env\lib\site-packages\pandas\io\parsers.py:1045: in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
env\lib\site-packages\pandas\io\parsers.py:2291: in __init__
    self._make_reader(self.handles.handle)
env\lib\site-packages\pandas\io\parsers.py:2412: in _make_reader
    line = f.readline()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.utf_8.IncrementalDecoder object at 0x000001B177EF98C8>
input = b'header,\r\nf\xce\xce,\r\nbar', final = False

    def decode(self, input, final=False):
        # decode input (taking the buffer into account)
        data = self.buffer + input
>       (result, consumed) = self._buffer_decode(data, self.errors, final)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 10: invalid continuation byte

env\lib\codecs.py:322: UnicodeDecodeError
```

**Comment by emlys** [comment]
I spent some time tracing this back and it's from changes in `io/common.py`. In v1.1.5 the error handling is sometimes set to 'replace' mode: https://github.com/pandas-dev/pandas/blob/b5958ee1999e9aead1938c0bba2b674378807b3d/pandas/io/common.py#L496 but in v1.2.0 it's not: https://github.com/pandas-dev/pandas/blob/3e89b4c4b1580aa890023fc550774e63d499da25/pandas/io/common.py#L643
Not sure if that was a bug before? Weird that it's not in the changelog.

**Comment by emlys** [comment]
Anyways, it doesn't look like we can set the `errors` parameter. That's an internal pandas thing. So maybe we no longer have the option of letting pandas replace unknown characters.

I don't really like the idea of replicating the 'replace' mode ourselves. I think we'd have to search and replace non-unicode characters in a byte string before calling `read_csv`. So I'm inclined to say that we don't need to support non-UTF8 inputs.

**Comment by phargogh** [comment]
Yep, looks this this behind-the-scenes change that we don't have much control over, but this is really a good thing!  Silent replacement could cause problems for us down the road.  For these tests that use `iso8859_5`, I think we could just pass in that encoding to `utils.read_csv_to_dataframe` within the test.  That's consistent with how pandas wants us to use its parsing functionality and is more explicit about how the file will be read.

But that leaves the problem about what to do with table encodings across InVEST in the general case, when we won't know the table's encoding in advance.

For the longer term, what if we were to support tabular inputs being either Excel or UTF-8 CSV files?  Excel workbooks always have a defined encoding, and UTF-8 CSVs are easy enough to create in Excel if you know what to look for.  We'll probably still have some issues when people accidentally export workbooks to CSV (the default Excel export writes `latin-1` CSVs), but validation and docs could help with that.

The only other option I could see would be to try to guess the user's encoding of a CSV field.  For convenience, we actually do this in the Qt ui via [`chardet`](https://pypi.org/project/chardet/), and `chardet` might be good enough for this purpose.  Even so, knowing a user's encoding will always be superior to guessing, and also cheaper to compute.

**Comment by dcdenu4** [comment]
Good sleuthing everyone! I think what James suggests seems good to me. For unknown encodings I like the idea of using `chardet` to read X number of bytes and use an educated guess at the determined encoding. If it still fails to read, could also tag along the confidence that `chardet` reports in the error message. This certainly feels like an upfront validation thing.

**Comment by davemfish** [comment]
Great find @emlys ! 

I agree that the silent replacement is problematic and I'm not sad that pandas has stopped doing it. We have tests that cover the following:
* reading a `latin-1` csv _without_ passing the encoding to `read_csv` (passes)
* reading an `iso8859_5` csv that includes a non-ASCII character _without_ passing the encoding (now raises `UnicodeDecodeError`)
* reading an `iso8859_5` csv that includes a non-ASCII character _with_ passing the encoding (passes)

So I think we can do without that middle failing test, as it only tested the replacement behavior that no longer exists. The other two tests cover the cases that are still important. Specifically, that first test assures us that we _can_ read arbitrary csv encodings without knowing the encoding, _so long as they do not include non-ASCII characters_. 

That leaves the rarer case where there is an unknown encoding with a non-ASCII character. `chardet` does look super convenient for handling this, but I tried it with that second test and it got the encoding wrong when given only the first line of the csv. So we might have to read an unknown amount of file before getting good results from `chardet`. That's fine for the `ui/inputs` use-case, but not good for this `read_csv` use-case. So I'm going to PR this without `chardet` for now.

**Comment by emlys** [comment]
Any idea how often people use non-UTF8, non-ASCII characters in their CSVs? Given that UTF8 supports virtually all languages, is this a problem we really need to address?

**Comment by davemfish** [comment]
> Any idea how often people use non-UTF8, non-ASCII characters in their CSVs? Given that UTF8 supports virtually all languages, is this a problem we really need to address?

Well-said. This was the thrust of my opening question about the history of that particular test.

**Comment by davemfish** [comment]
I was going to leave that test in and assert that a `UnicodeDecodeError` is raised with a message that says, "please try a utf8-encoded file." But now I'm having a heck of a time getting past a PermissionDenied error. It really seems like pandas is not properly closing the file handle when `read_csv` raises the `UnicodeDecodeError`

**Comment by davemfish** [comment]
```
    import psutil
    proc = psutil.Process()
    try:
        print(proc.open_files())  # file is not open here
        dataframe = pandas.read_csv(
            path, engine=engine, encoding=encoding, sep=sep, **kwargs)
    except UnicodeDecodeError as error:
        print(proc.open_files())  # file is still open here
        LOGGER.error(f'{path} must be encoded as utf-8')
        raise
```
And then the file is still open when the test runs it's teardown.

**Comment by davemfish** [comment]
I think this might be a bug. I made a reproducible example here: https://github.com/pandas-dev/pandas/issues/39024

**Comment by phargogh** [comment]
> > Any idea how often people use non-UTF8, non-ASCII characters in their CSVs? Given that UTF8 supports virtually all languages, is this a problem we really need to address?
>
> Well-said. This was the thrust of my opening question about the history of that particular test.

I don't have a direct answer to this for CSV files, but the popularity of UTF-8 in webpages has been rising over the last number of years: https://en.wikipedia.org/wiki/File:Utf8webgrowth.svg which might indicate a broader support for and awareness of UTF-8.  UTF-8 does indeed support all written human language (and some fictitious languages), within about half of the available codepoints, which is great.  While it's commonplace, not everyone uses it.  For us, we'd just need to be deliberate about what happens when someone provides a non-UTF-8 CSV and hopefully make that experience less cryptic and painful if we do decide to require UTF-8.

**Comment by davemfish** [comment]
This issue came back with version 1.3.0 where pandas once again does not catch the `UnicodeDecodeError` and does not replace the characters. I really don't know why this keeps flipping back and forth - it doesn't seem like a deliberate decision as it's never mentioned in the changelogs. 

Assuming this behavior could switch back again with any given pandas release, I'm thinking the resilient solution for us is:
1. catch & re-raise a `UnicodeDecodeError` in `utils.read_csv_to_dataframe` with a message that tells users to use `utf-8` encoding. That's how we solved this originally. 
2. eliminate the two tests (`test_utils` & `test_validation`) that we have been switching back and forth between asserting the replacement characters are present & asserting the `UnicodeDecodeError` is raised. I think that test really only tests pandas behavior. And since we seem to be okay with either behavior, I don't think we need the test. Thoughts @phargogh ?

**Comment by phargogh** [comment]
Yep, this sounds just fine to me and no need to test pandas behavior here.  Looking over these tests, I think they're leftover from when we had to do some nontrivial work to handle encodings.  Passing all of that off to pandas sounds right now that we're using that package.  I see this is addressed in https://github.com/natcap/invest/pull/579/files, so I'll go take a peek at that now.
