### ISSUE TITLE
Python version specified in Makefile differs from github actions

### ISSUE THREAD

**Issue by vakowal** [natcap/invest#438]
Just FYI! It seems I am the only one who relies on the InVEST Makefile to manage my virtual environment, but there is an inconsistency that prevents the recipe for `env` to work correctly.

Makefile (line 220) creates conda environment with Python 3.8.
Github actions file (line 55) creates conda environment with Python 3.7.  

Python 3.7 is what you want, because PyInstaller 3.5 is incompatible with Python 3.8: https://pypi.org/project/pyinstaller/3.5/

When building binaries with PyInstaller==3.5 and Python==3.8, here is the error I got (and solved by using Python 3.7):

> 134938 INFO: Building PYZ (ZlibArchive) build/pyi-build\rangeland_production\PYZ-00.pyz
> Traceback (most recent call last):
>   File "C:\rangeland_production\env\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\rangeland_production\env\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\__main__.py", line 118, in <module>
>     run()
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\__main__.py", line 111, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
>     exec(code, spec_namespace)
>   File "exe/rangeland_production.spec", line 37, in <module>
>     pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
>     self.__postinit__()
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
>     self.assemble()
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
>     self.code_dict = {
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
>     key: strip_paths_in_code(code)
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\utils.py", line 652, in strip_paths_in_code
>     consts = tuple(
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\utils.py", line 653, in <genexpr>
>     strip_paths_in_code(const_co, new_filename)
>   File "C:\rangeland_production\env\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
>     return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
> TypeError: an integer is required (got type bytes)
> make: *** [dist/rangeland_production] Error 1
>

**Comment by dcdenu4** [comment]
@vakowal good point and catch! I'll update this with the changes I made related to the other makefile env issues. We'll hopefully be bumping Pyinstaller version which was recently released and now works with Python 3.8 and 3.9!
