### ISSUE TITLE
Carbon model casts lucode integers to floats

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#44]
A user experienced an issue where her pools CSV had integer *lucode* values but floating point column values. When calling `utils.build_lookup_from_csv()`, the function returns a dictionary with the *lucode* values as floats. Setting all column values to integers, then *lucode* is also returned as an integer in the dictionary.

https://community.naturalcapitalproject.org/t/keyerror-invest-3-8-0-carbon-storage-model/850

**Comment by dcdenu4** [comment]
Looks like when using `pandas` the `dtype` arg could be set to `object` which to preserve and not interpret type.

**Comment by phargogh** [comment]
Hey @dcdenu4 , I couldn't help but notice this and thought it sounded unexpected.  Doesn't python hash `4101` and `4101.0` to the same key in a dict?

```python
>>> a = {4101: 'foo'}
>>> a[4101.0]
'foo'
```

**Comment by dcdenu4** [comment]
That is something I didn't know, the more you learn! I'll look back into this user issue.

**Comment by dcdenu4** [comment]
Alright, so after looking into it a bit more the real issue the user was having was the **NA** row, where the *lucode* ID was *NA*. This caused a `KeyError` to be reported on the first ID that it came across. Just another example of the need to address how this type of thing is handled in InVEST.
