### ISSUE TITLE
Renew Code-Signing Certificate

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#458]
Our current code-signing certificate will expire on March 6, 2021.  https://uit.stanford.edu/service/ssl/codesigning has instructions for how to do this through Stanford UIT.

**Comment by phargogh** [comment]
I've submitted a request for this.

**Comment by phargogh** [comment]
Waiting for UIT to respond and create the cert.

**Comment by phargogh** [comment]
We have just learned that Windows users are unable to run previously-signed versions of the InVEST binaries now that the former certificate has been revoked (much to my surprise).  Jade is running a training this coming Monday at 8pm PT, so ideally we'll have a workaround by then.

I've also reached out to UIT for their suggestions on the matter.

**Comment by dcdenu4** [comment]
Might as well link to the wiki James nicely put together: https://github.com/natcap/invest/wiki/Code-Signing-InVEST-Installation-Media

**Comment by phargogh** [comment]
* Windows binaries (3.8.0+) have been signed and timestamped using the new code signing certificate
* Mac Binaries (3.9.0) have been signed and timestamped using the new code signing certificate
* Re-signed binaries mentioned above have been re-uploaded to GCP
* Re-signed binaries mentioned above have been re-uploaded to Github Releases

Remaining work now is to make sure we can use the new certificate in our build process.

**Comment by phargogh** [comment]
The Stanford certificate generation service granted me a `.pfx` file (which is apparently the same thing as a `.p12`).  To convert to the `.key.pem` and `.crt` files needed by `osslsigncode`, I followed the instructions at https://www.markbrilman.nl/2011/08/howto-convert-a-pfx-to-a-seperate-key-crt-file/, copied here for posterity:

```
openssl pkcs12 -in [yourfile.pfx] -nocerts -out [keyfile-encrypted.key]
openssl pkcs12 -in [yourfile.pfx] -clcerts -nokeys -out [certificate.crt]
```
