### ISSUE TITLE
Add History note about PGP pit filling max threshold

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#463]
When PGP releases with the new pit filling max pixel threshold (https://github.com/natcap/pygeoprocessing/pull/157) , it might be worth mentioning it in InVEST History, when InVEST adopts that PGP version. This will likely have an impact on results from models and modelers who rely on PGP pit filling.

PGP issue https://github.com/natcap/pygeoprocessing/issues/117

**Comment by dcdenu4** [comment]
Just noting this PGP issue: https://github.com/natcap/pygeoprocessing/issues/158

**Comment by dcdenu4** [comment]
Still unreleased.

**Comment by emlys** [comment]
Still unreleased

**Comment by emlys** [comment]
This change was released in pygeoprocessing 2.2.0, invest 3.9.1. Is it worth retroactively adding to the history?

**Comment by dcdenu4** [comment]
We could, but I don't think it's necessary. The change would probably be most useful for us and we have it logged in Pygeoprocessing's history. It's also not something that is exposed to the user as something they can change from InVEST. I'm fine either way, but think we can leave it out.
