### ISSUE TITLE
Malformed code block preventing readthedocs from building

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#472]
PR #467 introduced a bug in the API docs that I should have caught that's preventing the readthedocs build from building.  Pretty sure this is just a matter of turning

```rst
.. code-block:: python
    if __name__ == '__main__':
```

into
```rst
.. code-block:: python

    if __name__ == '__main__':
```

**Comment by emlys** [comment]
Oops sorry @phargogh! I'm too used to at least one of the checks failing, I didn't notice it was important this time 😞

**Comment by phargogh** [comment]
I did it too!  Kinda underscores the importance of keeping our tests passing if at all possible ... so easy to have one additional test failure slip by.
