### ISSUE TITLE
GEOS and PROJ bump causing Wave Energy / Coastal Vulnerability tests to fail

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#476]
I noticed tests failing not related to PR #475 . When looking at the conda env diff, I saw some important updates. 

When updating to Proj=7.2.0 in Conda locally I could reproduce the test failures and I also got the dependent updates:

```
The following packages will be UPDATED:

  cairo                                1.16.0-hd28d34b_1006 --> 1.16.0-hba8bd2f_1007
  expat                                    2.2.9-h33f27b4_2 --> 2.2.10-h39d44d4_0
  gdal                                 3.2.1-py38hb9e1232_0 --> 3.2.1-py38hb9e1232_4
  geos                                     3.8.1-he025d50_0 --> 3.9.0-h39d44d4_0
  geotiff                                  1.6.0-h8884d1a_3 --> 1.6.0-h5d775bf_4
  icu                                       67.1-h33f27b4_0 --> 68.1-h0e60522_0
  libclang                        10.0.1-default_hf44288c_1 --> 11.0.1-default_h5c34c98_1
  libgdal                                  3.2.1-h0d43894_0 --> 3.2.1-hd376e63_4
  libspatialite                            5.0.0-hf693123_0 --> 5.0.1-h6966176_2
  openjpeg                                 2.3.1-h48faf41_3 --> 2.4.0-h48faf41_0
  poppler                                 0.89.0-h5d62644_1 --> 0.89.0-h3772339_5
  proj                                     7.1.1-h7d85306_3 --> 7.2.0-h3e70539_1
  qt                                      5.12.9-hb2cf2c5_0 --> 5.12.9-h5909a2a_3
  shapely                              1.7.1-py38hc96c142_1 --> 1.7.1-py38hc55ee08_2
  tiledb                                   2.1.6-hf84e3da_1 --> 2.2.3-hf84e3da_0
```

**Comment by dcdenu4** [comment]
The CV error makes it looks like a `shapely.ops.linemerge` call is failing, though the Shapely version has remained the same but is compiled against the newer dependencies. I see `geos` and `libspatiallite` are also bumped a version.

**Comment by dcdenu4** [comment]
PROJ release notes: https://proj.org/news.html

I can't find anything helpful for GEOS change logs.

**Comment by dcdenu4** [comment]
PROJ 7.2.0 was released in November. `libspatiallite 5.0.1` was released yesterday, 2/7/2021. GEOS 3.9.0 was released on Dec. 15th.

**Comment by emlys** [comment]
hooray for the conda env diff actions step!

**Comment by dcdenu4** [comment]
For CV:
`test_shore_points_on_multi_polygon` passes
`test_shore_points_on_single_polygon` fails with:
```
>       coastal_vulnerability.prepare_landmass_line_index_and_interpolate_shore_points(
            aoi_path, landmass_path, model_resolution, target_vector_path,
            polygon_pickle, lines_pickle, lines_rtree)

tests\test_coastal_vulnerability.py:963:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\venv-space\pyinstaller-41\lib\site-packages\natcap.invest-3.9.0.post185+g9cb3c7d6.d20210208-py3.8-win-amd64.egg\natcap\invest\coastal_vulnerability.py:722: in prepare_landmass_line_index_and_interpolate_shore_points
    unioned_line = shapely.ops.linemerge(lines_in_aoi_list)
..\venv-space\pyinstaller-41\lib\site-packages\shapely\ops.py:120: in linemerge
    result = lgeos.GEOSLineMerge(source._geom)
..\venv-space\pyinstaller-41\lib\site-packages\shapely\geometry\proxy.py:34: in _geom
    self.__geom__, n = self.factory(self.context)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

ob = [[], [], [], []]

    def geos_multilinestring_from_py(ob):
        # ob must be either a MultiLineString, a sequence, or
        # array of sequences or arrays

        if isinstance(ob, MultiLineString):
             return geos_geom_from_py(ob)

        obs = getattr(ob, 'geoms', ob)
        L = len(obs)
        assert L >= 1
        exemplar = obs[0]
        try:
>           N = len(exemplar[0])
E           IndexError: list index out of range

..\venv-space\pyinstaller-41\lib\site-packages\shapely\geometry\multilinestring.py:124: IndexError
```

**Comment by dcdenu4** [comment]
For whatever reason, `aoi_shapely.intersection(landmass_line)` is returning `LINESTRING EMPTY` when using these inputs:

<img src="https://user-images.githubusercontent.com/2659980/107271061-b5b1ff00-6a19-11eb-8575-33c25b31a8ed.png" width="100" height="100">

But returns valid geometries when using these inputs:

<img src="https://user-images.githubusercontent.com/2659980/107271329-12adb500-6a1a-11eb-8a99-a2057958c283.png" width="100" height="100">

The larger box is the AOI and ther smaller ones are the landmass polygons.

**Comment by dcdenu4** [comment]
Alright, so it looks like PROJ 7.2.0 IS causing a Wave Energy Test failure:

```python
================================== FAILURES ===================================
______ WaveEnergyUnitTests.test_pixel_size_based_on_coordinate_transform ______

...

     # Call the function to test
     result = wave_energy._pixel_size_based_on_coordinate_transform(
             raster_path, coord_trans, point)
   
     expected_res = (5553.933063, -1187.370813)
  
     # Compare
     for res, exp in zip(result, expected_res):
          self.assertAlmostEqual(res, exp, places=5)
           AssertionError: 5553.932270178571 != 5553.933063 within 5 places (0.0007928214290586766 difference)
```

**Comment by dcdenu4** [comment]
Dave got confirmation on the GEOS intersection issue: https://github.com/libgeos/geos/issues/408

**Comment by dcdenu4** [comment]
We ended up skipping the tests that GEOS 3.9.0 and PROJ 7.2.0 were causing to fail so that development could continue. Supposedly, GEOS is backporting a fix to 3.9 that should take care of those issues. For the PROJ 7.2.0 update, we should look at if these precision changes could just be loosened in the tests or maybe there's a better way to do the test that doesn't require looking at that kind of precision.

**Comment by davemfish** [comment]
A different CV test is failing now and our awesome conda env diffing suggests a change from geos 3.9.0 to 3.9.1 is probably the most significant thing that changed since the test was passing. https://github.com/natcap/invest/runs/1982446089?check_suite_focus=true

**Comment by davemfish** [comment]
The CV tests we had been skipping are passing again with geos 3.9.1, so that's great, they fixed the bug we reported. But test failing now is a regression test on the complete run, so will take some digging to figure out why final values are different under this version.

**Comment by dcdenu4** [comment]
One step forward and two steps back! Glad the conda env diffing has been helping!

**Comment by davemfish** [comment]
It turns out the CV results have not changed at all, but the shore points features were created in a different order, so our assertion on equal dataframes failed. Shore point creation is downstream of a bunch of geos-related operations for merging & intersecting landmass line features, so I guess that explains it. Again, the shore point geometries and data have not changed/regressed, the features just appear in a different order in the layer.

I updated the regression data here: https://bitbucket.org/natcap/invest-test-data/pull-requests/20/updated-regression-data-for-the-complete

It would kind of be nice if we could guarantee that the feature order won't keep changing without our knowledge, but it's probably unlikely to happen again.

**Comment by phargogh** [comment]
Looks like this has been addressed with #505 .

**Comment by dcdenu4** [comment]
Was the Wave Energy test handled? I skipped one of those tests to decide whether we should keep bumping precision or loosen it up?

**Comment by davemfish** [comment]
Wave energy was not touched in 505. I tried unskipping them with the new GEOS version, but that didn't seem to be the problem so I left them skipped.

**Comment by dcdenu4** [comment]
I'm on it.

**Comment by dcdenu4** [comment]
One of the failing Wave Energy tests is a regression test that asserts clipped polygons. Visualizing the outputs they look identical, interestingly the returned order of geometry is different. There is also an extra entry, see below.
```
>>> len(actual_shapely.wkt)
68359
>>> len(expected_shapely.wkt)
68358
```
