### ISSUE TITLE
DelineateIt UI - bug in enabling/disabling optional inputs

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#479]
As reported by Jesse on slack:  

> I was able to get the UI to accept both point vector and snap points options (v3.9) by populating the fields in a different order (vector before DEM raster). Once the snap points options become greyed out, I can't access them AND the vector input together without quitting and then restarting InVEST.

The goal here is for Jesse to supply his own outlet point vector, while still using the "snap points" option and associated parameters (distance & threshold flow accum).

**Comment by davemfish** [comment]
Further investigation suggests it may not have been the order of the inputs being touched, but rather the UI not recognizing a `MULTIPOINT` geometry type as an acceptable type.

**Comment by phargogh** [comment]
Hmm, I hadn't considered the case of a `MULTIPOINT` geometry type when looking at point snapping.  If we support `MULTIPOINT` geometry types, then we should also consider the case of `GEOMETRYCOLLECTION`.  I see that there are `Z`, `M`, `ZM`, and `25D` variants of these geometric types as well, but I've never seen these used in the wild and so would suggest that we defer these checks until later.

With DelineateIt's current behavior, all points in a `MULTIPOINT` geometry will be treated as a single feature of interest, and so the watershed(s) will ultimately be delineated from these 3 points.  There's a certain orthogonal elegance to this that I really like, as it allows the user to retain control over how component points are grouped.

Either way this goes, the UG should be clear about how these multipart geometries are handled.

**Comment by davemfish** [comment]
I think we've got two separate issues being raised now, which is great.

1. what do about conditional enabling/disabling of the "snap points" section of the UI. Is it reasonable at this point to remove the conditions from this checkbox altogether? Whether a user supplies their own vector or chooses to let delineatIt detect the pour points, "snap points" makes sense as an option either way, right? 

2. what to do about `MUTLIPOINT` types and other variants. 

> With DelineateIt's current behavior, all points in a MULTIPOINT geometry will be treated as a single feature of interest, and so a single watershed(s) feature will ultimately be delineated from these 3 points. There's a certain orthogonal elegance to this that I really like, as it allows the user to retain control over how component geometric objects are grouped.

I agree this makes sense from a GIS context. But does it ever make sense to have a single watershed composed of multiple features? That kinda goes against the definition of a watershed, right?

**Comment by phargogh** [comment]
> I agree this makes sense from a GIS context. But does it ever make sense to have a single watershed composed of multiple features? That kinda goes against the definition of a watershed, right?

The consistent definition of a watershed that I'm finding online is that a watershed is the area upstream of a single point ([ArcGIS](https://desktop.arcgis.com/en/arcmap/10.3/tools/spatial-analyst-toolbox/how-watershed-works.htm), [Wikipedia](https://en.wikipedia.org/wiki/Drainage_basin)).  So then when we added support for delineating the watersheds of lakes, we're already stretching the definition of a watershed.

> 1. what do about conditional enabling/disabling of the "snap points" section of the UI. Is it reasonable at this point to remove the conditions from this checkbox altogether? Whether a user supplies their own vector or chooses to let delineatIt detect the pour points, "snap points" makes sense as an option either way, right?

Yep, I agree with this ... 'snapping points' would make sense either way.  The outlet points are already snapped if we're detecting pour points, so the checkbox just wouldn't mean anything extra.

> 2. what to do about MUTLIPOINT types and other variants.

In Jesse's case, he had `MULTIPOINT` geometries that each had only one component point.  In his case, we could convert the Multipoint geometries to a single point, so it could be reasonable to expect that DelineateIt would snap them.

For cases where any geometries are skipped, it seems like it would be helpful to add logging to clarify what's going on.
