### ISSUE TITLE
deny file-read-data messages in os logs

### ISSUE THREAD

**Issue by emlys** [natcap/invest#489]
There are errors in the os logs indicating that InVEST is attempting to read other app preferences when it's launched (only happens with the binaries). 
```
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.VoiceMemos/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.archiveutility/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.Home/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.Safari/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.iChat/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.CloudDocs/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.mail/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.news/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.stocks/Data/Library/Preferences
```
This seemed suspicious at first but I confirmed that it happens with a minimal Qt app (https://github.com/emlys/invest/tree/minimal-qt-test). I asked at [PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/5548) and they said it's likely a Qt issue beyond their control. 

Now I'm seeing the same messages when starting the workbench, a minimal electron app, and even other apps (Chrome, Slack), so this is almost certainly not our issue. Just recording this for posterity.

**Comment by phargogh** [comment]
Hey @emlys which log are you looking at for this issue?  I'm not seeing it in the `system.log`, and the closest thing I can find is just in the general log, but it's only for a specific directory in `~/Library`:

![Screen Shot 2021-02-11 at 2 14 52 PM](https://user-images.githubusercontent.com/4583897/107705587-d1184680-6c73-11eb-91b0-f936fc4aff97.png)

The full text of the error is here: [sandboxd-warning.txt](https://github.com/natcap/invest/files/5968738/sandboxd-warning.txt)

So maybe the reported error is just on Catalina?
