### ISSUE TITLE
Update how we handle the JSON file that points to the latest builds

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#49]
We had previously set up a script at `scripts/update_installer_urls.py` to keep track of the latest application binaries, with the intent of having that be our main entry point for downloading the latest release of InVEST.  Since then, we decided that the new drupal site's scheduling functionality will be a better approach for updating the latest binaries on the natcap website.

To use this new functionality, we'll need to address a couple things:

- [x] We'll remove the old JSON file generation from the deployment process
- [x] @phargogh will talk with Irina to make sure that we understand what the target format needs to be and how the drupal site will use it
- [x] We'll update the script to use the new format
- [x] We'll use the new script in response to a new release (perhaps as part of a github action?)

**Comment by phargogh** [comment]
* Assigning to myself because I need to write to Irina to figure out the state of the drupal-side auto-updating
* Assigning to @dcdenu4 because we had talked about him implementing some cloud infrastructure to dynamically generate the required JSON on demand.

**Comment by phargogh** [comment]
Alrighty, I'm sorry for the delay on this update, @dcdenu4 , but I think we finally have everything in place to make this happen.

## Problem we're trying to solve

Right now, it takes some time and attention for us to log in to the natcap website and update download links for each release.  This is a part of our release checklist, so it's not that we forget, but that time spent updating hyperlinks by hand could be better spent doing other things.  It would be preferable if the website links could update themselves in response to a github release.

## Technical Requirements

A solution to this problem should solve the problem and also adhere to these technical requirements:

* The solution must return a JSON object over HTTPS when a `GET` is requested.
* Unless there are updates to the structure of the JSON (like if there are new links to be added to the file), the solution should require no user interactions.
* If an update to the code that renders the JSON object is required, an engineer should be able to commit a change to a repository and push it back and have the changes be automatically deployed.
* The JSON must adhere to [this structure](https://gist.github.com/phargogh/f2e336f1a06b940569d1698ab5c28061#file-invest-all-links-nid-json).
* The solution should compute in a reasonable amount of time, well within a common timeout for web browsers or `curl`/`wget`.

When the solution is in place and ready to try out on the website, let's talk and see about trying it out!  And of course, very happy to talk more about any of these functional requirements as needed or would be useful.

**Comment by dcdenu4** [comment]
The new approach to handling the JSON file that points to the latest builds is found in this repo:

github.com/natcap/invest-download-links

**Comment by dcdenu4** [comment]
@phargogh I think we've moved outstanding issues with this to the new repository where it now lives. So I'm going to close this.
