### ISSUE TITLE
Check that ARGS_SPEC is well-formed

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#491]
As we've been developing the workbench, which consumes `ARGS_SPEC` dictionaries to build model forms, we've been progressively elaborating and refining the specification for that structure.  And we've also found a couple of programmer errors along the way (such as https://github.com/natcap/invest/pull/446).

Now that we depend on the consistency of `ARGS_SPEC` for a programmatic consumer, we could benefit from asserting that they are all well-formed in a way that will catch accidental errors early on in our development cycle.

Known things to test include at this point:

- [ ] The structure of the dictionary, as outlined in the wiki https://github.com/natcap/invest/wiki/spec_invest#the-args_spec.  This should probably include checking valuation keys and conditional requirement.
- [ ]  lowercase, consistent labels, with whatever we end up deciding in #486

**Comment by emlys** [comment]
related to this, the validation module accounts for the `file`, `folder`, and `other` types, which aren't currently in use and should probably be removed.

**Comment by emlys** [comment]
This is in progress in #526, it's been helpful to test those changes against the new ARGS_SPEC structure.

**Comment by davemfish** [comment]
#526 included tests to assert that each model's ARGS_SPEC is well-formed, with correct types, etc.
