### ISSUE TITLE
Keep cmd.exe open on model crash

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#496]
We occasionally have errors (such as is experienced by [this user on the forums](https://community.naturalcapitalproject.org/t/the-program-does-not-work-or-open/1526/14)) where the model fails to launch.  In cases like this, we need to see the traceback in order to better diagnose the issue, and this usually requires that we walk people through running the model from `cmd.exe`.

What if the command prompt were to remain open?  If this could happen, this would allow users experiencing this error to see the error, screenshot it, and report it to us without us having to run things through `cmd.exe`.

One possible implementation could be a simple "press enter to close this window" when all of these conditions are met:
* We're running in `invest run`
* The execution is _not_ a `--quickrun`
* We're running in GUI (non-headless) mode
* The exception propagates all the way up to the CLI.

**Comment by phargogh** [comment]
I'm working on this in https://github.com/phargogh/invest/tree/feature/496-keep-cmd-open-on-ui-crash

**Comment by emlys** [comment]
Closing because we deprecated the QT interface!
