### ISSUE TITLE
Centralized ARGS_SPEC definitions for common args

### ISSUE THREAD

**Issue by emlys** [natcap/invest#498]
See discussion https://github.com/natcap/invest/pull/486#discussion_r579395449
@phargogh suggested a really neat idea of centralizing the ARGS_SPEC definition for LULC args since they are really common. This could also be done for AOIs, DEMs, and possibly others that are common. We are already centralizing their `"name"` properties by importing from `utils`. 
Some have model-specific `"about"` properties, but some of those might have more info than is really needed.
We could possibly overwrite properties as needed:
```
"lulc_raster_path": {
    "about": "some custom about property"
} | utils.LULC_ARG_SPEC
```
([neat syntax new in 3.9.0](https://www.python.org/dev/peps/pep-0584/)) or 
```
"lulc_raster_path": {
    **utils.LULC_ARG_SPEC,
    "about": "some custom about property"
}
```
(also neat)

**Comment by phargogh** [comment]
Threshold Flow Accumulation might be another one to consider, too.

**Comment by emlys** [comment]
This is in progress in #526. It's been helpful to do this alongside to avoid duplicating changes.
