### ISSUE TITLE
Implement the Stormwater Retention Model

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#504]
The Stormwater Retention model has provisional approval from the PSC\*\*, meaning we can get started on implementing it.  For the model to be complete, the model should:

* Implement the functionality described in the design doc (linked below)
* Adhere to the [InVEST Spec](https://github.com/natcap/invest/wiki/spec_invest)
* Have an implemented Qt interface
* Have a test suite with full coverage where practical
* Have sample data committed to `data/invest-sample-data`
* Be added to the InVEST installer
* Have a User's Guide chapter

Resources:
* [PEP](https://docs.google.com/document/d/1IwFJCvI9wjQX_st5zUU5j5tnLwyhsCzylCPpJNmN-VA/edit)
* [Design Doc](https://drive.google.com/file/d/1rXM49wxmb2g0foo-W2Md27AyalYFVD6_/view)
* [Data](https://drive.google.com/drive/u/1/folders/1uCxfhZ4pGsJMrhoAvVPvmKjTewGlQmnd)

When this model is ready to be merged and we have PSC approval, let's merge this into `release/3.10` for future release.

\*\* NOTE: The PSC's provisional approval is contingent on a final review of one or two minor points.  As a result, it is possible that the model's specification may change slightly and so we should wait to merge it into InVEST until we have that final PSC approval.

**Comment by emlys** [comment]
This is waiting on getting the finalized user's guide from Ben and Perrine, adding that to the UG, and then updating the UG commit hash in invest.

**Comment by emlys** [comment]
Also need to add the sample data - I have emailed Ben and Perrine about which dataset they prefer we use.

**Comment by davemfish** [comment]
Completed in #766
