### ISSUE TITLE
code coverage reporting in our Makefile is broken

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#506]
I'm not sure how long it's been this way, but it quietly reports the coverage of the test files themselves instead of the src files. Since no one noticed this until it also broke in other ways, I propose we drop coverage from the `make test` command. We can always add it back properly if we decide it's useful.

**Comment by davemfish** [comment]
An example of the incorrect report
https://github.com/natcap/invest/runs/1990005927?check_suite_focus=true#step:12:1666

**Comment by phargogh** [comment]
This looks to have been fixed in #500 .
