### ISSUE TITLE
Datastacks should be able to be loaded on any operating system

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#52]
As a cross-platform developer, I sometimes need to create a datastack archive or parameter set on Windows or Mac OS X and then load the datastack on the other operating system.  When I create a datastack on mac and load it on Windows, it works well.  When I create a datastack on Windows and load it on mac, it doesn't.  Looks like the paths are being saved with `\\` separators and perhaps that's a part of it.

**Comment by dcdenu4** [comment]
When I test `datastack.build_parameter_set` I see that the argument paths go through:
1) replace `'\\'` with `'/'`
2) normalize with `os.path.normpath`

Here's what I see from these operations:
```python
input path:  C:\Users\ddenu\raster.tif
replace path:  C:/Users/ddenu/raster.tif
norm path:  C:\Users\ddenu\raster.tif
input path:  dir/path/to/myshape.shp
replace path:  dir/path/to/myshape.shp
norm path:  dir\path\to\myshape.shp
input path:  directory\output\path\file.tif
replace path:  directory/output/path/file.tif
norm path:  directory\output\path\file.tif
input path:  linux/style/output/path.tif
replace path:  linux/style/output/path.tif
norm path:  linux\style\output\path.tif
```

**Comment by dcdenu4** [comment]
I realize I cannot easily test this from the mac side. But I could set up a linux VM which hopefully would reproduce the same issue.

**Comment by dcdenu4** [comment]
Hey @phargogh I was wondering if you could reproduce this issue and say what steps you took and what errors you got? When I save a datastack archive on Windows and look into the created json file everything looks good to me. As in:
```json
{
    "args": {
        "calc_sequestration": true,
        "carbon_pools_path": "data/carbon_pools_willamette.csv",
        "do_redd": false,
        "do_valuation": false,
        "lulc_cur_path": "data/lulc_cur_path_raster_uoqev4cq/lulc_current_willamette.tif",
        "lulc_cur_year": "2020",
        "lulc_fut_path": "data/lulc_fut_path_raster_7zfs1zdc/lulc_future_willamette.tif",
        "lulc_fut_year": "2050",
        "lulc_redd_path": "",
        "results_suffix": "willamette"
    },
    "invest_version": "3.9.0",
    "model_name": "natcap.invest.carbon"
}
```

**Comment by phargogh** [comment]
Of course!  I am a little surprised that I didn't outline the steps when I created the issue.  Sorry about that!

1. **On Windows**
    * open the Carbon UI
    * load the sample parameter set
    * save a new parameter set `.invs.json` file to a new location using relative paths.  Result:
       ```json
       {
           "args": {
               "calc_sequestration": true,
               "carbon_pools_path": "data\\invest-sample-data\\Carbon\\carbon_pools_willamette.csv",
               "do_redd": false,
               "do_valuation": false,
               "lulc_cur_path": "data\\invest-sample-data\\Carbon\\lulc_current_willamette.tif",
               "lulc_cur_year": "2020",
               "lulc_fut_path": "data\\invest-sample-data\\Carbon\\lulc_future_willamette.tif",
               "lulc_fut_year": "2050",
               "lulc_redd_path": "",
               "results_suffix": "willamette",
               "workspace_dir": "C:\\Users\\james\\Documents\\carbon_workspace"
           },
           "invest_version": "3.9.0.post202+g6c1a017de",
           "model_name": "natcap.invest.carbon"
       }
       ```
2. **On Mac**
   * Open the carbon UI
   * Select and load the carbon parameter set file saved above
   * Validation on local filepaths fails.  Correcting `\\` to `/` fixes the issue (see screenshot)
![Screen Shot 2021-02-23 at 3 20 36 PM](https://user-images.githubusercontent.com/4583897/108922609-39f4ac80-75ec-11eb-8e8e-4b8a06ebe0dd.png)

**Comment by dcdenu4** [comment]
Looks like `os.path.relpath` is swapping back to Windows style path breaks.
