### ISSUE TITLE
[Question] how to install setup.py (from ipbes-analysis) from github website? Many thanks!

### ISSUE THREAD

**Issue by yuqi9993** [natcap/invest#524]
Hi there, I’m trying to install setup.py (from the website: https://github.com/richpsharp/ipbes-analysis/tree/1.1.0/ipbes-ndr) in the python virtual environment 3.7 (named “py37”). 

I’ve installed all the required dependencies. However, I got error messages when running the code: pip install "git+https://github.com/richpsharp/ipbes-analysis.git".

The screenshot of the error message is:
![image](https://user-images.githubusercontent.com/58087492/111308991-9ad63a00-8618-11eb-9cfc-98388e325e6b.png)

Also, I installed the “natcap-invest” package in my virtual environment before, using “pip install F:\ natcap.invest-3.8.9-cp37-cp37m-win_amd64.whl”. Will the natcap-invest package affect the installation of setup.py?

Thanks. Any help would be appreciated.
Yuqi

**Comment by phargogh** [comment]
This looks like it's from a different repository, so I'd suggest opening an issue over there.

That being said, if you look at the repository structure, you'll need to:

1. `git clone https://github.com/richpsharp/ipbes-analysis.git`
2. `cd ipbes-analysis`
3. `python setup.py install`

The `setup.py` file is not in the repository root, so you won't be able to use `pip` in the way that you're trying to.

**Comment by yuqi9993** [comment]
> This looks like it's from a different repository, so I'd suggest opening an issue over there.
> 
> That being said, if you look at the repository structure, you'll need to:
> 
> 1. `git clone https://github.com/richpsharp/ipbes-analysis.git`
> 2. `cd ipbes-analysis`
> 3. `python setup.py install`
> 
> The `setup.py` file is not in the repository root, so you won't be able to use `pip` in the way that you're trying to.

Hi Phargogh, thank you so much for your quick reply! May I ask you one more thing?

I did the first two steps, but got errors when doing the third step (python setup.py install). I got errors when "Cythonizing src/ipbes_ndr_analysis/ipbes_ndr_analysis_cython.pyx". Is that because there are something wrong with my setuptools-scm package? (I'm using 5.0.2 setuptools-scm, pypi channel) Thanks!!

The error message is:
![image](https://user-images.githubusercontent.com/58087492/111361585-14871b80-864b-11eb-81ce-42cd26145489.png)

**Comment by yuqi9993** [comment]
> This looks like it's from a different repository, so I'd suggest opening an issue over there.
> 
> That being said, if you look at the repository structure, you'll need to:
> 
> 1. `git clone https://github.com/richpsharp/ipbes-analysis.git`
> 2. `cd ipbes-analysis`
> 3. `python setup.py install`
> 
> The `setup.py` file is not in the repository root, so you won't be able to use `pip` in the way that you're trying to.

Problem solved. Many thanks!!
