### ISSUE TITLE
Question: Exploring the possibility to run the SWY model at a monthly scale

### ISSUE THREAD

**Issue by silviafranceschi** [natcap/invest#527]
Dear all,
I am trying to understand if it is possible to run the SWY model using a different aggregation time scale rather than one year.
As I am using SWY model from an IDE, I can access the source code and, if I correctly understand, there isn't a clear relation/reason to use the year as the aggregation time scale, isn't it?
My problem is that it happens that I have only a some months of data available (let suppose that I have only 100 days of data of P and ETP) then I would like to calculate all the variables (QF, ETP and baseflow) for a basin using only these data at a monthly scale.
Do you think that it would be possible?
Which parts of the code do you think that would have to be changed?

I can see the variable N_MONTHS and this is something that I can easily change (in my case in 3), but my question is, at this point is it enough to provide the data of the 3 months separately as done for 12 months or should I use daily data as input?
And in any case, do you think that from the source code is it possible to create also the aggregated maps of baseflow for each month in order to have the possibility to calculate the discharge (total, average, ...) for a month? I saw some other posts regarding the possibility to extract monthly baseflow from the yearly data but I would prefer to make the software create them directly.

Any help is appreciated...

Thanks in advance

Silvia

**Comment by davemfish** [comment]
Closing this because the same question is posed here: https://community.naturalcapitalproject.org/t/exploring-the-possibility-to-run-the-swy-model-at-a-monthly-scale/1790

And that's a better place to have this conversation. Thanks,
