### ISSUE TITLE
Crop Production Regression missing data?

### ISSUE THREAD

**Issue by emlys** [natcap/invest#549]
The regression model user's guide says it supports 12 crops but only lists 11 (barley, maize, oil palm, potato, rice, rye, soybean, sugar beet, sugar cane, sunflower, and wheat) while the model data has regression tables for just 10 of them (rye is missing). The Mueller et al. paper cited as the source of the regression data has data from 17 crops (the 11 listed above plus cassava, cotton, groundnut, millet, rapeseed, and sorghum). Is some data missing here? At a minimum the user's guide should be corrected.

**Comment by dcdenu4** [comment]
Hey @emlys , this sounds like a conversation I worked out with Rich last year. I'll try to dig it out.

**Comment by dcdenu4** [comment]
Only a few months late on this but... here's the post!

https://community.naturalcapitalproject.org/t/rapseed-regression-yield-table-missing/1438/4?u=dcdenu4

**Comment by emlys** [comment]
Thanks @dcdenu4! So rye is probably the "one other one we dropped too" that Rich mentioned and there should only be 10 crops?

**Comment by dcdenu4** [comment]
Right, I see the following climate regression yield tables shipped with InVEST:

1) barley
2) maize
3) oilpalm
4) potato
5) rice
6) soybean
7) sugarbeet
8) sugarcane
9) sunflower
10) wheat

No rye in there!

**Comment by emlys** [comment]
User's guide has been updated to refer to 10 crops only.
