### ISSUE TITLE
Update to pygeoprocessing 2.2.1

### ISSUE THREAD

**Issue by emlys** [natcap/invest#557]
- [ ] Changes in `distance_to_channel_mfd` are causing it to return some negative values natcap/pygeoprocessing#199. These are almost certainly wrong and are causing NDR tests to fail.
- [ ] Changes in `distance_to_channel_mfd` are causing SDR tests to fail. Aggregate values are different from expected by relative tolerances ~5e-5 - ~5e-6. This is probably ok. Should update the expected values. Wait to do this until the above issue is solved, since it could affect these outputs also.
- [ ] `transform_bounding_box` now raises an error when the transformed bounding box is infinite (meaning there isn't a good transformation from the source to target projection). Should make sure that a helpful message is raised where this could happen:
    - [x] validation
    - [ ] wind energy (@dcdenu4 ?) the test data file `'New_England_US_Aoi.shp` fails validation now
    - [x] both crop production models (@richpsharp I believe wanted to do this?) Edit: because `different_projections_ok is True` for each of these, and they're transformed to WGS84 in the model also, they'll fail validation if this would be a problem.
    - [ ] coastal vulnerability

**Comment by dcdenu4** [comment]
The wind_energy test failing is `test_val_no_grid_land_pts`. The file that seems to be causing the failure is `resampled_global_dem_projected.tif`. Here's what that file looks like:
![image](https://user-images.githubusercontent.com/2659980/119987983-9bce0500-bf93-11eb-9cc2-c6ba01dcc724.png)

**Comment by dcdenu4** [comment]
Create a PR for updating the bad dem data shown above: https://bitbucket.org/natcap/invest-test-data/pull-requests/22/fixing-test-dem-file-for-wind-energy

**Comment by emlys** [comment]
This was done a while back.
