### ISSUE TITLE
Default max pit fill changed to -1 in PyGeoprocessing

### ISSUE THREAD

**Issue by richpsharp** [natcap/invest#560]
The max search flowpath distance in `fill_pits` has been changed to an unlimited flowpath length search. This could affect the outputs of:

* ndr
* sdr
* seasonal_water_yield

Previously there was a max search distance of 500 flowpath pixels, so the test data used for these models would not have been affected by this change.

**Comment by emlys** [comment]
I don't believe we did anything about this when updating to pygeoprocessing 2.3.0. We could retroactively add a note in HISTORY for the 3.9.1 release, but I'm not sure it's worth it.

**Comment by emlys** [comment]
Not worth it.
