### ISSUE TITLE
Translations: Add translation infrastructure

### ISSUE THREAD

**Issue by emlys** [natcap/invest#568]
This will involve:
    - making a way for UI "choose a language" components to communicate the chosen language to invest and reload
        - new endpoint for the workbench
        - ??? for Qt if we do that
    - calling `gettext.translation(...).install()` somewhere (cli.py?) 
    - creating directories in the expected structure to store our translation .po files
    - calling `pybabel compile` as part of the install/build process (converts human-readable .po files to binary .mo files, which are used to look up strings at runtime)

**Comment by dcdenu4** [comment]
I wonder if the choosing the language part should just be upfront in the install process. Maybe that's not doable for our implementation? Or maybe there's examples of other software that let you switch back and forth? I feel like I usually see the language selection once when installing in other applications.

**Comment by emlys** [comment]
This was done in #645
