### ISSUE TITLE
Carbon changes data projections

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#574]
A user from the forums was having an issue running their data on the carbon model. The outputs had a different extent then the inputs going in. Here's the post:

https://community.naturalcapitalproject.org/t/map-extent-of-output-different-from-input/2000/11

I noticed that the raster returned by the model changes the projection from the inputs.

Going in: the projection is: EPSG:22832 - Douala / UTM zone 32N - Projected

Coming out: the projection is: EPSG:3119 - Douala 1948 / AEF west - Projected

**Comment by davemfish** [comment]
We learned that the projection going in is actually deprecated. https://www.spatialreference.org/ref/epsg/douala-utm-zone-32n/

Presumably PROJ is making some decision behind the scenes about what to do there, so I don't think this is an invest bug.
