### ISSUE TITLE
improve error handling in Habitat Quality when nodata is undefined

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#58]
If the nodata value of a threat raster is undefined, but values other than 0 or 1 are present, we crash with: `TypeError: ufunc 'isfinite' not supported for the input types`

Here's an example from a user: https://community.naturalcapitalproject.org/t/typeerror-ufunc-isfinite-in-hq-model/874/2

It would be pretty straightforward to wrap this in a try, except and give clear direction to the user to check their nodata value:

`zero_threat = numpy.isclose(block, threat_nodata)`

**Comment by dcdenu4** [comment]
Assigning to myself because I have plans in the near future to refactor that model.

**Comment by phargogh** [comment]
This also sounds like something we may want to consider checking for in validation as well.

**Comment by dcdenu4** [comment]
[@phargogh @davemfish ] To James's point, should this be a general purpose validation criteria for raster types? Try `get_raster_info` and check *nodata* for *None*?

This obviously would be a separate issue since HQ threat rasters are ambiguous on model start, so would need to be a special add-on for HQ.

**Comment by davemfish** [comment]
That's a good question, @dcdenu4 . I don't know offhand how many models would use a raster validation option of `nodata is not None`. I bet some would. And I bet some models have logic built in to handle rasters with or without defined nodata.

Like you say, regardless of a decision to add to the validation API, a model like HQ that has "hidden" input rasters that are only referenced by other inputs, but are not themselves present in the `ARGS_SPEC`, will need a custom validation function for this.

**Comment by dcdenu4** [comment]
I don't think this issue is relevant anymore after the refactor of Habitat Quality. We changed the way that we handle nodata values, such that threat rasters can have nodata values and `convolve_2d` handles those properly in pygeo 2.0.
