### ISSUE TITLE
CV - accept raster format habitat layers

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#581]
This was requested by @cybersea and it sounds reasonable to me.

In the past it seemed most typical for coastal & marine habitat data to originate in vector format, so that was the primary case we designed for. In recent times, with advances in remote sensing tech, it's increasingly common for original data sources to be rasters.

If we can, could we document some raster-format data sources that users are likely to want to use before we implement this?

**Comment by cybersea** [comment]
GeoTiff seems to be the most predominant format I run across.    Also, potentially ERDAS Imagine (.img), ArcInfo GRID, ASCII Grid, ENVI.    But I think GeoTIFF is by far the most common.

Uh -- or did you mean some example data sources?

- TNC's Carribbean Benthic Habitat Map:  https://caribbeanscienceatlas.tnc.org/
- Mangrove data developed with satellite imagery -- local or global
- Global Mangrove Distribution, Aboveground Biomass, and Canopy Height: https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1665

**Comment by davemfish** [comment]
> Uh -- or did you mean some example data sources?
> 
> * TNC's Carribbean Benthic Habitat Map:  https://caribbeanscienceatlas.tnc.org/
> * Mangrove data developed with satellite imagery -- local or global
> * Global Mangrove Distribution, Aboveground Biomass, and Canopy Height: https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1665

This is what I was after - these are great examples, thanks!

**Comment by davemfish** [comment]
Here's an example of a really problematic vector that was generated from a high-res raster using `gdal.Polygonize`. Cases like this are a good argument for just accepting the raster dataset as input.

![monster](https://user-images.githubusercontent.com/4071255/130684621-989839f6-1ebe-4bf3-a5ad-3fbb61ddcb9d.png)

This is one huge feature with invalid geometries. `coastal_vulnerability.search_for_habitat` valiantly fixes the broken geometry with a `buffer(0)` so that it can do a subsequent `Intersection`, but the buffer takes ~22 minutes on my desktop.

Here's some detail on the invalid geometries. Patterns like this are really common for vector data that was converted from high-res raster.

![detail](https://user-images.githubusercontent.com/4071255/130685013-30435884-ce01-4264-b3e2-4661367ab3b7.png)

So either the user needs to do some painful pre-processing, or needs to wait for for long model runtimes and have plenty of available RAM.

**Comment by davemfish** [comment]
@cybersea is it safe to assume that raster habitat datasets mainly represent one habitat per dataset? Or are they sometimes more like a traditional "LULC" - i.e. a categorical raster with many different habitat types represented in one band?

**Comment by cybersea** [comment]
They could be either.   The benthic habitat layer has multiple classes, more like a typical LULC layer. Although we aren't using all of the classes and we're grouping some of the classes as well.     The mangrove layers would be the one-habitat-per-dataset type.

**Comment by davemfish** [comment]
Fixed by #734
