### ISSUE TITLE
Offer better reporting of GDAL errors when a model crashes

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#59]
Every once in a while we get errors like the the link below from the forums where the model crashes on one exception but the underlying error (which *is* logged to the logfile) actually is that they ran out of disk space.

Maybe we can raise an informative exception if there's an error of sufficient severity?

Or maybe we can report the last few GDAL error codes in the log that might have affected the final exception?

https://community.naturalcapitalproject.org/t/example-data-for-annual-water-yield-model/308/10

**Comment by phargogh** [comment]
@davemfish pointed out that this is definitely related to https://github.com/natcap/invest-gui/issues/3 and it'll probably be best addressed there in the new UI anyways!

**Comment by davemfish** [comment]
Yes, and I believe natcap/invest-gui#3 is already addressed on my fork. If I had a datastack handy to re-create some GDAL errors, I would confirm this is working in the new UI and post a screenshot.

**Comment by phargogh** [comment]
Since this has already been addressed, I'll mark this issue as closed.  Thanks @davemfish !
