### ISSUE TITLE
Updates to Habitat Quality

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#6]
Habitat Quality has been updated a couple of times in the past few years, mostly for pygeoprocessing updates, but it's still largely unchanged.  Even though we might be doing some major work on it in the near future, it'd be good to bring it up to the latest InVEST development standards and also update it to use `taskgraph`.

- [x] Update HQ to use Taskgraph
- [x] Update HQ to use the latest coding standards

**Comment by dcdenu4** [comment]
Refactored and PR'd into release/3.9
