### ISSUE TITLE
Release and update pygeoprocessing 2.3.1?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#613]
Closer to the InVEST 3.9.1 release, let's revisit whether it'd be worth doing a bugfix release of pygeoprocessing (there are currently a few outstanding unreleased changes and at least 1 outstanding PR) and including that in InVEST.  Unlike other PGP releases, there are no major dependency changes between pygeoprocessing 2.3.0 (as referenced in #557) and the current `HEAD` on `main` so this should be merely to include a few bugfixes in InVEST.

**Comment by emlys** [comment]
This has been done and pygeoprocessing 2.3.2 is included in #555.
