### ISSUE TITLE
ui_server: ARGS_SPEC is not JSON serializable

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#617]
Since we added `pint.Unit` types to the `ARGS_SPEC`, the dict as a whole is not JSON serializable, but `ui_server.getspec` expects that it will be. We could either update `ui_server`, or we could start enforcing a contract that `ARGS_SPEC` should always be JSON serializable.

This was caught by the Workbench test suite (`flaskapp.test.js`) so it also begs the question that maybe we should move tests of `ui_server.py` over to `natcap.invest`. That's something we considered when we first moved `ui_server` from `invest-workbench` to `natcap.invest`, and I believe we just decided to wait and see at that point.

**Comment by davemfish** [comment]
Actually, if the `pint.Unit` is the only unserializable type in an ARGS_SPEC, then we can easily deal with that by passing a function to the json serializer like this:

`json.dumps(ARGS_SPEC, default=natcap.invest.spec_utils.format_unit)`

The default function is applied whenever an object would otherwise raise a `TypeError`.

**Comment by emlys** [comment]
This was resolved in #623.
