### ISSUE TITLE
GLOBIO infrastructure can only be .tif or .shp

### ISSUE THREAD

**Issue by emlys** [natcap/invest#632]
GLOBIO only uses files in the infrastructure directory [if they end with .tif or .shp](https://github.com/natcap/invest/blob/main/src/natcap/invest/globio.py#L993-L1022). Ideally it would accept any gdal-supported raster or vector format.

**Comment by phargogh** [comment]
Neat!  Yes, ideally this should accept any raster or vector and handle it appropriately.  I'm curious if this restriction is part of the GLOBIO specification.

But also, before we dive into this, I think I remember Becky saying that she would check with the UN folks (who developed the GLOBIO model) and see if what they have is better/sufficient and that the InVEST implementation might be worth deprecating.

@beckyck do you have any thoughts about GLOBIO here?  Thanks in advance!

**Comment by emlys** [comment]
Closing because GLOBIO will be deprecated in the next minor release.
