### ISSUE TITLE
Urban Cooling model sample data might break with GDAL 3.3.0

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#637]
A user reported an error (#635) when running the Urban Cooling model with sample data using GDAL 3.3.0. It was related to invalid geometries, though QGIS reported no invalid geoms for the sample data for Urban Cooling. The user could also have been using other data than the sample data since QGIS doesn't show any invalid geoms in the sample data. Still worth checking out though when we eventually test GDAL 3.3.0+

Should try running this model locally with a GDAL 3.3.0 environment.

**Comment by emlys** [comment]
This could be related to the `bytes()` thing changed in #555, though I'd expect it to raise a different error if that was the problem. That was the only change needed for Urban Cooling and the tests are passing there with gdal 3.3.1.

**Comment by emlys** [comment]
Since the 3.9.1 release is out and includes GDAL 3.3.1, and `invest-autotest` was passing, I think we can close this
