### ISSUE TITLE
InVEST Readme could use a refresh

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#670]
From this discussion, https://github.com/natcap/cookbook/pull/1#issuecomment-929720320, it seems like there is consensus that the InVEST Readme could use a bit of a review and overhaul.

**Comment by dcdenu4** [comment]
It's not clear to me the benefit of having these separated. I also realize that we don't provide any upfront info that points to the latest installers and using the GUI.

**Comment by emlys** [comment]
I realized that `README_PYTHON.rst` is referenced in setup.py/pyproject.toml - it's the text that shows up on our PyPI page. So maybe it does make sense to keep them separate.

**Comment by davemfish** [comment]
### Building Python Packages

This section is not really in line with how most of us do this in practice: 

`pip install .`

**Comment by emilyanndavis** [comment]
It would be worth making sure we have documentation around how InVEST talks to sub-repos (sample data, user guide, etc.) and how/when to update revision refs in the Makefile.
