### ISSUE TITLE
Test against Python 3.10

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#672]
Python 3.10 us supposed to be released today (Oct 4, 2021) so let's make sure everything is working as expected.

**Comment by phargogh** [comment]
I just recently saw that `conda-forge` was starting to roll out support for python 3.10 and it looks like our big dependencies (GDAL, especially) do now have 3.10 available on conda-forge.

**Comment by emlys** [comment]
`distutils` is being deprecated in 3.10, to be removed in 3.12. We reference `distutils` in `exe/invest.spec` and `src/natcap/invest/scenic_quality/viewshed.pyx`.

**Comment by phargogh** [comment]
Sounds good, then this PR should also try removing those references! Hopefully the pyinstaller binaries doesn't really need `distutils`.

**Comment by phargogh** [comment]
Pygeoprocessing hasn't yet been tested against python 3.10, so I've got that running in the background here.  This issue here should probably wait until we're confident that pygeoprocessing doesn't need any major changes to work with python 3.10 (or a pygeoprocessing release is issued if it does).

**Comment by phargogh** [comment]
On hold until https://github.com/natcap/pygeoprocessing/pull/231 is complete.

**Comment by emlys** [comment]
Removing on hold label because natcap/pygeoprocessing#231 was merged.

**Comment by phargogh** [comment]
Let's be sure to update the trove classifiers in setup.py to reflect the currently-supported python versions (all of them).

**Comment by emlys** [comment]
In `pyproject.toml` `build-system.requires`, we use `numpy==1.21.2` for python 3.10. We should bump this to 1.21.3 which is the earliest version that officially supports 3.10. 1.21.2 did not have wheels for all OS's for python 3.10. It ends up building from source.
