### ISSUE TITLE
DelineateIt UI took several minutes to appear on Mac

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#695]
From Stacie via Slack:

>Random minor weirdness encountered in the Stanford InVEST class this week: For several students (but not everybody) using Macs, the DelineateIt UI took several minutes to appear after they launched the tool. This didn't happen to those same students with Carbon or SDR, which we ran in previous weeks. Nothing probably needs to be done about this, just reporting for the record.

**Comment by emlys** [comment]
Closing because we deprecated the QT interface!
