### ISSUE TITLE
invest processes should always announce the file they log to

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#709]
`utils.prepare_workspace` creates the user's model workspace and sets up of the logging FileHandler. It announces where it's logging to like this: `LOGGER.info('Writing log messages to %s', logfile)`

I propose to just move this to a level `100` message so that it cannot be filtered out by a user choosing a higher logging level than `INFO`. 

The use-case is the Workbench, where the parent process of invest needs to be told the logfile path. So that message needs to always come through stdout.

**Comment by phargogh** [comment]
Looks like this was addressed in #710
