### ISSUE TITLE
Add logging.basicConfig() to UI-generated python scripts

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#71]
Since we use python's `logging` for progress logging, I think it would be useful to include logging output in the python script generated by the UI on request through the "Development" menu.

I think this should just be a matter of:
```python
import logging
logging.basicConfig(level=logging.INFO)
LOGGER = logging.getLogger(__name__)
```

**Comment by dcdenu4** [comment]
Oh interesting, that does seem very useful.
