### ISSUE TITLE
Final decision on name of new Stormwater model

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#715]
It's possible we already have a decision on this from all the interested parties. But in case not, here's a reminder to do that before the `3.10` release.

Right now we have the user-facing model title as "Stormwater". If we stick with that, what about making it "Urban Stormwater"? 

Perhaps redundant, but it's kind of nice if all the urban models have the "Urban" prefix; it keeps them together in an alphabetized list in the launcher & workbench.

**Comment by emlys** [comment]
Have emailed Perrine and Ben about this specifically, suggesting "Urban Stormwater".

**Comment by emlys** [comment]
It seems that we've settled on "Urban Stormwater Retention". This clarifies that it's an urban model. "stormwater retention" is the ecosystem service being modeled whereas "stormwater" is not. The timescale issue is not addressed ("storm" implies a single event, but the model is annual), but it's made clear in the user's guide.

**Comment by davemfish** [comment]
Fixed in #766
