### ISSUE TITLE
Start menu model names differ from "model_title" 

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#718]
We recently created `natcap.invest.MODEL_METADATA` as the single source of truth for all the different invest model names. And the `model_title` is the meant to be the user-facing name. It appears in the Mac launcher, in the header of the Qt window (Windows & Mac), and in the Workbench.

One thing we missed is the Windows Start menu shortcut names, which are hardcoded in the NSIS script. At a glance, these models have start menu names different than the `model_title`, so we could update them:

| Start Menu | model_title |
|-------------|--------------|
**Scenic Quality** | Unobstructed Views: Scenic Quality Provision
Water Yield | **Annual Water Yield**
Pollination | **Crop Pollination**
Recreation | **Visitation: Recreation and Tourism**
**Urban Stormwater Retention** Model | Stormwater

I bolded the names that I personally prefer, so I would consider changing those `model_title` as needed also. Would anyone else like to weigh in?

**Comment by dcdenu4** [comment]
Would it be worth reaching out to Lisa or another science lead to make sure any changes we make to the names are adequate? From recently working on the global viewer there were instances where data product naming ended up being important to certain groups. I guess I'd want to make sure if we change names in a big way that those names weren't deliberately chosen for a reason.

**Comment by phargogh** [comment]
Yeah, it'd be worth reaching out to the science/model leads about this.

Personally, I agree with the ones that you liked, @davemfish.  For pollination, I'd go with "Crop Pollination" since it's pretty clearly about agriculture (the UG chapter is titled "Pollinator Abundance: Crop Pollination", which is probably the most precise option).  Eric Lonsdorf and Lisa would be good folks to check with for that model

**Comment by davemfish** [comment]
We'll update the four models (not Stormwater) in this issue with the name bolded in the table at the top. Stormwater we'll wait for issue #715

**Comment by davemfish** [comment]
Fixed in #753
