### ISSUE TITLE
deprecate Fisheries & Finfish models

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#719]
The PSC recently approved a PEP to deprecate these models in an upcoming release. In practice I believe it means removing the following modules:

- `natcap.invest.fisheries`
- `natcap.invest.finfish_aquaculture`
- `natcap.invest.reporting`
- `natcap.invest.ui.fisheries`
- `natcap.invest.ui.finfish`

For now I'll tag this with the `3.10` milestone, but we can discuss the appropriate timeline for doing this. It might be nice to have at least one release prior to acting on this where we can insert deprecation warnings.

**Comment by emlys** [comment]
Hooray! `test_cli.py` also uses the fisheries model, we can switch that to any other model.

**Comment by davemfish** [comment]
Remove the model's source code

- [ ] git rm the model's source code from src/natcap/invest/
- [ ] git rm the model's tests from tests/
- [ ] git rm the model's UI file from src/natcap/invest/ui
- [ ] git rm any related sections/pages from the InVEST API documentation at doc/api-docs
- [ ] Edit the _MODEL_UIS dict in src/natcap/invest/cli.py to remove the model's define entrypoints.

- [ ] Remove the model from setup.py (not all models will need this)
- [ ] Update the tests
- [ ] git rm any test files and/or classes associated with the model
- [ ] git rm any test data from invest-test-data repository and update Makefile with the new git rev.
- [ ] Make sure the remaining tests run through!

Remove the model from the InVEST distribution
Update the sample data repository at data/invest-data:

- [ ] Remove the model's directory from the repo.
- [ ] Remove the model's entry from the ZIPDIRS list in Makefile if needed.
- [ ] Update the Makefile with the new git revision.
- [ ] Remove any start menu links from the installer at installer/windows/invest_installer.nsi
- [ ] Remove the model's datastack entry/entries from scripts/invest-autotest.py
- [ ] Remove the user's guide chapter from the User's Guide repository and update the User's Guide revision in the Makefile accordingly.
- [ ] Update HISTORY.rst to note the change.
- [ ] Build the binaries to verify that everything builds correctly.
- [ ] Do a pull request on all this!

When the source code is all set and PRed in,

- [ ] Update the deprecated models page http://data.naturalcapitalproject.org/invest-releases/deprecated_models.html to link to the last full release with this model.
- [ ] Email Lori (as training coordinator) and Sarah (as communications manager) with the deprecations

**Comment by emlys** [comment]
Done in #748 .

**Comment by emlys** [comment]
Whoops, just remembered you said to keep this open!

**Comment by davemfish** [comment]
Done!
