### ISSUE TITLE
HRA failing on valid projections

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#79]
I wanted to start documenting an issue a user was having from the forums here:

https://community.naturalcapitalproject.org/t/habitat-risk-assessment-output-error-visualization-fails/926/2

Given the users input there was something about the projections of the AOI and habitat and stressor layers that were causing any downstream created raster to have a bad projection. I did  a quick fix for the user by projecting all of the users input to : *EPSG:32724
WGS 84 / UTM zone 24S*.

This might warrant further investigation to ensure that there is not a bug.

**Comment by phargogh** [comment]
@dcdenu4 do you recall how the original datasets were projected?  Some popular projections (I'm thinking of Web Mercator in particular) are poorly-supported by GDAL, and I'm just wondering if we should be aware of any other problematic projections.

Hopefully the upgrade to PROJ6 in GDAL3 will ultimately fix this!

**Comment by dcdenu4** [comment]
Just pulled them up. Here were the original projections going in:
**AOI**: *EPSG:31984 - SIRGAS 2000 / UTM zone 24S - Projected*
**Stressros**: *EPSG:4326 - WGS 84 - Geographic*
**Habitat**: *EPSG:4674 - SIRGAS 2000 - Geographic*

Honestly, seeing that Habitat projection makes me skeptical... Though I do feel like I first tried projecting this only and still had issues...

But yea, GDAL3 and PROJ6 should definitely help with these issues, especially if there are instances where always going through WGS84 is not necessary.

**Comment by phargogh** [comment]
Hmm, well, none of those _look_ like projections that GDAL doesn't handle well, but maybe we're not handling something correctly within HRA?  Curious.  I'm glad there's a workaround.

**Comment by dcdenu4** [comment]
If possible check if this is still an issue when GDAL 3.0 is PR'd into release 3.9 branch.

**Comment by dcdenu4** [comment]
Working on this in my fork under branch: `bugfix/hra-failing-on-valid-projection`

**Comment by dcdenu4** [comment]
I think the issue with this user's input was that the AOI was projected in meters but the habitat and stressor vectors were projected in degrees. The model uses the AOI to determine `target_pixel_size` based on the input `resolution`. So if AOI is in meters with a `1000` resolution, then the `target_pixel_size` is `1000`. This would be problematic when `rasterizing` the non projected vectors because `1000` degrees doesn't make sense.

**Comment by dcdenu4** [comment]
My take away from this issue is that the HRA User's Guide provides no guidance on projections for the AOI, Stressors, or Habitat inputs. There should be a note mentioning they should be in the same projection. Or the model should handle different projections.

**Comment by dcdenu4** [comment]
It looks like all spatial inputs should be projected in meters because other input to this model is in meters. Should there be an early validation check in the model that ensures all spatial inputs are projected?

**Comment by phargogh** [comment]
Well, we used to require that everyone have their inputs in the same projection (and sometimes also projected in a certain linear unit like m), but since then we've started to have a number of models reproject inputs as needed.  In SDR and SQ, for example, we we reproject spatial inputs to the spatial reference of the DEM.  In a few others, we reproject to the spatial reference of the LULC.

Between these two options (validation vs. reprojection), is there one that makes better sense for HRA?  Is there a compelling argument for or against the model handling different projections?

**Comment by dcdenu4** [comment]
I just spent some time digging around HRA. It looks like the model does heavily depend on calling `GetLinearUnits` for adjusting inputs of meters (resolution, buffer size) to spatial inputs units (which could be meters, feet, etc.). However, this is only relevant if spatial inputs are projected, because `GetLinearUnits` implies meters, feet, etc. but not degrees, which is Angular units. So the way the model was written, it's clear to me the intent was to have the inputs be *Projected*. Thus I think that validating inputs are Projected seems reasonable. The other option is of course to handle projecting Geographic inputs up front, which would require a refactor.

The reason I'd present for NOT handling geographic projections is because the model deals with distance calculations and inputs over linear space. So it makes sense the inputs should be in linear units... Not a very strong argument since other InVEST models reproject inputs to an AOI or DEM that is required to be projected in linear units. From a developer perspective, there is a larger time cost to implementing Geographic -> Projected, then there is for validating / providing an error message for a unProjected input.

Something needs to be done either way, because currently `GetLinearUnits` on a Geographic input returns `1.0`, even though it's Geographic and not Projected in linear units. This could lead to major unwanted side effects.


Linear Unit Inputs:

Resolution:
>The grid cell size, in meters, that is desired for the analysis. This must be a whole number. The model will convert any vector-based habitat and stressor inputs into rasters with pixel width and height equal to this value.

Buffer:
>The desired buffer distance (meters) to be used to expand a given stressor’s influence, or footprint

**Comment by dcdenu4** [comment]
Note, I updated the users guide to mention that the habitat, stressor, and AOI spatial inputs should be projected. As that is what the model currently expects, as I interpret it.

**Comment by phargogh** [comment]
Sounds fine to me!  As far as I can tell, there hasn't been a huge or notable demand for reprojection as part of the model run.

Since we're including this note in the UG, could we add a check for this in validation and/or something upfront during model execution if it isn't there already?

**Comment by dcdenu4** [comment]
That sounds good James:

- [ ] During processing of the Habitat / Stressor inputs, error if they are not projected and in geographic format. ( Note, the model already errors if AOI is not projected ).

**Comment by dcdenu4** [comment]
There are some more updates on this. There is a test in `test_hra.py` called `test_layer_no_projection`. This test checks that habitats and stressors without projections raises a `ValueError`. Those test inputs are created in `_make_simple_vector` function where setting the projection itself is entirely skipped:
```python
srs = osr.SpatialReference()
if projected:
    srs.ImportFromEPSG(EPSG_CODE)
```
Similarly in `hra.py` there is a function `_label_linear_unit` that checks if this projection is missing and raises that `ValueError`
```python
if not spat_ref:
    raise ValueError()
```
Is it possible this actually wants to test for Geographic vs Projected? OR is it actually just wanting to check against the spatial reference missing completely?

**Comment by phargogh** [comment]
From what you describe, it sounds like the model and tests are only checking for whether a spatial reference is present, not whether the coordinate system is geographic or projected, and that sounds like different behavior from what we would expect!  Isn't everything required to be in a projected coordinate system with linear units?
