### ISSUE TITLE
numpy 1.22 compatibility

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#796]
numpy 1.22 was released a few days ago and it seems to be causing a couple issues.

1. Build failures: `No module named numpy.distutils`
2. Test failure: `test_carbon_totals_precision` fails with a value outside the numerical tolerance

https://github.com/davemfish/invest/actions/runs/1649577411

**Comment by davemfish** [comment]
It looks like the build issue is already fixed in pyinstaller, but not yet released. https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-numpy.py#L53

**Comment by dcdenu4** [comment]
Would it make sense to cap numpy requirements to <1.22 for now, until the Pyinstaller release with this fix comes out?

**Comment by davemfish** [comment]
The test failure is due to a bugfix in RNG https://github.com/numpy/numpy/pull/20314

I verified this by observing that the random floats generated in our test do differ slightly under the different numpy versions. So I will update our regression value.

**Comment by davemfish** [comment]
> Would it make sense to cap numpy requirements to <1.22 for now, until the Pyinstaller release with this fix comes out?

I think it's either this or inject our own numpy hook for pyinstaller, only to remove it later. So I agree it probably makes sense to cap numpy or perhaps try installing Pyinstaller's `develop` branch?

**Comment by phargogh** [comment]
Because the pyinstaller `develop` branch is a moving target (and the branch can sometimes introduce issues), I'd suggest either installing pyinstaller to a specific revision on their `develop` branch (the latest is probably fine) or capping the numpy version.  I'd worry that installing from the pyinstaller `develop` might leave us vulnerable to broken builds.

**Comment by davemfish** [comment]
Okay, we'll restrict numpy for now. And then move this issue to `3.10.1` to update the test so it passes with numpy `1.22`, and also to watch for the Pyinstaller release.
