### ISSUE TITLE
Consistently and helpfully handle reclassification errors across InVEST

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#8]
Despite how common reclassifications are across InVEST, we don't handle errors very consistently.  If a model's biophysical table is missing a row and that landcover code is encountered, either a `KeyError` is raised, or else there's a cryptic error coming from numpy about bins.

If there's an issue around reclassifications, InVEST should consistently and helpfully handle errors like these by raising a human-readable error message that contains enough information for a GIS person to decipher the source of the issue.  Stacie Wolny specifically referenced the error message at https://bitbucket.org/natcap/invest/src/13fa555b96402d9b463aa524b170de01c046a7bf/src/natcap/invest/ndr/ndr.py#lines-931 as being clear and helpful.

**Comment by dcdenu4** [comment]
Switching to `on hold` status because we're still talking through the best approaches. Currently see this issue: https://github.com/natcap/pygeoprocessing/issues/105

**Comment by dcdenu4** [comment]
Uses of `reclassify_rasters` are found in the following models which could use a more helpful message:

- [ ] carbon.py
- [ ] crop_production_percentile.py
- [ ] crop_production_regression.py
- [ ] forest_carbon_edge_effect.,py
- [ ] globio.py
- [ ] habitat_quality.py
- [ ] hydropower_water_yield.py
- [ ] pollination.py
- [ ] sdr.py
- [ ] seasonal_water_yield.py
- [ ] urban_cooling_model.py

**Comment by dcdenu4** [comment]
habitat quality does LULC code and table checking up front so it's not necessary to add redundancy around `reclassify_raster` function.

**Comment by dcdenu4** [comment]
After attempting to implement handling of reclassification issues in multiple models I'm now wondering if the best approach is to do what habitat quality does and handle everything up front. Not necessarily in validation, but early on when the CSV tables are read in. Something like:

1) Read in CSV tables
2) Call utils function for checking unique raster values against lookup dictionary.

We have a lot of models that say something similar in the *Data Needs* section:
>All values in this raster MUST have corresponding entries in the Land Cover Biophysical Table

I'm leaning to thinking that these input errors are common enough that they could warrant explicit checking.

**Comment by dcdenu4** [comment]
Currently working through this issue in a PR draft https://github.com/natcap/invest/pull/260

**Comment by dcdenu4** [comment]
This was handled in PR #287
