### ISSUE TITLE
Urban Stormwater missing sampledata & autotest

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#808]
We forgot to include this model's sample data dir in the Makefile's list of zipdirs, and in the NSIS script's list of dirs. So the data is not available from the Windows installer or from our website's "Download individual sample data" link.

We also forgot to add this model to `invest-autotest.py`, otherwise that would have caught the missing data. Did we miss anything else?

And can we remove the `storm_impact` dir from the sampledata? I'm not sure if that was an earlier version of this model's data?

**Comment by davemfish** [comment]
I'm doing this to be merged into the `release/3.10` branch

**Comment by phargogh** [comment]
@davemfish I just created https://bitbucket.org/natcap/invest-sample-data/pull-requests/24/remove-deprecated-model-sample-data-from for removing the storm_impact and Malaria models from the sample data, neither of which are in InVEST any longer.  No need to rush to include this deletion in 3.10.1.

**Comment by davemfish** [comment]
Fixed in #809
