### ISSUE TITLE
Expose a setting for Taskgraph's logging level

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#852]
We offer this in Qt; the ability to set the Taskgraph loggingLevel separately from all other loggers, because DEBUG logging from Taskgraph is so noisy.

**Comment by phargogh** [comment]
We mentioned on the team call this morning that we might look to add a flask endpoint to configure the taskgraph logging level.

I'm not necessarily advocating for this configuration approach, but it is possible for us to define a JSON-like object with which to configure logging, through [`logging.config.dictConfig`](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig).  Just wanted to share that as a possible option in case it would be helpful for us.

**Comment by phargogh** [comment]
Ah, I misunderstood that this was for the InVEST model CLI and not the flask process.  Even so, this dict style of configuration (maybe through a file) might be handy if we ever needed to offer finer-grained logging controls.
