### ISSUE TITLE
Validation of HQ input flaky

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#853]
I was using the workbench beta to run HQ for a forum user question. When putting 0.5 into the half saturation constant input it remained "red" with the error message. I tried clicking other inputs to get it to "register". I finally got it to validate after changing the value in that input three or four times.

- [ ] Try to reproduce problem and record steps

**Comment by davemfish** [comment]
on hold until it's reproduced

**Comment by davemfish** [comment]
@dcdenu4 has this reproduced lately?

**Comment by dcdenu4** [comment]
Thanks for the reminder, I'll test it out with a recent dev build.

**Comment by dcdenu4** [comment]
I'm no longer experiencing this issue.
