### ISSUE TITLE
Display more details from ARGS_SPEC

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#854]
The latest iteration of an invest `ARGS_SPEC` has lots of useful info we're not yet displaying to the user.

We already have an open issues for displaying units natcap/invest#867 

We can also display the nested specs that define required columns/fields for csv and vector inputs.

As of PRs like https://github.com/natcap/invest/pull/633 and https://github.com/natcap/invest/pull/639 a lot of details that used to be in  an args "about" property has moved into those nested specs for columns or fields.

So we could consider formatting & rendering all that. Or if that feels too redundant with the User's Guide where we're already doing that formatting, we could consider including a hyperlink to the specific arg description in the UG.

**Comment by emlys** [comment]
I'm concerned that displaying nested info, especially ones that could contain recursively nested args such as CSVs, would get too complicated and redundant with the user's guide. How about just displaying the "about" text and units in a tooltip, along with a link to the corresponding bullet point in the user's guide?

Info about table structure, etc. might not be so useful to display right in the UI anyway. If someone's file is incorrect, that's not something they can fix in the UI. They'll need to open another program to edit it. Assume they want to look at the arg spec info alongside excel or QGIS. Then it's probably easier to see in the user's guide (where it would be larger and better formatted, and expands to fill the window size).

I'd propose we add RST anchors to each arg bullet point in the user's guide using a standard format like `<model>-<arg key>`. For instance the carbon model's `lulc_cur_path` arg would have an anchor `.. _carbon-lulc-cur-path:`. Then you can link there in the HTML with `carbonstorage.html#carbon-lulc-cur-path`.
