### ISSUE TITLE
Dealing with overflow in text input fields

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#855]
Input text fields should default to display the right-most end of their text content when they contain text that is too long to display completely. That way the more important part of the filepaths is always visible. 

Inputs should also not scroll automatically in either direction when a user moves focus off of the input.

**Comment by newtpatrol** [comment]
Thanks for working on this Dave! Apologies for not looking for an existing issue on it before posting a new one.

**Comment by davemfish** [comment]
> Apologies for not looking for an existing issue on it before posting a new one.

Probably most efficient to just make a new one anyway. Plus now there's some extra motivation to move this up the priority list.
