### ISSUE TITLE
Add a wait indicator on model inputs launch?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#868]
* Mac OS X 11
* Using mac artifact at https://pipelines.actions.githubusercontent.com/F4lHndai5pNrgEJlI2njzHq5AUtQLlP3jKt2FbnX1yv7QGCERr/_apis/pipelines/1/runs/471/signedartifactscontent?artifactName=invest-workbench-macos-latest&urlExpires=2021-02-16T18%3A23%3A52.4312404Z&urlSigningMethod=HMACV1&urlSignature=ADWtdCgV0fDVy4oh1o5gZyvHaHckMSnpG1eXXnYLNpI%3D

When I launch the application, the window launches great, and the model list is presented as expected.  I then launched `DelineateIt` from a prior run (this might not matter) and Mac OS needed to prompt me to confirm that I want to grant access to this directory.  The thing is, it was about 20-30 seconds before the OS permissions dialog was presented, and in that time there was nothing to indicate that the application was hanging.  Clearly the event loop is running, but the model inputs list wasn't showing up at all.

Maybe it'd be worth adding a spinner or other indicator to show that something is happening in the background on model launch?

**Comment by davemfish** [comment]
Closing this since we haven't heard any other reports of a delayed response opening models.
