### ISSUE TITLE
Publish for linux as a snap?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#871]
Looking through the `electron-builder` documentation, it looks like the `snap` format is supported.  If this is the case, maybe we could address natcap/invest#121 as a feature of the electron-build process?

**Comment by davemfish** [comment]
I don't think this is on our roadmap, so I'm closing it for now.

**Comment by davemfish** [comment]
We received an inquiry about this recently: https://community.naturalcapitalalliance.org/t/invest-workbench-for-linux/6406/2

As the Workbench has seen enhancements over the years (Plugins, Reports, DataHub Integration) its functionality has expanded beyond just running invest models, and so there are increasingly more reasons why someone would choose the Workbench over the `natcap.invest` Python interface. In particular, if we want Linux users to develop plugins, we might need to provide them with Workbench builds.

Of course, there are significant costs to testing and maintaining builds for a third platform.
