### ISSUE TITLE
**spec_utils.ET0 overriding already-defined attributes

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#894]
In Seasonal Water Yield, we have a case where we're using the standard ET0 information dict from `spec_utils` like so:

```python
ARGS_SPEC = {
    ...
        "[MONTH]": {
            "about": _(
                "Twelve files, one for each month. File names must "
                "end with the month number (1-12)."),
        **spec_utils.ETO
    }
```

Which results in `ARGS_SPEC['args]['ET0_dir']['[MONTH]']['about'] == 'Map of evapotranspiration values.'`, where `'Map of evapotranspiration values'` is being pulled from `spec_utils.ET0['about']`.

This differs from our original assumption about the behavior of the `**kwargs` syntax, but it turns out is, in fact [what python does per the docs](https://docs.python.org/3/library/stdtypes.html#dict):

> If keyword arguments are given, the keyword arguments and their values are added to the dictionary created from the positional argument. If a key being added is already present, the value from the keyword argument replaces the value from the positional argument.

This came up as the result of a [forums question](https://community.naturalcapitalproject.org/t/error-running-model-valueerror-no-precip-found-for-month-1/2529).

This is probably an issue in other places where we use `**spec_utils` as well.

**Comment by emlys** [comment]
whoops, sorry about that! yes, I think anything from `spec_utils` should always go first in the dictionary.
