### ISSUE TITLE
Auto-PR into release branches fails when there are no release branches

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#898]
When we merge a PR into main, the workflow at `workflows/auto-pr-from-main-into-releases.yml` is executed in order to open up PRs to merge the changes just merged into main into each open release branch.  It turns out that if there are no release branches (as we have now), then the workflow fails.  This should be fixed so that the workflow just exits gracefully, without a failure, since this is a perfectly acceptable repo state to be in.

Example failure: https://github.com/natcap/invest/runs/5487825466?check_suite_focus=true

**Comment by emlys** [comment]
This was fixed by #899.
