### ISSUE TITLE
SDR tests are failing with gdal=3.4.2

### ISSUE THREAD

**Issue by emlys** [natcap/invest#905]
Three SDR tests are failing on github actions:
```
test_base_regression: AssertionError: these key (actual/expected) errors occured: {'usle_tot': (13.90210914612, 14.25030517578), 'sed_export': (0.55185163021, 0.60502111912), 'sed_dep': (8.80612564087, 9.05251502991)}

test_drainage_regression: AssertionError: these key (actual/expected) errors occured: {'sed_export': (0.97192692757, 1.02959537506), 'usle_tot': (12.68887424469, 12.97211265564)}

test_regression_with_undefined_nodata: AssertionError: these key (actual/expected) errors occured: {'sed_export': (0.55185163021, 0.60502111912), 'usle_tot': (13.90210914612, 14.25030517578)}
```
These passed when I ran them locally. Possibly an updated dependency?

**Comment by emlys** [comment]
Confirmed that the tests fail with GDAL 3.4.2 and pass with 3.4.1. The differences are larger than I'd like to attribute to floating point imprecision.

**Comment by emlys** [comment]
The difference is coming from a change in the aligned LULC raster. Something in the alignment process must have changed. 
Original LULC:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/43770515/161343659-de0a60a5-dcf5-4581-9b8b-51d03dcb0ba3.png">
Aligned LULC using GDAL 3.4.1:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/43770515/161343795-57796cf8-1526-4988-b142-c15bea3f9701.png">
Aligned LULC using GDAL 3.4.2:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/43770515/161343947-8cf01cfe-0677-4c33-80f1-768f39535333.png">

The 3.4.2 version actually looks a lot more accurate (maybe identical) to the original. In the 3.4.1 version lots of pixels are switched to LULC class 2 (gray).

**Comment by emlys** [comment]
This comes down to [this undocumented change](https://github.com/OSGeo/gdal/commit/db9ea60631eda5ef881ae75dc3355f42734fb38c) released in 3.4.2. From what I can tell, nearest neighbor is being used instead of `mode`, because of the new setting `GDAL_WARP_USE_TRANSLATION_OPTIM` that defaults to `YES`. In this particular SDR case, the warp operation is just translating along pixel boundaries (?). And because of that, it's being "optimized" to use `near` instead of `mode`.

The `near` result is way more accurate to the original. We use `near` a lot in invest and `mode` for just a few (SDR: LULC, Urban Cooling: LULC, Urban Flood: LULC and soil groups). I don't know why `mode` was chosen over `near` for these, and I don't know if it really matters.

However, `near` is definitely _not_ what we want for resampling DEMs, etc. It kind of seems like a mistake that GDAL now silently ignores your selecting warping algorithm. 

I think next steps are:
* Set `GDAL_WARP_USE_TRANSLATION_OPTIM=NO` to restore the old behavior (does this have to be set as an env variable? would be nice to keep it isolated to invest)
* Consider using `near` instead of `mode`, since it gives way more accurate results at least in this one case
* Possibly get clarification from GDAL developers about the intent of this change

**Comment by emlys** [comment]
> If they don't use these options in any other cases, then maybe we don't need to make any changes?

That would probably be fine if we can confirm that. I'm struggling to understand the source code and see when it applies. I created an issue on osgeo/gdal asking about it.

**Comment by dcdenu4** [comment]
Here's the ticket: https://github.com/OSGeo/gdal/issues/5578!

**Comment by emlys** [comment]
Pinning GDAL<3.4.2 as a temporary fix until we have a better understanding of what the changes in 3.4.2 do.

**Comment by davemfish** [comment]
It seems there are DLL import issues with version `3.4.1`, so the resolution now is `gdal<3.4.1`.

And once we have consensus that the changes in gdal `3.4.2` are there to stay, we can update SDR regression data to accommodate them.
