### ISSUE TITLE
Make delineateit create watersheds with a ws_id column

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#908]
When watersheds are created in delineateit, they have the feature attribute `ID` to indicate the watershed ID.  For consistency with our routed models which use `ws_id` as their watershed ID fieldnames, it would be nice to just use the `ws_id` fieldname instead.

[This came up on the forums recently](https://community.naturalcapitalproject.org/t/questions-about-running-delineatelt/2577/8?u=jdouglass), where a user didn't know to rename the column from delineateit.

**Comment by emlys** [comment]
Thanks for making this issue @phargogh! I did notice that `pygeoprocessing.routing.delineate_watersheds_d8` seems to create a `ws_id` field. Not sure why that doesn't make it to the delineateit output. (https://github.com/natcap/pygeoprocessing/blob/77388fb239f47a1cb4e3fba8aaec7d304f80c4c5/src/pygeoprocessing/routing/watershed.pyx#L724)

**Comment by phargogh** [comment]
OH: https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/routing/watershed.pyx#L994

Looks like we copy over all of the attributes from the source geometry _except_ one called `ws_id`.  So this is probably a bug in pygeoprocessing, then, and not in delineateit, since we should be allowing features to have attributes of any name and then allow delineateit to assign a `ws_id` field.

**Comment by phargogh** [comment]
I've got a few minutes here, so I'll take a look at this and see if I can get a PR together for you to review over in pygeoprocessing @emlys
