### ISSUE TITLE
[Proposal, RFC] Separate requirements from constraints

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#916]
# The Problem

This came up while working on #880. 

We have long struggled with how best to define the packages that are required for InVEST's execution under various circumstances, and we have been simply defining everything in `requirements.txt`.  The result of this is that `natcap.invest` now has much stricter-than-actually-necessary requirements, which could limit someone's ability to install, say, on `debian:stable`, due to a restriction in place for a `Windows` build.

## Use Case: Installing `natcap.invest` as a library

When someone wants to install `natcap.invest` in a development environment, we should assume that the user has a deep technical understanding of their system and are able to meet the functional requirements needed in order to run `natcap.invest`.  So long as we are clear about the package versions needed to use `natcap.invest`, we should let the user make sure that they are installed correctly.

The packages required for a user on `debian:stable` should not be determined by a build issue on Windows.

## Use Case: Building InVEST binaries

When building InVEST binaries, we are at the whim of package maintainers elsewhere and their CI systems that may release buggy, ill-compiled, or incomplete binary builds.  When we discover those issues for a particular package and platform, we should be able to exclude that package for that platform, or else exclude that package version altogether, without inhibiting a technical user from being able to install whatever dependency versions they want.

## Use Case: `conda install -c conda-forge natcap.invest`

Our [`conda-forge` package's requirements definition](https://github.com/conda-forge/natcap.invest-feedstock/blob/main/recipe/meta.yaml) is a mildly-updated version of our package requirements.  Like with the `natcap.invest` library use case, we should assume that `conda-forge` is catching build issues in the CI process and not uploading faulty packages, so this requirements list should be _functional_ requirements as in `requirements.txt`. 

# Proposed Solution: add a `pip` constraints file

`pip` has 2 forms of requirement specifications:

* `requirements.txt`, which lists functional package requirements.  Packages in this list must be installed.
* `constraints.txt`, which lists any constraints on packages.  Constraints listed apply to packages being installed through `requirements.txt`.

So, InVEST's `requirements.txt` would look like:

```diff
-GDAL>=3.1.2,!=3.3.0  # 3.3.0 had a bug that broke our windows builds: https://github.com/OSGeo/gdal/issues/3898
+GDAL>=3.1.2
 Pyro4==4.77  # pip-only
 pandas>=1.2.1
-numpy>=1.11.0,!=1.16.0
-Rtree>=0.8.2,!=0.9.1
+numpy>=1.11.0
+Rtree>=0.8.2
 Shapely>=1.7.1,<2.0.0
 scipy>=1.6.0,<1.8.0  # pip-only
 pygeoprocessing>=2.3.2  # pip-only
taskgraph[niced_processes]>=0.11.0  # pip-only
psutil>=5.6.6
chardet>=3.0.4
openpyxl
pint
Babel
```

And we would add a file, `constraints-binaries.txt` that contains constraints needed for the binaries:

```diff
+# constraints-binaries.txt
+#
+# If we have any version constraints needed for our binary builds (any OS),
+# this is where they go.
+
+# 3.3.0 had a bug that broke our windows builds: https://github.com/OSGeo/gdal/issues/3898
+GDAL!=3.3.0;platform_system=='Windows'
+
+# Numpy 1.16.0 had some release bugs that were patched in 1.16.1.
+# https://numpy.org/doc/stable/release/1.16.1-notes.html#numpy-1-16-1-release-notes
+numpy!=1.16.0
+
+# We've had problems with rtree builds being broken.  This is a list of broken
+# builds that we should not build InVEST against.
+Rtree!=0.9.1
```

If one wanted to install packages through `pip`, this could be done via `pip install -r requirements.txt -c constraints-binaries.txt`.

# Implications:

## Tests

To inspire greater confidence in our binary builds, I think our build matrix should use the version constraints placed on our binary builds.  If it becomes useful later on to test other combinations of packages, we can make that call later on.

## `scripts/convert-requirements-to-conda-yml.py`

Because we use `conda` in our CI environments for building and testing, we will need to update this script to resolve our requirements and constraints as `pip` does for us if we were just using `pip`.  I have not yet found a reliable way to resolve these constraints with 3rd-party tools.  If none exist, it will fall on us to implement, test and maintain this functionality.

## `.github/actions/setup_env/action.yml`

Our custom action will need to be updated to accommodate constraint files, which are then passed to `scripts/convert-requirements-to-conda-yml.py`.

## `.github/workflows/build-and-test.yml`

The appropriate constraint files will need to be provided through this configuration.  One benefit of this constraint file approach, however, is that we have the option to define different sets of constraints for different use cases as they arise.

**Comment by emlys** [comment]
wow, requirements vs. constraints! I didn't know I wanted this until now but it sounds great. Tangentially, I've wondered recently if we should check in an environment.yml rather than generating it with that script. That would be able to document at least two dependencies that are outside the scope of what pip manages (gdal binaries, and python). Yarn and NodeJS are also available through conda-forge, if that's useful for the workbench.

**Comment by phargogh** [comment]
Related, the conda folks are [working on a v2 of the conda environment file spec](https://github.com/conda/conda/issues/11341).  Just as a note-to-self while we're thinking about this.

**Comment by emlys** [comment]
Due to [this issue](https://github.com/pyinstaller/pyinstaller/issues/6301) Pyinstaller is incompatible with python 3.10.0. That would be a good use for a constraint, but python itself isn't managed by pip so it couldn't go in the `constraints.txt`.

**Comment by emlys** [comment]
FYI per [PEP 621](https://peps.python.org/pep-0621/), dependencies and optional dependencies can be specified directly in pyproject.toml. 

Also I like the idea from [this blog post](https://snarky.ca/clarifying-pep-518/) of having an `extras_require`/`optional-dependencies` called `dev` to handle your dev dependencies.
