### ISSUE TITLE
gettext '_' makes it hard to use invest in the python REPL

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#941]
```python
>>> from natcap.invest import spec_utils
>>> spec_utils.format_type_string('csv')
'`CSV <input_types.html#csv>`__'
>>> x= spec_utils.format_type_string('csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dmf\projects\invest\env\lib\site-packages\natcap\invest\spec_utils.py", line 362, in format_type_string
    'boolean': _('true/false'),
TypeError: 'str' object is not callable
```

In this case the REPL assigns to `_` implicitly on the second line. But we also have cases in invest where we assign to `_` following the convention of using that variable name for a throwaway object. Won't that also interfere with gettext trying to call `_()`?

**Comment by davemfish** [comment]
From James on slack:

>I just found this SO post adding a little more detail: https://stackoverflow.com/a/1538868
Most relevant is that _ is in __builtins__ in the REPL only and not in scripts, which is weird conditional behavior in my opinion and I personally would prefer it were in locals() but there you go.

>Even so, this’ll probably come up again, and so I wonder if we should rename the function and/or load the translation in every module it’s used in order to make the object reference as explicit as possible in order to avoid accidentally overwriting a globally-accessible variable.

**Comment by emlys** [comment]
The `_` function is an alias for [`gettext.gettext`](https://docs.python.org/3/library/gettext.html#gettext.gettext), so the simplest solution would be to use the longer name. Sounds like that will be safest since we have at least 2 possible naming conflicts (`_` as the previous returned value in the REPL, and `_` as a placeholder variable)
