### ISSUE TITLE
Minor updates requested to Cell Size ARGS_SPEC documentation for Visitation: Recreation and Tourism model

### ISSUE THREAD

**Issue by jagoldstein** [natcap/invest#942]
I'm requesting the addition of a single word to the Cell Size `ARGS_SPEC` in the Visitation: Recreation and Tourism chapter of the UG. In explaining how size is measured for the two different grid types, it currently reads:
"_If the Grid Type is square, this is the length of each side of the square. If the Grid Type is ‘hexagon’, this is the hexagon’s diameter._"

I just spent some time trying to understand how to measure the diameter of a hexagon and it turns out that there are two diameters, maximal and minimal. After examining model results in my GIS, I'm confident that cell size defines the **maximal** diameter for hexs. So, please add the word "maximal" in front of "diameter" for the hex grid type: "_If the Grid Type is ‘hexagon’, this is the hexagon’s maximal diameter._" I think this will potentially save users some time and provide clarity.

Also, it's unclear why the word "hexagon" has single quotes around it in the Cell Size `ARGS_SPEC` but the word "square" does not, so I'd suggest making that consistent by either removing the quotes around "hexagon" or adding them around "square".

**Comment by jagoldstein** [comment]
Heya @davemfish , I noticed that this `ARGS_SPEC` language has not been updated in the [UG](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/recreation.html#data-needs) yet. Is that still due to a [build failure caused by a failing workbench test](https://storage.googleapis.com/releases.naturalcapitalproject.org/invest-userguide/latest/recreation.html#data-needs)? Thanks!

**Comment by davemfish** [comment]
Hmm, yeah I think it's due to build failures in the UG repo. It looks like UG builds have been failing since we released invest 3.11, which must have been the first release with this change in it. Should be resolved soon @jagoldstein !
