### ISSUE TITLE
NDR sample data does not support nitrogen calculations

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#963]
This is noted in the sample data folder's `README`. So it's okay to leave as-is, but might be nice to fill out the biophysical table to support the Nitrogen option. Otherwise a user who loads the sample data and then enters in some parameters for the nitrogen calculations will hit a `ValueError` about missing headers in the table.

**Comment by newtpatrol** [comment]
@davemfish I'm afraid I don't understand - what does it mean that the "NDR sample data does not support nitrogen calculations"?

**Comment by davemfish** [comment]
@newtpatrol sorry for being vague. The biophysical table does not have the necessary columns so if a user loads the sample data but then selects "Calculate Nitrogen" and adds values for the other two related parameters in the UI, they will hit these errors:

```
ValueError: Missing header load_n from C:\Users\dmf\Downloads\NDR\biophysical_table_gura.csv
Missing header eff_n from C:\Users\dmf\Downloads\NDR\biophysical_table_gura.csv
Missing header crit_len_n from C:\Users\dmf\Downloads\NDR\biophysical_table_gura.csv
Missing header proportion_subsurface_n from C:\Users\dmf\Downloads\NDR\biophysical_table_gura.csv
```

**Comment by davemfish** [comment]
Okay great, thank you! The sample data is unfortunately still on bitbucket and a generally a pain to work with in version control. You may send me updated files and I'll add them @newtpatrol

**Comment by newtpatrol** [comment]
Here's new sample data for NDR, which includes nitrogen, and the .json has been updated to run both N and P, and has been exported from InVEST 3.10.2. I also removed other models' columns from the biophysical table, which I should do with other water models since it tends to confuse people. Thanks for adding it to the pile for the next release. 
[NDR _add_nitrogen.zip](https://github.com/natcap/invest/files/8759280/NDR._add_nitrogen.zip)

**Comment by davemfish** [comment]
Thank you! This just missed the cut for the upcoming release (sorry it was already in motion and we have to cut it off somewhere!) but will for sure be in the next one, likely in another month or so.

TODO:

- [ ] update sample data repo with the data linked above.

**Comment by newtpatrol** [comment]
No problem, I snoozed, I losed. :-)
