### ISSUE TITLE
Hide the language setting in the Workbench

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#966]
We have the workbench all setup to translate text, but we don't have the translations yet. So I think we should hide the widget that lets users select a language until we have the translations. Otherwise I think people will wonder why it's not working.

**Comment by emlys** [comment]
Isn't this taken care of since we only show the language setting in dev mode?
https://github.com/natcap/invest/blob/092b8d395f7fa13d4f4cdbf86302f9ed88b835bf/workbench/src/renderer/components/SettingsModal/index.jsx#L89

**Comment by davemfish** [comment]
> Isn't this taken care of since we only show the language setting in dev mode?

Aha! I had a funny feeling that we'd already dealt with this. Forgot that we purposely left it in for dev mode. Thanks!
