### ISSUE TITLE
Use PEP 420: implicit namespace packages

### ISSUE THREAD

**Issue by emlys** [natcap/invest#967]
`natcap` is a namespace package. We indicate that with the file `src/natcap/__init__.py` which contains
```
import pkg_resources
pkg_resources.declare_namespace(__name__)
```
Today I learned that that's outdated. If I'm understanding correctly, we can just delete `src/natcap/__init__.py` and it will work the same way.
https://stackoverflow.com/a/27586272/14451410
https://peps.python.org/pep-0420/
This isn't really an enhancement, just keeping up with changes in the python standards.

**Comment by emlys** [comment]
Bumping to critical because this is failing all builds. As of setuptools 62.3.0 released today, we should see a `SetuptoolsDeprecationWarning` warning us that the `namespace_packages` parameter to `setup()` is deprecated. But due to a bug (https://github.com/pypa/setuptools/issues/3320) an error is raised instead.

**Comment by abravalheri** [comment]
Sorry for the disruption. Soon the new setuptools version will be available with the fix for the unexpected error (it should only be a warning).Thank you @emlys .

Please let me know if it does not work.

**Comment by emlys** [comment]
No worries @abravalheri, thanks for fixing it so quickly!
