### ISSUE TITLE
create-dmg non-zero exit breaks Mac builds

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#984]
The problem is in `create-dmg`'s cleanup step. https://github.com/create-dmg/create-dmg/issues/133

It seems the DMG is created just fine. So in the interest of passing builds, we can probably force our workflow to continue past that failure.

**Comment by davemfish** [comment]
> It seems the DMG is created just fine. So in the interest of passing builds, we can probably force our workflow to continue past that failure.

It seems like this was incorrect. The DMG does not get created, a temporary one with a name like `rw.InVEST_3.10.2.post2555+g9a6254838.dmg` gets created early in the process, but when this error hits:

```
Unmounting disk image...
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```

We still don't have a functional DMG, only the temp one.

**Comment by phargogh** [comment]
I'm trying out increasing the number of retries in a script to see if that does anything.

**Comment by davemfish** [comment]
We just talked this over and it seems like we'll need to modify `create-dmg` to the point where it makes sense to check-in and maintain our own script calling `hdiutil`. We can start by forking `create-dmg`, or just using it as a reference.

**Comment by dcdenu4** [comment]
Emily modified create-dmg and was able to produce a successful run by iterating on detach to allow for more tries.
