### ISSUE TITLE
Jest is slow; sometimes causes timeouts

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#988]
Occasionally a workbench test will fail on Windows because jest exceeded it's default timeout of 5s. 
```
FAIL tests/renderer/app.test.js (31.464 s)
  Various ways to open and close InVEST models
    × Clicking an invest model button renders SetupTab (6065 ms)
```
https://github.com/natcap/invest/runs/6414664777?check_suite_focus=true

I don't see anything wrong with this test, it's quite similar to other tests that never fail. And it never fails when run locally, only in CI.

It's interesting that this test is the first one jest tries to run. Scanning the runtimes of all the tests, I see a pattern where tests in the first file that runs take longer than they otherwise would. When I `yarn run test` locally, `flaskapp.test.js` is the first file run. On Actions, `app.test.js` runs first.

In each case, the tests take longer when they are the first ones that jest runs. Here are the total runtimes for the whole file, but I can also see the times of individual tests, and they are also inflated, so it's not strictly some jest startup thing adding to the runtime.

`tests/invest/flaskapp.test.js (81.588 s)` -- first, local
`tests/invest/flaskapp.test.js (53.382 s)` -- not first, CI

`tests/renderer/app.test.js (31.464 s)` -- first, CI 
`tests/renderer/app.test.js (8.486 s)` -- not first, local

We're already using `--runInBand` which is supposed to avoid using a process pool, which would otherwise explain a longer time to startup.

I'm not sure what to do, other than allowing a longer jest timeout for CI.

**Comment by emlys** [comment]
If Vitest works well for us in the urban online project, do you think it'd be worth transitioning the workbench from Jest to Vitest?

**Comment by davemfish** [comment]
Maybe! I'm not sure if we could fully give up jest, as we use it to run tests for code running in the main process, not just the renderer. And vitest, I assume, is designed for testing browser code. But even so, it might make sense to use vitest for the renderer tests, and possibly for others. Let's wait and see though, vitest is a lot less mature of a project than jest.

**Comment by davemfish** [comment]
Looking at a recent Actions job https://github.com/natcap/invest/actions/runs/4622649074/jobs/8197601130

I don't see the lengthy execution times on the first test file. And I don't **think** we've seen an actual jest timeout on the first test in quite some time. So I'll close this and we can re-open if it comes up again.
